/* Generated by Nim Compiler v0.14.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/john/code/Nim/lib -o /media/sf_D_DRIVE/Work/Code/nim-raytracer/src/src/nimcache/cairo_cairo.o /media/sf_D_DRIVE/Work/Code/nim-raytracer/src/src/nimcache/cairo_cairo.c */
#define NIM_INTBITS 32

#include "nimbase.h"
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct Tcontext150490 Tcontext150490;
typedef struct Tsurface150492 Tsurface150492;
typedef struct Tuserdatakey150504 Tuserdatakey150504;
typedef struct Tpattern150494 Tpattern150494;
typedef struct Tmatrix150502 Tmatrix150502;
typedef struct Trectanglelist150518 Trectanglelist150518;
typedef struct Tfontoptions150500 Tfontoptions150500;
typedef struct Tfontface150498 Tfontface150498;
typedef struct Tscaledfont150496 Tscaledfont150496;
typedef struct Tglyph150506 Tglyph150506;
typedef struct Ttextextents150508 Ttextextents150508;
typedef struct Tfontextents150510 Tfontextents150510;
typedef struct Tpath150514 Tpath150514;
typedef struct Outofmemerror3450 Outofmemerror3450;
typedef struct Systemerror3426 Systemerror3426;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell47305 Cell47305;
typedef struct Cellseq47321 Cellseq47321;
typedef struct Gcheap49818 Gcheap49818;
typedef struct Gcstack49816 Gcstack49816;
typedef struct Memregion29485 Memregion29485;
typedef struct Smallchunk29439 Smallchunk29439;
typedef struct Llchunk29479 Llchunk29479;
typedef struct Bigchunk29441 Bigchunk29441;
typedef struct Intset29414 Intset29414;
typedef struct Trunk29410 Trunk29410;
typedef struct Avlnode29483 Avlnode29483;
typedef struct Gcstat49814 Gcstat49814;
typedef struct Cellset47317 Cellset47317;
typedef struct Pagedesc47313 Pagedesc47313;
typedef struct Ioerror3428 Ioerror3428;
typedef struct Assertionerror3444 Assertionerror3444;
typedef struct Trectangle150516 Trectangle150516;
typedef struct Tpathdata150512 Tpathdata150512;
typedef struct Basechunk29437 Basechunk29437;
typedef struct Freecell29429 Freecell29429;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(NI32, TY150716) (void);
typedef N_CDECL_PTR(NCSTRING, TY150718) (void);
typedef N_CDECL_PTR(Tcontext150490*, TY150726) (Tsurface150492* target0);
typedef N_CDECL_PTR(Tcontext150490*, TY150729) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void, TY150732) (Tcontext150490* cr0);
typedef N_CDECL_PTR(NI32, TY150735) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void*, TY150738) (Tcontext150490* cr0, Tuserdatakey150504* key0);
typedef NU8 Tstatus150406;
typedef N_CDECL_PTR(void, Tdestroyfunc150484) (void* data0);
typedef N_CDECL_PTR(Tstatus150406, TY150742) (Tcontext150490* cr0, Tuserdatakey150504* key0, void* userdata0, Tdestroyfunc150484 destroy0);
typedef N_CDECL_PTR(void, TY150748) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void, TY150751) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void, TY150754) (Tcontext150490* cr0);
typedef NU16 Tcontent150430;
typedef N_CDECL_PTR(void, TY150757) (Tcontext150490* cr0, Tcontent150430 content0);
typedef N_CDECL_PTR(Tpattern150494*, TY150761) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void, TY150764) (Tcontext150490* cr0);
typedef NU8 Toperator150408;
typedef N_CDECL_PTR(void, TY150767) (Tcontext150490* cr0, Toperator150408 op0);
typedef N_CDECL_PTR(void, TY150771) (Tcontext150490* cr0, Tpattern150494* source0);
typedef N_CDECL_PTR(void, TY150775) (Tcontext150490* cr0, NF red0, NF green0, NF blue0);
typedef N_CDECL_PTR(void, TY150781) (Tcontext150490* cr0, NF red0, NF green0, NF blue0, NF alpha0);
typedef N_CDECL_PTR(void, TY150788) (Tcontext150490* cr0, Tsurface150492* surface0, NF x0, NF y0);
typedef N_CDECL_PTR(void, TY150794) (Tcontext150490* cr0, NF tolerance0);
typedef NU8 Tantialias150410;
typedef N_CDECL_PTR(void, TY150798) (Tcontext150490* cr0, Tantialias150410 antialias0);
typedef NU8 Tfillrule150412;
typedef N_CDECL_PTR(void, TY150802) (Tcontext150490* cr0, Tfillrule150412 fillrule0);
typedef N_CDECL_PTR(void, TY150806) (Tcontext150490* cr0, NF width0);
typedef NU8 Tlinecap150414;
typedef N_CDECL_PTR(void, TY150810) (Tcontext150490* cr0, Tlinecap150414 linecap0);
typedef NU8 Tlinejoin150416;
typedef N_CDECL_PTR(void, TY150814) (Tcontext150490* cr0, Tlinejoin150416 linejoin0);
typedef N_CDECL_PTR(void, TY150818) (Tcontext150490* cr0, NF* dashes0, NI dashes0Len0, NF offset0);
typedef N_CDECL_PTR(void, TY150824) (Tcontext150490* cr0, NF limit0);
typedef N_CDECL_PTR(void, TY150828) (Tcontext150490* cr0, NF tx0, NF ty0);
typedef N_CDECL_PTR(void, TY150833) (Tcontext150490* cr0, NF sx0, NF sy0);
typedef N_CDECL_PTR(void, TY150838) (Tcontext150490* cr0, NF angle0);
typedef N_CDECL_PTR(void, TY150842) (Tcontext150490* cr0, Tmatrix150502* matrix0);
typedef N_CDECL_PTR(void, TY150846) (Tcontext150490* cr0, Tmatrix150502* matrix0);
typedef N_CDECL_PTR(void, TY150850) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void, TY150853) (Tcontext150490* cr0, NF* x0, NF* y0);
typedef N_CDECL_PTR(void, TY150859) (Tcontext150490* cr0, NF* dx0, NF* dy0);
typedef N_CDECL_PTR(void, TY150865) (Tcontext150490* cr0, NF* x0, NF* y0);
typedef N_CDECL_PTR(void, TY150871) (Tcontext150490* cr0, NF* dx0, NF* dy0);
typedef N_CDECL_PTR(void, TY150877) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void, TY150880) (Tcontext150490* cr0, NF x0, NF y0);
typedef N_CDECL_PTR(void, TY150885) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void, TY150888) (Tcontext150490* cr0, NF x0, NF y0);
typedef N_CDECL_PTR(void, TY150893) (Tcontext150490* cr0, NF x10, NF y10, NF x20, NF y20, NF x30, NF y30);
typedef N_CDECL_PTR(void, TY150902) (Tcontext150490* cr0, NF xc0, NF yc0, NF radius0, NF angle10, NF angle20);
typedef N_CDECL_PTR(void, TY150910) (Tcontext150490* cr0, NF xc0, NF yc0, NF radius0, NF angle10, NF angle20);
typedef N_CDECL_PTR(void, TY150918) (Tcontext150490* cr0, NF dx0, NF dy0);
typedef N_CDECL_PTR(void, TY150923) (Tcontext150490* cr0, NF dx0, NF dy0);
typedef N_CDECL_PTR(void, TY150928) (Tcontext150490* cr0, NF dx10, NF dy10, NF dx20, NF dy20, NF dx30, NF dy30);
typedef N_CDECL_PTR(void, TY150937) (Tcontext150490* cr0, NF x0, NF y0, NF width0, NF height0);
typedef N_CDECL_PTR(void, TY150944) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void, TY150947) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void, TY150950) (Tcontext150490* cr0, NF alpha0);
typedef N_CDECL_PTR(void, TY150954) (Tcontext150490* cr0, Tpattern150494* pattern0);
typedef N_CDECL_PTR(void, TY150958) (Tcontext150490* cr0, Tsurface150492* surface0, NF surfacex0, NF surfacey0);
typedef N_CDECL_PTR(void, TY150964) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void, TY150967) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void, TY150970) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void, TY150973) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void, TY150976) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void, TY150979) (Tcontext150490* cr0);
typedef N_CDECL_PTR(NI32, TY150982) (Tcontext150490* cr0, NF x0, NF y0);
typedef N_CDECL_PTR(NI32, TY150987) (Tcontext150490* cr0, NF x0, NF y0);
typedef N_CDECL_PTR(void, TY150992) (Tcontext150490* cr0, NF* x10, NF* y10, NF* x20, NF* y20);
typedef N_CDECL_PTR(void, TY151000) (Tcontext150490* cr0, NF* x10, NF* y10, NF* x20, NF* y20);
typedef N_CDECL_PTR(void, TY151008) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void, TY151011) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void, TY151014) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void, TY151017) (Tcontext150490* cr0, NF* x10, NF* y10, NF* x20, NF* y20);
typedef N_CDECL_PTR(Trectanglelist150518*, TY151025) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void, TY151028) (Trectanglelist150518* rectanglelist0);
typedef N_CDECL_PTR(Tfontoptions150500*, TY151031) (void);
typedef N_CDECL_PTR(Tfontoptions150500*, TY151033) (Tfontoptions150500* original0);
typedef N_CDECL_PTR(void, TY151036) (Tfontoptions150500* options0);
typedef N_CDECL_PTR(Tstatus150406, TY151039) (Tfontoptions150500* options0);
typedef N_CDECL_PTR(void, TY151042) (Tfontoptions150500* options0, Tfontoptions150500* other0);
typedef N_CDECL_PTR(NI32, TY151046) (Tfontoptions150500* options0, Tfontoptions150500* other0);
typedef N_CDECL_PTR(NI32, TY151050) (Tfontoptions150500* options0);
typedef N_CDECL_PTR(void, TY151053) (Tfontoptions150500* options0, Tantialias150410 antialias0);
typedef N_CDECL_PTR(Tantialias150410, TY151057) (Tfontoptions150500* options0);
typedef NU8 Tsubpixelorder150422;
typedef N_CDECL_PTR(void, TY151060) (Tfontoptions150500* options0, Tsubpixelorder150422 subpixelorder0);
typedef N_CDECL_PTR(Tsubpixelorder150422, TY151064) (Tfontoptions150500* options0);
typedef NU8 Thintstyle150424;
typedef N_CDECL_PTR(void, TY151067) (Tfontoptions150500* options0, Thintstyle150424 hintstyle0);
typedef N_CDECL_PTR(Thintstyle150424, TY151071) (Tfontoptions150500* options0);
typedef NU8 Thintmetrics150426;
typedef N_CDECL_PTR(void, TY151074) (Tfontoptions150500* options0, Thintmetrics150426 hintmetrics0);
typedef N_CDECL_PTR(Thintmetrics150426, TY151078) (Tfontoptions150500* options0);
typedef NU8 Tfontslant150418;
typedef NU8 Tfontweight150420;
typedef N_CDECL_PTR(void, TY151081) (Tcontext150490* cr0, NCSTRING family0, Tfontslant150418 slant0, Tfontweight150420 weight0);
typedef N_CDECL_PTR(void, TY151087) (Tcontext150490* cr0, NF size0);
typedef N_CDECL_PTR(void, TY151091) (Tcontext150490* cr0, Tmatrix150502* matrix0);
typedef N_CDECL_PTR(void, TY151095) (Tcontext150490* cr0, Tmatrix150502* matrix0);
typedef N_CDECL_PTR(void, TY151099) (Tcontext150490* cr0, Tfontoptions150500* options0);
typedef N_CDECL_PTR(void, TY151103) (Tcontext150490* cr0, Tfontoptions150500* options0);
typedef N_CDECL_PTR(void, TY151107) (Tcontext150490* cr0, Tfontface150498* fontface0);
typedef N_CDECL_PTR(Tfontface150498*, TY151111) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void, TY151114) (Tcontext150490* cr0, Tscaledfont150496* scaledfont0);
typedef N_CDECL_PTR(Tscaledfont150496*, TY151118) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void, TY151121) (Tcontext150490* cr0, NCSTRING utf80);
typedef N_CDECL_PTR(void, TY151125) (Tcontext150490* cr0, Tglyph150506* glyphs0, NI32 numglyphs0);
typedef N_CDECL_PTR(void, TY151130) (Tcontext150490* cr0, NCSTRING utf80);
typedef N_CDECL_PTR(void, TY151134) (Tcontext150490* cr0, Tglyph150506* glyphs0, NI32 numglyphs0);
typedef N_CDECL_PTR(void, TY151139) (Tcontext150490* cr0, NCSTRING utf80, Ttextextents150508* extents0);
typedef N_CDECL_PTR(void, TY151144) (Tcontext150490* cr0, Tglyph150506* glyphs0, NI32 numglyphs0, Ttextextents150508* extents0);
typedef N_CDECL_PTR(void, TY151150) (Tcontext150490* cr0, Tfontextents150510* extents0);
typedef N_CDECL_PTR(Tfontface150498*, TY151154) (Tfontface150498* fontface0);
typedef N_CDECL_PTR(void, TY151157) (Tfontface150498* fontface0);
typedef N_CDECL_PTR(NI32, TY151160) (Tfontface150498* fontface0);
typedef N_CDECL_PTR(Tstatus150406, TY151163) (Tfontface150498* fontface0);
typedef NU8 Tfonttype150438;
typedef N_CDECL_PTR(Tfonttype150438, TY151166) (Tfontface150498* fontface0);
typedef N_CDECL_PTR(void*, TY151169) (Tfontface150498* fontface0, Tuserdatakey150504* key0);
typedef N_CDECL_PTR(Tstatus150406, TY151173) (Tfontface150498* fontface0, Tuserdatakey150504* key0, void* userdata0, Tdestroyfunc150484 destroy0);
typedef N_CDECL_PTR(Tscaledfont150496*, TY151179) (Tfontface150498* fontface0, Tmatrix150502* fontmatrix0, Tmatrix150502* ctm0, Tfontoptions150500* options0);
typedef N_CDECL_PTR(Tscaledfont150496*, TY151185) (Tscaledfont150496* scaledfont0);
typedef N_CDECL_PTR(void, TY151188) (Tscaledfont150496* scaledfont0);
typedef N_CDECL_PTR(NI32, TY151191) (Tscaledfont150496* scaledfont0);
typedef N_CDECL_PTR(Tstatus150406, TY151194) (Tscaledfont150496* scaledfont0);
typedef N_CDECL_PTR(Tfonttype150438, TY151197) (Tscaledfont150496* scaledfont0);
typedef N_CDECL_PTR(void*, TY151200) (Tscaledfont150496* scaledfont0, Tuserdatakey150504* key0);
typedef N_CDECL_PTR(Tstatus150406, TY151204) (Tscaledfont150496* scaledfont0, Tuserdatakey150504* key0, void* userdata0, Tdestroyfunc150484 destroy0);
typedef N_CDECL_PTR(void, TY151210) (Tscaledfont150496* scaledfont0, Tfontextents150510* extents0);
typedef N_CDECL_PTR(void, TY151214) (Tscaledfont150496* scaledfont0, NCSTRING utf80, Ttextextents150508* extents0);
typedef N_CDECL_PTR(void, TY151219) (Tscaledfont150496* scaledfont0, Tglyph150506* glyphs0, NI32 numglyphs0, Ttextextents150508* extents0);
typedef N_CDECL_PTR(Tfontface150498*, TY151225) (Tscaledfont150496* scaledfont0);
typedef N_CDECL_PTR(void, TY151228) (Tscaledfont150496* scaledfont0, Tmatrix150502* fontmatrix0);
typedef N_CDECL_PTR(void, TY151232) (Tscaledfont150496* scaledfont0, Tmatrix150502* ctm0);
typedef N_CDECL_PTR(void, TY151236) (Tscaledfont150496* scaledfont0, Tfontoptions150500* options0);
typedef N_CDECL_PTR(Toperator150408, TY151240) (Tcontext150490* cr0);
typedef N_CDECL_PTR(Tpattern150494*, TY151243) (Tcontext150490* cr0);
typedef N_CDECL_PTR(NF, TY151246) (Tcontext150490* cr0);
typedef N_CDECL_PTR(Tantialias150410, TY151249) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void, TY151252) (Tcontext150490* cr0, NF* x0, NF* y0);
typedef N_CDECL_PTR(Tfillrule150412, TY151258) (Tcontext150490* cr0);
typedef N_CDECL_PTR(NF, TY151261) (Tcontext150490* cr0);
typedef N_CDECL_PTR(Tlinecap150414, TY151264) (Tcontext150490* cr0);
typedef N_CDECL_PTR(Tlinejoin150416, TY151267) (Tcontext150490* cr0);
typedef N_CDECL_PTR(NF, TY151270) (Tcontext150490* cr0);
typedef N_CDECL_PTR(NI32, TY151273) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void, TY151276) (Tcontext150490* cr0, NF* dashes0, NF* offset0);
typedef N_CDECL_PTR(void, TY151282) (Tcontext150490* cr0, Tmatrix150502* matrix0);
typedef N_CDECL_PTR(Tsurface150492*, TY151286) (Tcontext150490* cr0);
typedef N_CDECL_PTR(Tsurface150492*, TY151289) (Tcontext150490* cr0);
typedef N_CDECL_PTR(Tpath150514*, TY151292) (Tcontext150490* cr0);
typedef N_CDECL_PTR(Tpath150514*, TY151295) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void, TY151298) (Tcontext150490* cr0, Tpath150514* path0);
typedef N_CDECL_PTR(void, TY151302) (Tpath150514* path0);
typedef N_CDECL_PTR(Tstatus150406, TY151305) (Tcontext150490* cr0);
typedef N_CDECL_PTR(NCSTRING, TY151308) (Tstatus150406 status0);
typedef N_CDECL_PTR(Tsurface150492*, TY151311) (Tsurface150492* other0, Tcontent150430 content0, NI32 width0, NI32 height0);
typedef N_CDECL_PTR(Tsurface150492*, TY151317) (Tsurface150492* surface0);
typedef N_CDECL_PTR(void, TY151320) (Tsurface150492* surface0);
typedef N_CDECL_PTR(void, TY151323) (Tsurface150492* surface0);
typedef N_CDECL_PTR(NI32, TY151326) (Tsurface150492* surface0);
typedef N_CDECL_PTR(Tstatus150406, TY151329) (Tsurface150492* surface0);
typedef NU8 Tsurfacetype150442;
typedef N_CDECL_PTR(Tsurfacetype150442, TY151332) (Tsurface150492* surface0);
typedef N_CDECL_PTR(Tcontent150430, TY151335) (Tsurface150492* surface0);
typedef N_CDECL_PTR(Tstatus150406, TY151338) (Tsurface150492* surface0, NCSTRING filename0);
typedef N_CDECL_PTR(Tstatus150406, Twritefunc150486) (void* closure0, NCSTRING data0, NI32 len0);
typedef N_CDECL_PTR(Tstatus150406, TY151342) (Tsurface150492* surface0, Twritefunc150486 writefunc0, void* closure0);
typedef N_CDECL_PTR(void*, TY151347) (Tsurface150492* surface0, Tuserdatakey150504* key0);
typedef N_CDECL_PTR(Tstatus150406, TY151351) (Tsurface150492* surface0, Tuserdatakey150504* key0, void* userdata0, Tdestroyfunc150484 destroy0);
typedef N_CDECL_PTR(void, TY151357) (Tsurface150492* surface0, Tfontoptions150500* options0);
typedef N_CDECL_PTR(void, TY151361) (Tsurface150492* surface0);
typedef N_CDECL_PTR(void, TY151364) (Tsurface150492* surface0);
typedef N_CDECL_PTR(void, TY151367) (Tsurface150492* surface0, NI32 x0, NI32 y0, NI32 width0, NI32 height0);
typedef N_CDECL_PTR(void, TY151374) (Tsurface150492* surface0, NF xoffset0, NF yoffset0);
typedef N_CDECL_PTR(void, TY151379) (Tsurface150492* surface0, NF* xoffset0, NF* yoffset0);
typedef N_CDECL_PTR(void, TY151385) (Tsurface150492* surface0, NF xpixelsperinch0, NF ypixelsperinch0);
typedef NU8 Tformat150432;
typedef N_CDECL_PTR(Tsurface150492*, TY151390) (Tformat150432 format0, NI32 width0, NI32 height0);
typedef N_CDECL_PTR(Tsurface150492*, TY151395) (NCSTRING data0, Tformat150432 format0, NI32 width0, NI32 height0, NI32 stride0);
typedef N_CDECL_PTR(NCSTRING, TY151402) (Tsurface150492* surface0);
typedef N_CDECL_PTR(Tformat150432, TY151405) (Tsurface150492* surface0);
typedef N_CDECL_PTR(NI32, TY151408) (Tsurface150492* surface0);
typedef N_CDECL_PTR(NI32, TY151411) (Tsurface150492* surface0);
typedef N_CDECL_PTR(NI32, TY151414) (Tsurface150492* surface0);
typedef N_CDECL_PTR(Tsurface150492*, TY151417) (NCSTRING filename0);
typedef N_CDECL_PTR(Tstatus150406, Treadfunc150488) (void* closure0, NCSTRING data0, NI32 len0);
typedef N_CDECL_PTR(Tsurface150492*, TY151420) (Treadfunc150488 readfunc0, void* closure0);
typedef N_CDECL_PTR(Tpattern150494*, TY151424) (NF red0, NF green0, NF blue0);
typedef N_CDECL_PTR(Tpattern150494*, TY151429) (NF red0, NF green0, NF blue0, NF alpha0);
typedef N_CDECL_PTR(Tpattern150494*, TY151435) (Tsurface150492* surface0);
typedef N_CDECL_PTR(Tpattern150494*, TY151438) (NF x00, NF y00, NF x10, NF y10);
typedef N_CDECL_PTR(Tpattern150494*, TY151444) (NF cx00, NF cy00, NF radius00, NF cx10, NF cy10, NF radius10);
typedef N_CDECL_PTR(Tpattern150494*, TY151452) (Tpattern150494* pattern0);
typedef N_CDECL_PTR(void, TY151455) (Tpattern150494* pattern0);
typedef N_CDECL_PTR(NI32, TY151458) (Tpattern150494* pattern0);
typedef N_CDECL_PTR(Tstatus150406, TY151461) (Tpattern150494* pattern0);
typedef N_CDECL_PTR(void*, TY151464) (Tpattern150494* pattern0, Tuserdatakey150504* key0);
typedef N_CDECL_PTR(Tstatus150406, TY151468) (Tpattern150494* pattern0, Tuserdatakey150504* key0, void* userdata0, Tdestroyfunc150484 destroy0);
typedef NU8 Tpatterntype150440;
typedef N_CDECL_PTR(Tpatterntype150440, TY151474) (Tpattern150494* pattern0);
typedef N_CDECL_PTR(void, TY151477) (Tpattern150494* pattern0, NF offset0, NF red0, NF green0, NF blue0);
typedef N_CDECL_PTR(void, TY151484) (Tpattern150494* pattern0, NF offset0, NF red0, NF green0, NF blue0, NF alpha0);
typedef N_CDECL_PTR(void, TY151492) (Tpattern150494* pattern0, Tmatrix150502* matrix0);
typedef N_CDECL_PTR(void, TY151496) (Tpattern150494* pattern0, Tmatrix150502* matrix0);
typedef NU8 Textend150434;
typedef N_CDECL_PTR(void, TY151500) (Tpattern150494* pattern0, Textend150434 extend0);
typedef N_CDECL_PTR(Textend150434, TY151504) (Tpattern150494* pattern0);
typedef NU8 Tfilter150436;
typedef N_CDECL_PTR(void, TY151507) (Tpattern150494* pattern0, Tfilter150436 filter0);
typedef N_CDECL_PTR(Tfilter150436, TY151511) (Tpattern150494* pattern0);
typedef N_CDECL_PTR(Tstatus150406, TY151514) (Tpattern150494* pattern0, NF* red0, NF* green0, NF* blue0, NF* alpha0);
typedef N_CDECL_PTR(Tstatus150406, TY151522) (Tpattern150494* pattern0, Tsurface150492** surface0);
typedef N_CDECL_PTR(Tstatus150406, TY151526) (Tpattern150494* pattern0, NI32 index0, NF* offset0, NF* red0, NF* green0, NF* blue0, NF* alpha0);
typedef N_CDECL_PTR(Tstatus150406, TY151536) (Tpattern150494* pattern0, NI32* count0);
typedef N_CDECL_PTR(Tstatus150406, TY151541) (Tpattern150494* pattern0, NF* x00, NF* y00, NF* x10, NF* y10);
typedef N_CDECL_PTR(Tstatus150406, TY151549) (Tpattern150494* pattern0, NF* x00, NF* y00, NF* r00, NF* x10, NF* y10, NF* r10);
typedef N_CDECL_PTR(void, TY151559) (Tmatrix150502* matrix0, NF xx0, NF yx0, NF xy0, NF yy0, NF x00, NF y00);
typedef N_CDECL_PTR(void, TY151568) (Tmatrix150502* matrix0);
typedef N_CDECL_PTR(void, TY151571) (Tmatrix150502* matrix0, NF tx0, NF ty0);
typedef N_CDECL_PTR(void, TY151576) (Tmatrix150502* matrix0, NF sx0, NF sy0);
typedef N_CDECL_PTR(void, TY151581) (Tmatrix150502* matrix0, NF radians0);
typedef N_CDECL_PTR(void, TY151585) (Tmatrix150502* matrix0, NF tx0, NF ty0);
typedef N_CDECL_PTR(void, TY151590) (Tmatrix150502* matrix0, NF sx0, NF sy0);
typedef N_CDECL_PTR(void, TY151595) (Tmatrix150502* matrix0, NF radians0);
typedef N_CDECL_PTR(Tstatus150406, TY151599) (Tmatrix150502* matrix0);
typedef N_CDECL_PTR(void, TY151602) (Tmatrix150502* result0, Tmatrix150502* a0, Tmatrix150502* b0);
typedef N_CDECL_PTR(void, TY151607) (Tmatrix150502* matrix0, NF* dx0, NF* dy0);
typedef N_CDECL_PTR(void, TY151613) (Tmatrix150502* matrix0, NF* x0, NF* y0);
typedef N_CDECL_PTR(Tsurface150492*, TY151619) (NCSTRING filename0, NF widthinpoints0, NF heightinpoints0);
typedef N_CDECL_PTR(Tsurface150492*, TY151624) (Twritefunc150486 writefunc0, void* closure0, NF widthinpoints0, NF heightinpoints0);
typedef N_CDECL_PTR(void, TY151630) (Tsurface150492* surface0, NF widthinpoints0, NF heightinpoints0);
typedef N_CDECL_PTR(Tsurface150492*, TY151635) (NCSTRING filename0, NF widthinpoints0, NF heightinpoints0);
typedef N_CDECL_PTR(Tsurface150492*, TY151640) (Twritefunc150486 writefunc0, void* closure0, NF widthinpoints0, NF heightinpoints0);
typedef N_CDECL_PTR(void, TY151646) (Tsurface150492* surface0, NF widthinpoints0, NF heightinpoints0);
typedef N_CDECL_PTR(void, TY151651) (Tsurface150492* surface0, NCSTRING comment0);
typedef N_CDECL_PTR(void, TY151655) (Tsurface150492* surface0);
typedef N_CDECL_PTR(void, TY151658) (Tsurface150492* surface0);
typedef N_CDECL_PTR(Tsurface150492*, TY151661) (NCSTRING filename0, NF widthinpoints0, NF heightinpoints0);
typedef N_CDECL_PTR(Tsurface150492*, TY151666) (Twritefunc150486 writefunc0, void* closure0, NF widthinpoints0, NF heightinpoints0);
typedef NU8 Tsvgversion150444;
typedef N_CDECL_PTR(void, TY151672) (Tsurface150492* surface0, Tsvgversion150444 version0);
typedef N_CDECL_PTR(NCSTRING, TY151676) (Tsvgversion150444 version0);
typedef N_CDECL_PTR(void, TY151679) (void);
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Systemerror3426  {
  Exception Sup;
};
struct  Outofmemerror3450  {
  Systemerror3426 Sup;
};
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell47305  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47321  {
NI len;
NI cap;
Cell47305** d;
};
typedef Smallchunk29439* TY29500[512];
typedef Trunk29410* Trunkbuckets29412[256];
struct  Intset29414  {
Trunkbuckets29412 data;
};
struct  Memregion29485  {
NI minlargeobj;
NI maxlargeobj;
TY29500 freesmallchunks;
Llchunk29479* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk29441* freechunkslist;
Intset29414 chunkstarts;
Avlnode29483* root;
Avlnode29483* deleted;
Avlnode29483* last;
Avlnode29483* freeavlnodes;
NIM_BOOL locked;
};
struct  Gcstat49814  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset47317  {
NI counter;
NI max;
Pagedesc47313* head;
Pagedesc47313** data;
};
struct  Gcheap49818  {
Gcstack49816* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47321 zct;
Cellseq47321 decstack;
Cellseq47321 tempstack;
NI recgclock;
Memregion29485 region;
Gcstat49814 stat;
Cellset47317 marked;
Cellseq47321 additionalroots;
};
struct  Ioerror3428  {
  Systemerror3426 Sup;
};
struct  Assertionerror3444  {
  Exception Sup;
};
typedef N_CDECL_PTR(Tsurface150492*, TY151735) (Tsurface150492* target0, double x0, double y0, double w0, double h0);
struct  Tcontext150490  {
char dummy;
};
struct  Tsurface150492  {
char dummy;
};
struct  Tuserdatakey150504  {
NI32 unused;
};
struct  Tpattern150494  {
char dummy;
};
struct  Tmatrix150502  {
NF xx;
NF yx;
NF xy;
NF yy;
NF x0;
NF y0;
};
struct  Trectanglelist150518  {
Tstatus150406 status;
Trectangle150516* rectangles;
NI32 numrectangles;
};
struct  Tfontoptions150500  {
char dummy;
};
struct  Tfontface150498  {
char dummy;
};
struct  Tscaledfont150496  {
char dummy;
};
struct  Tglyph150506  {
NI32 index;
NF x;
NF y;
};
struct  Ttextextents150508  {
NF xbearing;
NF ybearing;
NF width;
NF height;
NF xadvance;
NF yadvance;
};
struct  Tfontextents150510  {
NF ascent;
NF descent;
NF height;
NF maxxadvance;
NF maxyadvance;
};
struct  Tpath150514  {
Tstatus150406 status;
Tpathdata150512* data;
NI32 numdata;
};
struct  Gcstack49816  {
Gcstack49816* prev;
Gcstack49816* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk29437  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk29439  {
  Basechunk29437 Sup;
Smallchunk29439* next;
Smallchunk29439* prev;
Freecell29429* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk29479  {
NI size;
NI acc;
Llchunk29479* next;
};
struct  Bigchunk29441  {
  Basechunk29437 Sup;
Bigchunk29441* next;
Bigchunk29441* prev;
NI align;
NF data;
};
typedef NI TY29418[16];
struct  Trunk29410  {
Trunk29410* next;
NI key;
TY29418 bits;
};
typedef Avlnode29483* TY29490[2];
struct  Avlnode29483  {
TY29490 link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc47313  {
Pagedesc47313* next;
NI key;
TY29418 bits;
};
struct  Trectangle150516  {
NF x;
NF y;
NF width;
NF height;
};
struct  Tpathdata150512  {
NF x;
NF y;
};
struct  Freecell29429  {
Freecell29429* next;
NI zerofield;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path0);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path0);
N_NIMCALL(void*, nimGetProcAddr)(void* lib0, NCSTRING name0);
N_NIMCALL(void, version_150719_77748642)(NI32* major0, NI32* minor0, NI32* micro0);
static N_INLINE(NI, divInt)(NI a0, NI b0);
N_NOINLINE(void, raiseDivByZero)(void);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI, mulInt)(NI a0, NI b0);
static N_INLINE(NI, modInt)(NI a0, NI b0);
static N_INLINE(NI, addInt)(NI a0, NI b0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_21201_1689653243)(void);
static N_INLINE(void, popFrame)(void);
N_NOINLINE(void, checkstatus_151688_77748642)(Tstatus150406 s0);
N_NIMCALL(void*, newObj)(TNimType* typ0, NI size0);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str0);
static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0);
static N_INLINE(Cell47305*, usrtocell_51440_1689653243)(void* usr0);
static N_INLINE(void, rtladdzct_52601_1689653243)(Cell47305* c0);
N_NOINLINE(void, addzct_51417_1689653243)(Cellseq47321* s0, Cell47305* c0);
N_NIMCALL(void, raiseException)(Exception* e0, NCSTRING ename0);
STRING_LITERAL(T77748642_4, "libcairo.so", 11);
STRING_LITERAL(T77748642_6, "libcairo.so.2", 13);
STRING_LITERAL(T77748642_7, "libcairo.so(|.2)", 16);
static void* T77748642_2;
TY150716 Dl_150715;
TY150718 Dl_150717;
TY150726 Dl_150725;
TY150729 Dl_150728;
TY150732 Dl_150731;
TY150735 Dl_150734;
TY150738 Dl_150737;
TY150742 Dl_150741;
TY150748 Dl_150747;
TY150751 Dl_150750;
TY150754 Dl_150753;
TY150757 Dl_150756;
TY150761 Dl_150760;
TY150764 Dl_150763;
TY150767 Dl_150766;
TY150771 Dl_150770;
TY150775 Dl_150774;
TY150781 Dl_150780;
TY150788 Dl_150787;
TY150794 Dl_150793;
TY150798 Dl_150797;
TY150802 Dl_150801;
TY150806 Dl_150805;
TY150810 Dl_150809;
TY150814 Dl_150813;
TY150818 Dl_150817;
TY150824 Dl_150823;
TY150828 Dl_150827;
TY150833 Dl_150832;
TY150838 Dl_150837;
TY150842 Dl_150841;
TY150846 Dl_150845;
TY150850 Dl_150849;
TY150853 Dl_150852;
TY150859 Dl_150858;
TY150865 Dl_150864;
TY150871 Dl_150870;
TY150877 Dl_150876;
TY150880 Dl_150879;
TY150885 Dl_150884;
TY150888 Dl_150887;
TY150893 Dl_150892;
TY150902 Dl_150901;
TY150910 Dl_150909;
TY150918 Dl_150917;
TY150923 Dl_150922;
TY150928 Dl_150927;
TY150937 Dl_150936;
TY150944 Dl_150943;
TY150947 Dl_150946;
TY150950 Dl_150949;
TY150954 Dl_150953;
TY150958 Dl_150957;
TY150964 Dl_150963;
TY150967 Dl_150966;
TY150970 Dl_150969;
TY150973 Dl_150972;
TY150976 Dl_150975;
TY150979 Dl_150978;
TY150982 Dl_150981;
TY150987 Dl_150986;
TY150992 Dl_150991;
TY151000 Dl_150999;
TY151008 Dl_151007;
TY151011 Dl_151010;
TY151014 Dl_151013;
TY151017 Dl_151016;
TY151025 Dl_151024;
TY151028 Dl_151027;
TY151031 Dl_151030;
TY151033 Dl_151032;
TY151036 Dl_151035;
TY151039 Dl_151038;
TY151042 Dl_151041;
TY151046 Dl_151045;
TY151050 Dl_151049;
TY151053 Dl_151052;
TY151057 Dl_151056;
TY151060 Dl_151059;
TY151064 Dl_151063;
TY151067 Dl_151066;
TY151071 Dl_151070;
TY151074 Dl_151073;
TY151078 Dl_151077;
TY151081 Dl_151080;
TY151087 Dl_151086;
TY151091 Dl_151090;
TY151095 Dl_151094;
TY151099 Dl_151098;
TY151103 Dl_151102;
TY151107 Dl_151106;
TY151111 Dl_151110;
TY151114 Dl_151113;
TY151118 Dl_151117;
TY151121 Dl_151120;
TY151125 Dl_151124;
TY151130 Dl_151129;
TY151134 Dl_151133;
TY151139 Dl_151138;
TY151144 Dl_151143;
TY151150 Dl_151149;
TY151154 Dl_151153;
TY151157 Dl_151156;
TY151160 Dl_151159;
TY151163 Dl_151162;
TY151166 Dl_151165;
TY151169 Dl_151168;
TY151173 Dl_151172;
TY151179 Dl_151178;
TY151185 Dl_151184;
TY151188 Dl_151187;
TY151191 Dl_151190;
TY151194 Dl_151193;
TY151197 Dl_151196;
TY151200 Dl_151199;
TY151204 Dl_151203;
TY151210 Dl_151209;
TY151214 Dl_151213;
TY151219 Dl_151218;
TY151225 Dl_151224;
TY151228 Dl_151227;
TY151232 Dl_151231;
TY151236 Dl_151235;
TY151240 Dl_151239;
TY151243 Dl_151242;
TY151246 Dl_151245;
TY151249 Dl_151248;
TY151252 Dl_151251;
TY151258 Dl_151257;
TY151261 Dl_151260;
TY151264 Dl_151263;
TY151267 Dl_151266;
TY151270 Dl_151269;
TY151273 Dl_151272;
TY151276 Dl_151275;
TY151282 Dl_151281;
TY151286 Dl_151285;
TY151289 Dl_151288;
TY151292 Dl_151291;
TY151295 Dl_151294;
TY151298 Dl_151297;
TY151302 Dl_151301;
TY151305 Dl_151304;
TY151308 Dl_151307;
TY151311 Dl_151310;
TY151317 Dl_151316;
TY151320 Dl_151319;
TY151323 Dl_151322;
TY151326 Dl_151325;
TY151329 Dl_151328;
TY151332 Dl_151331;
TY151335 Dl_151334;
TY151338 Dl_151337;
TY151342 Dl_151341;
TY151347 Dl_151346;
TY151351 Dl_151350;
TY151357 Dl_151356;
TY151361 Dl_151360;
TY151364 Dl_151363;
TY151367 Dl_151366;
TY151374 Dl_151373;
TY151379 Dl_151378;
TY151385 Dl_151384;
TY151390 Dl_151389;
TY151395 Dl_151394;
TY151402 Dl_151401;
TY151405 Dl_151404;
TY151408 Dl_151407;
TY151411 Dl_151410;
TY151414 Dl_151413;
TY151417 Dl_151416;
TY151420 Dl_151419;
TY151424 Dl_151423;
TY151429 Dl_151428;
TY151435 Dl_151434;
TY151438 Dl_151437;
TY151444 Dl_151443;
TY151452 Dl_151451;
TY151455 Dl_151454;
TY151458 Dl_151457;
TY151461 Dl_151460;
TY151464 Dl_151463;
TY151468 Dl_151467;
TY151474 Dl_151473;
TY151477 Dl_151476;
TY151484 Dl_151483;
TY151492 Dl_151491;
TY151496 Dl_151495;
TY151500 Dl_151499;
TY151504 Dl_151503;
TY151507 Dl_151506;
TY151511 Dl_151510;
TY151514 Dl_151513;
TY151522 Dl_151521;
TY151526 Dl_151525;
TY151536 Dl_151535;
TY151541 Dl_151540;
TY151549 Dl_151548;
TY151559 Dl_151558;
TY151568 Dl_151567;
TY151571 Dl_151570;
TY151576 Dl_151575;
TY151581 Dl_151580;
TY151585 Dl_151584;
TY151590 Dl_151589;
TY151595 Dl_151594;
TY151599 Dl_151598;
TY151602 Dl_151601;
TY151607 Dl_151606;
TY151613 Dl_151612;
TY151619 Dl_151618;
TY151624 Dl_151623;
TY151630 Dl_151629;
TY151635 Dl_151634;
TY151640 Dl_151639;
TY151646 Dl_151645;
TY151651 Dl_151650;
TY151655 Dl_151654;
TY151658 Dl_151657;
TY151661 Dl_151660;
TY151666 Dl_151665;
TY151672 Dl_151671;
TY151676 Dl_151675;
TY151679 Dl_151678;
extern TFrame* frameptr_18436_1689653243;
extern TNimType NTI151696; /* ref OutOfMemError */
extern TNimType NTI3450; /* OutOfMemError */
extern Gcheap49818 gch_49858_1689653243;
extern TNimType NTI14435; /* ref IOError */
extern TNimType NTI3428; /* IOError */
extern TNimType NTI90828; /* ref AssertionError */
extern TNimType NTI3444; /* AssertionError */
TY151735 Dl_151734;

static N_INLINE(NI, divInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		if (!(b0 == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = (NIM_BOOL)0;
		LOC7 = (a0 == ((NI) (-2147483647 -1)));
		if (!(LOC7)) goto LA8;
		LOC7 = (b0 == ((NI) -1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result0 = (NI)(a0 / b0);
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, modInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		if (!(b0 == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	result0 = (NI)(a0 % b0);
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU32)(a0) + (NU32)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_18436_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_18436_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_18436_1689653243;
	frameptr_18436_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_21201_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_18436_1689653243 = (*frameptr_18436_1689653243).prev;
}

N_NIMCALL(void, version_150719_77748642)(NI32* major0, NI32* minor0, NI32* micro0) {
	NI32 version0;
	NI32 T77748642_456;
	NI32 T77748642_457;
	NI32 T77748642_458;
	NI32 T77748642_459;
	NI32 T77748642_460;
	NI32 T77748642_461;
	NI32 T77748642_462;
	NI32 T77748642_463;
	nimfr("version", "cairo.nim")
	version0 = (NI32)0;
	nimln(715, "cairo.nim");
	version0 = Dl_150715();
	nimln(716, "cairo.nim");
	T77748642_456 = divInt(version0, ((NI32) 10000));
	(*major0) = (NI32)(T77748642_456);
	nimln(717, "cairo.nim");
	T77748642_457 = mulInt((*major0), ((NI32) 10000));
	T77748642_458 = modInt(version0, (NI32)(T77748642_457));
	T77748642_459 = divInt((NI32)(T77748642_458), ((NI32) 100));
	(*minor0) = (NI32)(T77748642_459);
	nimln(718, "cairo.nim");
	T77748642_460 = mulInt((*major0), ((NI32) 10000));
	T77748642_461 = mulInt((*minor0), ((NI32) 100));
	T77748642_462 = addInt((NI32)(T77748642_460), (NI32)(T77748642_461));
	T77748642_463 = modInt(version0, (NI32)(T77748642_462));
	(*micro0) = (NI32)(T77748642_463);
	popFrame();
}

static N_INLINE(Cell47305*, usrtocell_51440_1689653243)(void* usr0) {
	Cell47305* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell47305*)0;
	nimln(131, "gc.nim");
	result0 = ((Cell47305*) ((NI)((NU32)(((NI) (usr0))) - (NU32)(((NI)sizeof(Cell47305))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_52601_1689653243)(Cell47305* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(211, "gc.nim");
	addzct_51417_1689653243((&gch_49858_1689653243.zct), c0);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(271, "gc.nim");
	{
		Cell47305* c0;
		nimln(343, "system.nim");
		if (!!((src0 == NIM_NIL))) goto LA3;
		nimln(272, "gc.nim");
		c0 = usrtocell_51440_1689653243(src0);
		nimln(179, "gc.nim");
		(*c0).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(274, "gc.nim");
	{
		Cell47305* c0;
		nimln(343, "system.nim");
		if (!!(((*dest0) == NIM_NIL))) goto LA7;
		nimln(275, "gc.nim");
		c0 = usrtocell_51440_1689653243((*dest0));
		nimln(276, "gc.nim");
		{
			nimln(177, "gc.nim");
			(*c0).refcount -= ((NI) 8);
			nimln(178, "gc.nim");
			if (!((NU32)((*c0).refcount) < (NU32)(((NI) 8)))) goto LA11;
			nimln(277, "gc.nim");
			rtladdzct_52601_1689653243(c0);
		}
		LA11: ;
	}
	LA7: ;
	nimln(278, "gc.nim");
	(*dest0) = src0;
	popFrame();
}

N_NOINLINE(void, checkstatus_151688_77748642)(Tstatus150406 s0) {
	nimfr("checkStatus", "cairo.nim")
	nimln(723, "cairo.nim");
	switch (s0) {
	case ((Tstatus150406) 0):
	{
	}
	break;
	case ((Tstatus150406) 1):
	{
		Outofmemerror3450* e_151695_77748642;
		NCSTRING LOC3;
		e_151695_77748642 = (Outofmemerror3450*)0;
		nimln(2512, "system.nim");
		e_151695_77748642 = (Outofmemerror3450*) newObj((&NTI151696), sizeof(Outofmemerror3450));
		(*e_151695_77748642).Sup.Sup.Sup.m_type = (&NTI3450);
		nimln(2513, "system.nim");
		nimln(726, "cairo.nim");
		LOC3 = (NCSTRING)0;
		LOC3 = Dl_151307(s0);
		asgnRefNoCycle((void**) (&(*e_151695_77748642).Sup.Sup.message), cstrToNimstr(LOC3));
		raiseException((Exception*)e_151695_77748642, "OutOfMemError");
	}
	break;
	case ((Tstatus150406) 10):
	case ((Tstatus150406) 11):
	case ((Tstatus150406) 18):
	case ((Tstatus150406) 23):
	{
		Ioerror3428* e_151708_77748642;
		NCSTRING LOC5;
		e_151708_77748642 = (Ioerror3428*)0;
		nimln(2512, "system.nim");
		e_151708_77748642 = (Ioerror3428*) newObj((&NTI14435), sizeof(Ioerror3428));
		(*e_151708_77748642).Sup.Sup.Sup.m_type = (&NTI3428);
		nimln(2513, "system.nim");
		nimln(729, "cairo.nim");
		LOC5 = (NCSTRING)0;
		LOC5 = Dl_151307(s0);
		asgnRefNoCycle((void**) (&(*e_151708_77748642).Sup.Sup.message), cstrToNimstr(LOC5));
		raiseException((Exception*)e_151708_77748642, "IOError");
	}
	break;
	default:
	{
		Assertionerror3444* e_151721_77748642;
		NCSTRING LOC7;
		e_151721_77748642 = (Assertionerror3444*)0;
		nimln(2512, "system.nim");
		e_151721_77748642 = (Assertionerror3444*) newObj((&NTI90828), sizeof(Assertionerror3444));
		(*e_151721_77748642).Sup.Sup.m_type = (&NTI3444);
		nimln(2513, "system.nim");
		nimln(731, "cairo.nim");
		LOC7 = (NCSTRING)0;
		LOC7 = Dl_151307(s0);
		asgnRefNoCycle((void**) (&(*e_151721_77748642).Sup.message), cstrToNimstr(LOC7));
		raiseException((Exception*)e_151721_77748642, "AssertionError");
	}
	break;
	}
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, cairo_cairoInit000)(void) {
	nimfr("cairo", "cairo.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, cairo_cairoDatInit000)(void) {
if (!((T77748642_2 = nimLoadLibrary((NimStringDesc*) &T77748642_4))
||(T77748642_2 = nimLoadLibrary((NimStringDesc*) &T77748642_6))
)) nimLoadLibraryError((NimStringDesc*) &T77748642_7);
	Dl_150715 = (TY150716) nimGetProcAddr(T77748642_2, "cairo_version");
	Dl_150717 = (TY150718) nimGetProcAddr(T77748642_2, "cairo_version_string");
	Dl_150725 = (TY150726) nimGetProcAddr(T77748642_2, "cairo_create");
	Dl_150728 = (TY150729) nimGetProcAddr(T77748642_2, "cairo_reference");
	Dl_150731 = (TY150732) nimGetProcAddr(T77748642_2, "cairo_destroy");
	Dl_150734 = (TY150735) nimGetProcAddr(T77748642_2, "cairo_get_reference_count");
	Dl_150737 = (TY150738) nimGetProcAddr(T77748642_2, "cairo_get_user_data");
	Dl_150741 = (TY150742) nimGetProcAddr(T77748642_2, "cairo_set_user_data");
	Dl_150747 = (TY150748) nimGetProcAddr(T77748642_2, "cairo_save");
	Dl_150750 = (TY150751) nimGetProcAddr(T77748642_2, "cairo_restore");
	Dl_150753 = (TY150754) nimGetProcAddr(T77748642_2, "cairo_push_group");
	Dl_150756 = (TY150757) nimGetProcAddr(T77748642_2, "cairo_push_group_with_content");
	Dl_150760 = (TY150761) nimGetProcAddr(T77748642_2, "cairo_pop_group");
	Dl_150763 = (TY150764) nimGetProcAddr(T77748642_2, "cairo_pop_group_to_source");
	Dl_150766 = (TY150767) nimGetProcAddr(T77748642_2, "cairo_set_operator");
	Dl_150770 = (TY150771) nimGetProcAddr(T77748642_2, "cairo_set_source");
	Dl_150774 = (TY150775) nimGetProcAddr(T77748642_2, "cairo_set_source_rgb");
	Dl_150780 = (TY150781) nimGetProcAddr(T77748642_2, "cairo_set_source_rgba");
	Dl_150787 = (TY150788) nimGetProcAddr(T77748642_2, "cairo_set_source_surface");
	Dl_150793 = (TY150794) nimGetProcAddr(T77748642_2, "cairo_set_tolerance");
	Dl_150797 = (TY150798) nimGetProcAddr(T77748642_2, "cairo_set_antialias");
	Dl_150801 = (TY150802) nimGetProcAddr(T77748642_2, "cairo_set_fill_rule");
	Dl_150805 = (TY150806) nimGetProcAddr(T77748642_2, "cairo_set_line_width");
	Dl_150809 = (TY150810) nimGetProcAddr(T77748642_2, "cairo_set_line_cap");
	Dl_150813 = (TY150814) nimGetProcAddr(T77748642_2, "cairo_set_line_join");
	Dl_150817 = (TY150818) nimGetProcAddr(T77748642_2, "cairo_set_dash");
	Dl_150823 = (TY150824) nimGetProcAddr(T77748642_2, "cairo_set_miter_limit");
	Dl_150827 = (TY150828) nimGetProcAddr(T77748642_2, "cairo_translate");
	Dl_150832 = (TY150833) nimGetProcAddr(T77748642_2, "cairo_scale");
	Dl_150837 = (TY150838) nimGetProcAddr(T77748642_2, "cairo_rotate");
	Dl_150841 = (TY150842) nimGetProcAddr(T77748642_2, "cairo_transform");
	Dl_150845 = (TY150846) nimGetProcAddr(T77748642_2, "cairo_set_matrix");
	Dl_150849 = (TY150850) nimGetProcAddr(T77748642_2, "cairo_identity_matrix");
	Dl_150852 = (TY150853) nimGetProcAddr(T77748642_2, "cairo_user_to_device");
	Dl_150858 = (TY150859) nimGetProcAddr(T77748642_2, "cairo_user_to_device_distance");
	Dl_150864 = (TY150865) nimGetProcAddr(T77748642_2, "cairo_device_to_user");
	Dl_150870 = (TY150871) nimGetProcAddr(T77748642_2, "cairo_device_to_user_distance");
	Dl_150876 = (TY150877) nimGetProcAddr(T77748642_2, "cairo_new_path");
	Dl_150879 = (TY150880) nimGetProcAddr(T77748642_2, "cairo_move_to");
	Dl_150884 = (TY150885) nimGetProcAddr(T77748642_2, "cairo_new_sub_path");
	Dl_150887 = (TY150888) nimGetProcAddr(T77748642_2, "cairo_line_to");
	Dl_150892 = (TY150893) nimGetProcAddr(T77748642_2, "cairo_curve_to");
	Dl_150901 = (TY150902) nimGetProcAddr(T77748642_2, "cairo_arc");
	Dl_150909 = (TY150910) nimGetProcAddr(T77748642_2, "cairo_arc_negative");
	Dl_150917 = (TY150918) nimGetProcAddr(T77748642_2, "cairo_rel_move_to");
	Dl_150922 = (TY150923) nimGetProcAddr(T77748642_2, "cairo_rel_line_to");
	Dl_150927 = (TY150928) nimGetProcAddr(T77748642_2, "cairo_rel_curve_to");
	Dl_150936 = (TY150937) nimGetProcAddr(T77748642_2, "cairo_rectangle");
	Dl_150943 = (TY150944) nimGetProcAddr(T77748642_2, "cairo_close_path");
	Dl_150946 = (TY150947) nimGetProcAddr(T77748642_2, "cairo_paint");
	Dl_150949 = (TY150950) nimGetProcAddr(T77748642_2, "cairo_paint_with_alpha");
	Dl_150953 = (TY150954) nimGetProcAddr(T77748642_2, "cairo_mask");
	Dl_150957 = (TY150958) nimGetProcAddr(T77748642_2, "cairo_mask_surface");
	Dl_150963 = (TY150964) nimGetProcAddr(T77748642_2, "cairo_stroke");
	Dl_150966 = (TY150967) nimGetProcAddr(T77748642_2, "cairo_stroke_preserve");
	Dl_150969 = (TY150970) nimGetProcAddr(T77748642_2, "cairo_fill");
	Dl_150972 = (TY150973) nimGetProcAddr(T77748642_2, "cairo_fill_preserve");
	Dl_150975 = (TY150976) nimGetProcAddr(T77748642_2, "cairo_copy_page");
	Dl_150978 = (TY150979) nimGetProcAddr(T77748642_2, "cairo_show_page");
	Dl_150981 = (TY150982) nimGetProcAddr(T77748642_2, "cairo_in_stroke");
	Dl_150986 = (TY150987) nimGetProcAddr(T77748642_2, "cairo_in_fill");
	Dl_150991 = (TY150992) nimGetProcAddr(T77748642_2, "cairo_stroke_extents");
	Dl_150999 = (TY151000) nimGetProcAddr(T77748642_2, "cairo_fill_extents");
	Dl_151007 = (TY151008) nimGetProcAddr(T77748642_2, "cairo_reset_clip");
	Dl_151010 = (TY151011) nimGetProcAddr(T77748642_2, "cairo_clip");
	Dl_151013 = (TY151014) nimGetProcAddr(T77748642_2, "cairo_clip_preserve");
	Dl_151016 = (TY151017) nimGetProcAddr(T77748642_2, "cairo_clip_extents");
	Dl_151024 = (TY151025) nimGetProcAddr(T77748642_2, "cairo_copy_clip_rectangle_list");
	Dl_151027 = (TY151028) nimGetProcAddr(T77748642_2, "cairo_rectangle_list_destroy");
	Dl_151030 = (TY151031) nimGetProcAddr(T77748642_2, "cairo_font_options_create");
	Dl_151032 = (TY151033) nimGetProcAddr(T77748642_2, "cairo_font_options_copy");
	Dl_151035 = (TY151036) nimGetProcAddr(T77748642_2, "cairo_font_options_destroy");
	Dl_151038 = (TY151039) nimGetProcAddr(T77748642_2, "cairo_font_options_status");
	Dl_151041 = (TY151042) nimGetProcAddr(T77748642_2, "cairo_font_options_merge");
	Dl_151045 = (TY151046) nimGetProcAddr(T77748642_2, "cairo_font_options_equal");
	Dl_151049 = (TY151050) nimGetProcAddr(T77748642_2, "cairo_font_options_hash");
	Dl_151052 = (TY151053) nimGetProcAddr(T77748642_2, "cairo_font_options_set_antialias");
	Dl_151056 = (TY151057) nimGetProcAddr(T77748642_2, "cairo_font_options_get_antialias");
	Dl_151059 = (TY151060) nimGetProcAddr(T77748642_2, "cairo_font_options_set_subpixel_order");
	Dl_151063 = (TY151064) nimGetProcAddr(T77748642_2, "cairo_font_options_get_subpixel_order");
	Dl_151066 = (TY151067) nimGetProcAddr(T77748642_2, "cairo_font_options_set_hint_style");
	Dl_151070 = (TY151071) nimGetProcAddr(T77748642_2, "cairo_font_options_get_hint_style");
	Dl_151073 = (TY151074) nimGetProcAddr(T77748642_2, "cairo_font_options_set_hint_metrics");
	Dl_151077 = (TY151078) nimGetProcAddr(T77748642_2, "cairo_font_options_get_hint_metrics");
	Dl_151080 = (TY151081) nimGetProcAddr(T77748642_2, "cairo_select_font_face");
	Dl_151086 = (TY151087) nimGetProcAddr(T77748642_2, "cairo_set_font_size");
	Dl_151090 = (TY151091) nimGetProcAddr(T77748642_2, "cairo_set_font_matrix");
	Dl_151094 = (TY151095) nimGetProcAddr(T77748642_2, "cairo_get_font_matrix");
	Dl_151098 = (TY151099) nimGetProcAddr(T77748642_2, "cairo_set_font_options");
	Dl_151102 = (TY151103) nimGetProcAddr(T77748642_2, "cairo_get_font_options");
	Dl_151106 = (TY151107) nimGetProcAddr(T77748642_2, "cairo_set_font_face");
	Dl_151110 = (TY151111) nimGetProcAddr(T77748642_2, "cairo_get_font_face");
	Dl_151113 = (TY151114) nimGetProcAddr(T77748642_2, "cairo_set_scaled_font");
	Dl_151117 = (TY151118) nimGetProcAddr(T77748642_2, "cairo_get_scaled_font");
	Dl_151120 = (TY151121) nimGetProcAddr(T77748642_2, "cairo_show_text");
	Dl_151124 = (TY151125) nimGetProcAddr(T77748642_2, "cairo_show_glyphs");
	Dl_151129 = (TY151130) nimGetProcAddr(T77748642_2, "cairo_text_path");
	Dl_151133 = (TY151134) nimGetProcAddr(T77748642_2, "cairo_glyph_path");
	Dl_151138 = (TY151139) nimGetProcAddr(T77748642_2, "cairo_text_extents");
	Dl_151143 = (TY151144) nimGetProcAddr(T77748642_2, "cairo_glyph_extents");
	Dl_151149 = (TY151150) nimGetProcAddr(T77748642_2, "cairo_font_extents");
	Dl_151153 = (TY151154) nimGetProcAddr(T77748642_2, "cairo_font_face_reference");
	Dl_151156 = (TY151157) nimGetProcAddr(T77748642_2, "cairo_font_face_destroy");
	Dl_151159 = (TY151160) nimGetProcAddr(T77748642_2, "cairo_font_face_get_reference_count");
	Dl_151162 = (TY151163) nimGetProcAddr(T77748642_2, "cairo_font_face_status");
	Dl_151165 = (TY151166) nimGetProcAddr(T77748642_2, "cairo_font_face_get_type");
	Dl_151168 = (TY151169) nimGetProcAddr(T77748642_2, "cairo_font_face_get_user_data");
	Dl_151172 = (TY151173) nimGetProcAddr(T77748642_2, "cairo_font_face_set_user_data");
	Dl_151178 = (TY151179) nimGetProcAddr(T77748642_2, "cairo_scaled_font_create");
	Dl_151184 = (TY151185) nimGetProcAddr(T77748642_2, "cairo_scaled_font_reference");
	Dl_151187 = (TY151188) nimGetProcAddr(T77748642_2, "cairo_scaled_font_destroy");
	Dl_151190 = (TY151191) nimGetProcAddr(T77748642_2, "cairo_scaled_font_get_reference_count");
	Dl_151193 = (TY151194) nimGetProcAddr(T77748642_2, "cairo_scaled_font_status");
	Dl_151196 = (TY151197) nimGetProcAddr(T77748642_2, "cairo_scaled_font_get_type");
	Dl_151199 = (TY151200) nimGetProcAddr(T77748642_2, "cairo_scaled_font_get_user_data");
	Dl_151203 = (TY151204) nimGetProcAddr(T77748642_2, "cairo_scaled_font_set_user_data");
	Dl_151209 = (TY151210) nimGetProcAddr(T77748642_2, "cairo_scaled_font_extents");
	Dl_151213 = (TY151214) nimGetProcAddr(T77748642_2, "cairo_scaled_font_text_extents");
	Dl_151218 = (TY151219) nimGetProcAddr(T77748642_2, "cairo_scaled_font_glyph_extents");
	Dl_151224 = (TY151225) nimGetProcAddr(T77748642_2, "cairo_scaled_font_get_font_face");
	Dl_151227 = (TY151228) nimGetProcAddr(T77748642_2, "cairo_scaled_font_get_font_matrix");
	Dl_151231 = (TY151232) nimGetProcAddr(T77748642_2, "cairo_scaled_font_get_ctm");
	Dl_151235 = (TY151236) nimGetProcAddr(T77748642_2, "cairo_scaled_font_get_font_options");
	Dl_151239 = (TY151240) nimGetProcAddr(T77748642_2, "cairo_get_operator");
	Dl_151242 = (TY151243) nimGetProcAddr(T77748642_2, "cairo_get_source");
	Dl_151245 = (TY151246) nimGetProcAddr(T77748642_2, "cairo_get_tolerance");
	Dl_151248 = (TY151249) nimGetProcAddr(T77748642_2, "cairo_get_antialias");
	Dl_151251 = (TY151252) nimGetProcAddr(T77748642_2, "cairo_get_current_point");
	Dl_151257 = (TY151258) nimGetProcAddr(T77748642_2, "cairo_get_fill_rule");
	Dl_151260 = (TY151261) nimGetProcAddr(T77748642_2, "cairo_get_line_width");
	Dl_151263 = (TY151264) nimGetProcAddr(T77748642_2, "cairo_get_line_cap");
	Dl_151266 = (TY151267) nimGetProcAddr(T77748642_2, "cairo_get_line_join");
	Dl_151269 = (TY151270) nimGetProcAddr(T77748642_2, "cairo_get_miter_limit");
	Dl_151272 = (TY151273) nimGetProcAddr(T77748642_2, "cairo_get_dash_count");
	Dl_151275 = (TY151276) nimGetProcAddr(T77748642_2, "cairo_get_dash");
	Dl_151281 = (TY151282) nimGetProcAddr(T77748642_2, "cairo_get_matrix");
	Dl_151285 = (TY151286) nimGetProcAddr(T77748642_2, "cairo_get_target");
	Dl_151288 = (TY151289) nimGetProcAddr(T77748642_2, "cairo_get_group_target");
	Dl_151291 = (TY151292) nimGetProcAddr(T77748642_2, "cairo_copy_path");
	Dl_151294 = (TY151295) nimGetProcAddr(T77748642_2, "cairo_copy_path_flat");
	Dl_151297 = (TY151298) nimGetProcAddr(T77748642_2, "cairo_append_path");
	Dl_151301 = (TY151302) nimGetProcAddr(T77748642_2, "cairo_path_destroy");
	Dl_151304 = (TY151305) nimGetProcAddr(T77748642_2, "cairo_status");
	Dl_151307 = (TY151308) nimGetProcAddr(T77748642_2, "cairo_status_to_string");
	Dl_151310 = (TY151311) nimGetProcAddr(T77748642_2, "cairo_surface_create_similar");
	Dl_151316 = (TY151317) nimGetProcAddr(T77748642_2, "cairo_surface_reference");
	Dl_151319 = (TY151320) nimGetProcAddr(T77748642_2, "cairo_surface_finish");
	Dl_151322 = (TY151323) nimGetProcAddr(T77748642_2, "cairo_surface_destroy");
	Dl_151325 = (TY151326) nimGetProcAddr(T77748642_2, "cairo_surface_get_reference_count");
	Dl_151328 = (TY151329) nimGetProcAddr(T77748642_2, "cairo_surface_status");
	Dl_151331 = (TY151332) nimGetProcAddr(T77748642_2, "cairo_surface_get_type");
	Dl_151334 = (TY151335) nimGetProcAddr(T77748642_2, "cairo_surface_get_content");
	Dl_151337 = (TY151338) nimGetProcAddr(T77748642_2, "cairo_surface_write_to_png");
	Dl_151341 = (TY151342) nimGetProcAddr(T77748642_2, "cairo_surface_write_to_png_stream");
	Dl_151346 = (TY151347) nimGetProcAddr(T77748642_2, "cairo_surface_get_user_data");
	Dl_151350 = (TY151351) nimGetProcAddr(T77748642_2, "cairo_surface_set_user_data");
	Dl_151356 = (TY151357) nimGetProcAddr(T77748642_2, "cairo_surface_get_font_options");
	Dl_151360 = (TY151361) nimGetProcAddr(T77748642_2, "cairo_surface_flush");
	Dl_151363 = (TY151364) nimGetProcAddr(T77748642_2, "cairo_surface_mark_dirty");
	Dl_151366 = (TY151367) nimGetProcAddr(T77748642_2, "cairo_surface_mark_dirty_rectangle");
	Dl_151373 = (TY151374) nimGetProcAddr(T77748642_2, "cairo_surface_set_device_offset");
	Dl_151378 = (TY151379) nimGetProcAddr(T77748642_2, "cairo_surface_get_device_offset");
	Dl_151384 = (TY151385) nimGetProcAddr(T77748642_2, "cairo_surface_set_fallback_resolution");
	Dl_151389 = (TY151390) nimGetProcAddr(T77748642_2, "cairo_image_surface_create");
	Dl_151394 = (TY151395) nimGetProcAddr(T77748642_2, "cairo_image_surface_create_for_data");
	Dl_151401 = (TY151402) nimGetProcAddr(T77748642_2, "cairo_image_surface_get_data");
	Dl_151404 = (TY151405) nimGetProcAddr(T77748642_2, "cairo_image_surface_get_format");
	Dl_151407 = (TY151408) nimGetProcAddr(T77748642_2, "cairo_image_surface_get_width");
	Dl_151410 = (TY151411) nimGetProcAddr(T77748642_2, "cairo_image_surface_get_height");
	Dl_151413 = (TY151414) nimGetProcAddr(T77748642_2, "cairo_image_surface_get_stride");
	Dl_151416 = (TY151417) nimGetProcAddr(T77748642_2, "cairo_image_surface_create_from_png");
	Dl_151419 = (TY151420) nimGetProcAddr(T77748642_2, "cairo_image_surface_create_from_png_stream");
	Dl_151423 = (TY151424) nimGetProcAddr(T77748642_2, "cairo_pattern_create_rgb");
	Dl_151428 = (TY151429) nimGetProcAddr(T77748642_2, "cairo_pattern_create_rgba");
	Dl_151434 = (TY151435) nimGetProcAddr(T77748642_2, "cairo_pattern_create_for_surface");
	Dl_151437 = (TY151438) nimGetProcAddr(T77748642_2, "cairo_pattern_create_linear");
	Dl_151443 = (TY151444) nimGetProcAddr(T77748642_2, "cairo_pattern_create_radial");
	Dl_151451 = (TY151452) nimGetProcAddr(T77748642_2, "cairo_pattern_reference");
	Dl_151454 = (TY151455) nimGetProcAddr(T77748642_2, "cairo_pattern_destroy");
	Dl_151457 = (TY151458) nimGetProcAddr(T77748642_2, "cairo_pattern_get_reference_count");
	Dl_151460 = (TY151461) nimGetProcAddr(T77748642_2, "cairo_pattern_status");
	Dl_151463 = (TY151464) nimGetProcAddr(T77748642_2, "cairo_pattern_get_user_data");
	Dl_151467 = (TY151468) nimGetProcAddr(T77748642_2, "cairo_pattern_set_user_data");
	Dl_151473 = (TY151474) nimGetProcAddr(T77748642_2, "cairo_pattern_get_type");
	Dl_151476 = (TY151477) nimGetProcAddr(T77748642_2, "cairo_pattern_add_color_stop_rgb");
	Dl_151483 = (TY151484) nimGetProcAddr(T77748642_2, "cairo_pattern_add_color_stop_rgba");
	Dl_151491 = (TY151492) nimGetProcAddr(T77748642_2, "cairo_pattern_set_matrix");
	Dl_151495 = (TY151496) nimGetProcAddr(T77748642_2, "cairo_pattern_get_matrix");
	Dl_151499 = (TY151500) nimGetProcAddr(T77748642_2, "cairo_pattern_set_extend");
	Dl_151503 = (TY151504) nimGetProcAddr(T77748642_2, "cairo_pattern_get_extend");
	Dl_151506 = (TY151507) nimGetProcAddr(T77748642_2, "cairo_pattern_set_filter");
	Dl_151510 = (TY151511) nimGetProcAddr(T77748642_2, "cairo_pattern_get_filter");
	Dl_151513 = (TY151514) nimGetProcAddr(T77748642_2, "cairo_pattern_get_rgba");
	Dl_151521 = (TY151522) nimGetProcAddr(T77748642_2, "cairo_pattern_get_surface");
	Dl_151525 = (TY151526) nimGetProcAddr(T77748642_2, "cairo_pattern_get_color_stop_rgba");
	Dl_151535 = (TY151536) nimGetProcAddr(T77748642_2, "cairo_pattern_get_color_stop_count");
	Dl_151540 = (TY151541) nimGetProcAddr(T77748642_2, "cairo_pattern_get_linear_points");
	Dl_151548 = (TY151549) nimGetProcAddr(T77748642_2, "cairo_pattern_get_radial_circles");
	Dl_151558 = (TY151559) nimGetProcAddr(T77748642_2, "cairo_matrix_init");
	Dl_151567 = (TY151568) nimGetProcAddr(T77748642_2, "cairo_matrix_init_identity");
	Dl_151570 = (TY151571) nimGetProcAddr(T77748642_2, "cairo_matrix_init_translate");
	Dl_151575 = (TY151576) nimGetProcAddr(T77748642_2, "cairo_matrix_init_scale");
	Dl_151580 = (TY151581) nimGetProcAddr(T77748642_2, "cairo_matrix_init_rotate");
	Dl_151584 = (TY151585) nimGetProcAddr(T77748642_2, "cairo_matrix_translate");
	Dl_151589 = (TY151590) nimGetProcAddr(T77748642_2, "cairo_matrix_scale");
	Dl_151594 = (TY151595) nimGetProcAddr(T77748642_2, "cairo_matrix_rotate");
	Dl_151598 = (TY151599) nimGetProcAddr(T77748642_2, "cairo_matrix_invert");
	Dl_151601 = (TY151602) nimGetProcAddr(T77748642_2, "cairo_matrix_multiply");
	Dl_151606 = (TY151607) nimGetProcAddr(T77748642_2, "cairo_matrix_transform_distance");
	Dl_151612 = (TY151613) nimGetProcAddr(T77748642_2, "cairo_matrix_transform_point");
	Dl_151618 = (TY151619) nimGetProcAddr(T77748642_2, "cairo_pdf_surface_create");
	Dl_151623 = (TY151624) nimGetProcAddr(T77748642_2, "cairo_pdf_surface_create_for_stream");
	Dl_151629 = (TY151630) nimGetProcAddr(T77748642_2, "cairo_pdf_surface_set_size");
	Dl_151634 = (TY151635) nimGetProcAddr(T77748642_2, "cairo_ps_surface_create");
	Dl_151639 = (TY151640) nimGetProcAddr(T77748642_2, "cairo_ps_surface_create_for_stream");
	Dl_151645 = (TY151646) nimGetProcAddr(T77748642_2, "cairo_ps_surface_set_size");
	Dl_151650 = (TY151651) nimGetProcAddr(T77748642_2, "cairo_ps_surface_dsc_comment");
	Dl_151654 = (TY151655) nimGetProcAddr(T77748642_2, "cairo_ps_surface_dsc_begin_setup");
	Dl_151657 = (TY151658) nimGetProcAddr(T77748642_2, "cairo_ps_surface_dsc_begin_page_setup");
	Dl_151660 = (TY151661) nimGetProcAddr(T77748642_2, "cairo_svg_surface_create");
	Dl_151665 = (TY151666) nimGetProcAddr(T77748642_2, "cairo_svg_surface_create_for_stream");
	Dl_151671 = (TY151672) nimGetProcAddr(T77748642_2, "cairo_svg_surface_restrict_to_version");
	Dl_151675 = (TY151676) nimGetProcAddr(T77748642_2, "cairo_svg_version_to_string");
	Dl_151678 = (TY151679) nimGetProcAddr(T77748642_2, "cairo_debug_reset_static_data");
	Dl_151734 = (TY151735) nimGetProcAddr(T77748642_2, "cairo_surface_create_for_rectangle");
}

