/* Generated by Nim Compiler v0.14.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/john/code/Nim/lib -o /media/sf_D_DRIVE/Work/Code/nim-raytracer/src/src/nimcache/color.o /media/sf_D_DRIVE/Work/Code/nim-raytracer/src/src/nimcache/color.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <math.h>
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef NF32 TY151018[3];
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_NIMCALL(NF32, srgbtolinear_151003_2725535669)(NF32 v0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_21201_1689653243)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NF32, r_151024_140325102)(TY151018 v0);
N_NIMCALL(NF32, g_151038_140325102)(TY151018 v0);
N_NIMCALL(NF32, b_151052_140325102)(TY151018 v0);
N_NIMCALL(void, vec3_151066_140325102)(NF32 a0, NF32 b0, NF32 c0, TY151018 Result);
N_NIMCALL(void, srgbtolinear_151011_2725535669)(TY151018 c0, TY151018 Result);
N_NOINLINE(void, chckNil)(void* p0);
N_NIMCALL(void, genericReset)(void* dest0, TNimType* mt0);
N_NIMCALL(NF32, lineartosrgb_151085_2725535669)(NF32 v0);
N_NIMCALL(void, lineartosrgb_151096_2725535669)(TY151018 c0, TY151018 Result);
N_NIMCALL(NF32, gammatolinear_151140_2725535669)(NF32 v0, NF32 gamma0);
N_NIMCALL(NF32, lineartogamma_151145_2725535669)(NF32 v0, NF32 gamma0);
extern TFrame* frameptr_18436_1689653243;
extern TNimType NTI151018; /* array[0..2, float32] */

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_18436_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_18436_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_18436_1689653243;
	frameptr_18436_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_21201_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_18436_1689653243 = (*frameptr_18436_1689653243).prev;
}

N_NIMCALL(NF32, srgbtolinear_151003_2725535669)(NF32 v0) {
	NF32 result0;
	NF a0;
	NF LOC1;
	nimfr("sRGBToLinear", "color.nim")
	result0 = (NF32)0;
	nimln(6, "color.nim");
	a0 = 5.5000000000000000e-02;
	LOC1 = (NF)0;
	nimln(7, "color.nim");
	{
		if (!(((NF) (v0)) <= 4.0450000000000000e-02)) goto LA4;
		nimln(8, "color.nim");
		LOC1 = ((NF)(((NF) (v0))) / (NF)(1.2920000000000000e+01));
	}
	goto LA2;
	LA4: ;
	{
		nimln(10, "color.nim");
		LOC1 = pow(((NF)(((NF)(((NF) (v0))) + (NF)(a0))) / (NF)(((NF)(1.0000000000000000e+00) + (NF)(a0)))), 2.3999999999999999e+00);
	}
	LA2: ;
	result0 = ((NF32) (LOC1));
	popFrame();
	return result0;
}

N_NIMCALL(void, srgbtolinear_151011_2725535669)(TY151018 c0, TY151018 Result) {
	NF32 LOC1;
	NF32 LOC2;
	NF32 LOC3;
	NF32 LOC4;
	NF32 LOC5;
	NF32 LOC6;
	nimfr("sRGBToLinear", "color.nim")
	nimln(13, "color.nim");
	LOC1 = (NF32)0;
	LOC1 = r_151024_140325102(c0);
	LOC2 = (NF32)0;
	LOC2 = srgbtolinear_151003_2725535669(LOC1);
	nimln(14, "color.nim");
	LOC3 = (NF32)0;
	LOC3 = g_151038_140325102(c0);
	LOC4 = (NF32)0;
	LOC4 = srgbtolinear_151003_2725535669(LOC3);
	nimln(15, "color.nim");
	LOC5 = (NF32)0;
	LOC5 = b_151052_140325102(c0);
	LOC6 = (NF32)0;
	LOC6 = srgbtolinear_151003_2725535669(LOC5);
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI151018));
	vec3_151066_140325102(LOC2, LOC4, LOC6, Result);
	popFrame();
}

N_NIMCALL(NF32, lineartosrgb_151085_2725535669)(NF32 v0) {
	NF32 result0;
	NF a0;
	NF LOC1;
	nimfr("linearToSRGB", "color.nim")
	result0 = (NF32)0;
	nimln(18, "color.nim");
	a0 = 5.5000000000000000e-02;
	LOC1 = (NF)0;
	nimln(19, "color.nim");
	{
		if (!(((NF) (v0)) <= 3.1308000000000000e-03)) goto LA4;
		nimln(20, "color.nim");
		LOC1 = ((NF)(1.2920000000000000e+01) * (NF)(((NF) (v0))));
	}
	goto LA2;
	LA4: ;
	{
		NF32 LOC7;
		nimln(22, "color.nim");
		LOC7 = (NF32)0;
		LOC7 = powf(v0, 4.1666666666666669e-01);
		LOC1 = ((NF)(((NF)(((NF)(1.0000000000000000e+00) + (NF)(a0))) * (NF)(((NF) (LOC7))))) - (NF)(a0));
	}
	LA2: ;
	result0 = ((NF32) (LOC1));
	popFrame();
	return result0;
}

N_NIMCALL(void, lineartosrgb_151096_2725535669)(TY151018 c0, TY151018 Result) {
	NF32 LOC1;
	NF32 LOC2;
	NF32 LOC3;
	NF32 LOC4;
	NF32 LOC5;
	NF32 LOC6;
	nimfr("linearToSRGB", "color.nim")
	nimln(25, "color.nim");
	LOC1 = (NF32)0;
	LOC1 = r_151024_140325102(c0);
	LOC2 = (NF32)0;
	LOC2 = lineartosrgb_151085_2725535669(LOC1);
	nimln(26, "color.nim");
	LOC3 = (NF32)0;
	LOC3 = g_151038_140325102(c0);
	LOC4 = (NF32)0;
	LOC4 = lineartosrgb_151085_2725535669(LOC3);
	nimln(27, "color.nim");
	LOC5 = (NF32)0;
	LOC5 = b_151052_140325102(c0);
	LOC6 = (NF32)0;
	LOC6 = lineartosrgb_151085_2725535669(LOC5);
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI151018));
	vec3_151066_140325102(LOC2, LOC4, LOC6, Result);
	popFrame();
}

N_NIMCALL(NF32, gammatolinear_151140_2725535669)(NF32 v0, NF32 gamma0) {
	NF32 result0;
	nimfr("gammaToLinear", "color.nim")
	result0 = (NF32)0;
	nimln(30, "color.nim");
	result0 = powf(v0, gamma0);
	popFrame();
	return result0;
}

N_NIMCALL(NF32, lineartogamma_151145_2725535669)(NF32 v0, NF32 gamma0) {
	NF32 result0;
	nimfr("linearToGamma", "color.nim")
	result0 = (NF32)0;
	nimln(33, "color.nim");
	result0 = powf(v0, ((NF32)(1.0000000000000000e+00) / (NF32)(gamma0)));
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_colorInit000)(void) {
	nimfr("color", "color.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_colorDatInit000)(void) {
}

