/* Generated by Nim Compiler v0.14.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/john/code/Nim/lib -o /media/sf_D_DRIVE/Work/Code/nim-raytracer/src/src/nimcache/gamma.o /media/sf_D_DRIVE/Work/Code/nim-raytracer/src/src/nimcache/gamma.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <math.h>
typedef struct Framebufobj153002 Framebufobj153002;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell47305 Cell47305;
typedef struct Cellseq47321 Cellseq47321;
typedef struct Gcheap49818 Gcheap49818;
typedef struct Gcstack49816 Gcstack49816;
typedef struct Memregion29485 Memregion29485;
typedef struct Smallchunk29439 Smallchunk29439;
typedef struct Llchunk29479 Llchunk29479;
typedef struct Bigchunk29441 Bigchunk29441;
typedef struct Intset29414 Intset29414;
typedef struct Trunk29410 Trunk29410;
typedef struct Avlnode29483 Avlnode29483;
typedef struct Gcstat49814 Gcstat49814;
typedef struct Cellset47317 Cellset47317;
typedef struct Pagedesc47313 Pagedesc47313;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY153031 TY153031;
typedef struct Basechunk29437 Basechunk29437;
typedef struct Freecell29429 Freecell29429;
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, Globalmarkerproc55802) (void);
struct  Cell47305  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47321  {
NI len;
NI cap;
Cell47305** d;
};
typedef Smallchunk29439* TY29500[512];
typedef Trunk29410* Trunkbuckets29412[256];
struct  Intset29414  {
Trunkbuckets29412 data;
};
struct  Memregion29485  {
NI minlargeobj;
NI maxlargeobj;
TY29500 freesmallchunks;
Llchunk29479* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk29441* freechunkslist;
Intset29414 chunkstarts;
Avlnode29483* root;
Avlnode29483* deleted;
Avlnode29483* last;
Avlnode29483* freeavlnodes;
NIM_BOOL locked;
};
struct  Gcstat49814  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset47317  {
NI counter;
NI max;
Pagedesc47313* head;
Pagedesc47313** data;
};
struct  Gcheap49818  {
Gcstack49816* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47321 zct;
Cellseq47321 decstack;
Cellseq47321 tempstack;
NI recgclock;
Memregion29485 region;
Gcstat49814 stat;
Cellset47317 marked;
Cellseq47321 additionalroots;
};
typedef NF32 TY153463[3];
typedef NF32 TY155083[1];
typedef NF32 TY155137[2];
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Framebufobj153002  {
NI w;
NI h;
TY153031* data;
};
struct  Gcstack49816  {
Gcstack49816* prev;
Gcstack49816* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk29437  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk29439  {
  Basechunk29437 Sup;
Smallchunk29439* next;
Smallchunk29439* prev;
Freecell29429* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk29479  {
NI size;
NI acc;
Llchunk29479* next;
};
struct  Bigchunk29441  {
  Basechunk29437 Sup;
Bigchunk29441* next;
Bigchunk29441* prev;
NI align;
NF data;
};
typedef NI TY29418[16];
struct  Trunk29410  {
Trunk29410* next;
NI key;
TY29418 bits;
};
typedef Avlnode29483* TY29490[2];
struct  Avlnode29483  {
TY29490 link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc47313  {
Pagedesc47313* next;
NI key;
TY29418 bits;
};
struct  Freecell29429  {
Freecell29429* next;
NI zerofield;
};
struct TY153031 {
  TGenericSeq Sup;
  NF32 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d0, NI op0);
N_NIMCALL(void, T658669625_2)();
N_NIMCALL(void, nimRegisterGlobalMarker)(Globalmarkerproc55802 markerproc0);
N_NIMCALL(Framebufobj153002*, newframebuf_153010_623370228)(NI w0, NI h0);
static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0);
N_NOINLINE(void, raiseRangeError)(NI64 val0);
static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0);
static N_INLINE(Cell47305*, usrtocell_51440_1689653243)(void* usr0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_21201_1689653243)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_52601_1689653243)(Cell47305* c0);
N_NOINLINE(void, addzct_51417_1689653243)(Cellseq47321* s0, Cell47305* c0);
static N_INLINE(NF, HEX2F_90207_1689653243)(NI x0, NI y0);
N_NIMCALL(void, vec3_155024_140325102)(TY153463 a0, TY153463 Result);
N_NIMCALL(NF32, HEX5BHEX5D_155038_140325102)(TY153463 v0, NI ix0);
N_NIMCALL(void, vec3_155077_140325102)(TY155083 a0, NF32 b0, TY155083 c0, TY153463 Result);
N_NIMCALL(NF32, HEX5BHEX5D_155099_140325102)(TY155083 v0, NI ix0);
N_NIMCALL(void, vec3_155128_140325102)(TY155083 a0, TY155137 b0, TY153463 Result);
N_NIMCALL(NF32, HEX5BHEX5D_155158_140325102)(TY155137 v0, NI ix0);
N_NIMCALL(void, vec3_155187_140325102)(NF32 a0, TY155137 b0, TY153463 Result);
N_NIMCALL(void, vec3_155226_140325102)(NF32 a0, TY155083 b0, NF32 c0, TY153463 Result);
N_NIMCALL(void, vec3_155257_140325102)(NF32 a0, NF32 b0, TY155083 c0, TY153463 Result);
N_NIMCALL(void, vec3_155288_140325102)(TY155083 a0, TY155083 b0, NF32 c0, TY153463 Result);
N_NIMCALL(void, vec3_155342_140325102)(TY155083 a0, TY155083 b0, TY155083 c0, TY153463 Result);
N_NIMCALL(void, vec3_155395_140325102)(NF32 a0, TY153463 Result);
N_NIMCALL(void, vec3_155411_140325102)(TY155083 a0, NF32 b0, NF32 c0, TY153463 Result);
N_NIMCALL(void, vec3_155442_140325102)(TY155137 a0, NF32 b0, TY153463 Result);
N_NIMCALL(void, vec3_155481_140325102)(NF32 a0, TY155083 b0, TY155083 c0, TY153463 Result);
N_NIMCALL(void, vec3_155523_140325102)(TY155137 a0, TY155083 b0, TY153463 Result);
N_NOINLINE(void, chckNil)(void* p0);
N_NIMCALL(void, genericReset)(void* dest0, TNimType* mt0);
N_NIMCALL(void, vec3_154208_140325102)(NF32 a0, NF32 b0, NF32 c0, TY153463 Result);
N_NIMCALL(void, rect_154227_623370228)(Framebufobj153002** fb0, NI ox0, NI oy0, NI w0, NI h0, TY153463 color0);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a0, NI b0);
N_NIMCALL(NIM_BOOL, writeppm_154284_623370228)(Framebufobj153002* fb0, NimStringDesc* filename0, NI bits0, NIM_BOOL srgb0);
N_NIMCALL(NF32, lineartosrgb_151011_2725535669)(NF32 v0);
static N_INLINE(void, initStackBottomWith)(void* locals0);
N_NOINLINE(void, setStackBottom)(void* thestackbottom0);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_arrayUtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_arrayUtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_vectorInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_vectorDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_functionsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_functionsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_vecInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_vecDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_matrixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_matrixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_matInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_matDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_globalsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_globalsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_mat_transformInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_mat_transformDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_glmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_glmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_colorInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_colorDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_mathutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_mathutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_framebufInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_framebufDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, gammaInit000)(void);
NIM_EXTERNC N_NOINLINE(void, gammaDatInit000)(void);
STRING_LITERAL(T658669625_7, "gamma.ppm", 9);
STRING_LITERAL(T658669625_11, "gamma3.ppm", 10);
NI Width_155002_658669625;
NI Height_155004_658669625;
Framebufobj153002* fb_155005_658669625;
extern TNimType NTI153004; /* Framebuf */
extern TFrame* frameptr_18436_1689653243;
extern Gcheap49818 gch_49858_1689653243;
NI nrects_155006_658669625;
NF rectwidth_155007_658669625;
NF step_155008_658669625;
NI i_155019_658669625;
NF b_155020_658669625;
TY153463 c_155584_658669625;
extern TNimType NTI153463; /* array[0..2, float32] */
NI ox_155585_658669625;
NI i_155606_658669625;
NF b_155607_658669625;
TY153463 c_155793_658669625;
NI ox_155794_658669625;
NI i_155814_658669625;
TY153463 c_156000_658669625;
NI i_156019_658669625;
TY153463 c_156205_658669625;
NI x_156224_658669625;
NF x1_156226_658669625;
NF x2_156228_658669625;
NF xw_156229_658669625;
NF32 r_156230_658669625;
NF32 g_156231_658669625;
NF xf_156232_658669625;
TY153463 c_156418_658669625;
N_NIMCALL(void, T658669625_2)() {
	nimGCvisit((void*)fb_155005_658669625, 0);
}

static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (a0 <= i0);
		if (!(LOC3)) goto LA4;
		LOC3 = (i0 <= b0);
		LA4: ;
		if (!LOC3) goto LA5;
		result0 = i0;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i0)));
	}
	LA1: ;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_18436_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_18436_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_18436_1689653243;
	frameptr_18436_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_21201_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_18436_1689653243 = (*frameptr_18436_1689653243).prev;
}

static N_INLINE(Cell47305*, usrtocell_51440_1689653243)(void* usr0) {
	Cell47305* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell47305*)0;
	nimln(131, "gc.nim");
	result0 = ((Cell47305*) ((NI)((NU32)(((NI) (usr0))) - (NU32)(((NI)sizeof(Cell47305))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_52601_1689653243)(Cell47305* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(211, "gc.nim");
	addzct_51417_1689653243((&gch_49858_1689653243.zct), c0);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(271, "gc.nim");
	{
		Cell47305* c0;
		nimln(343, "system.nim");
		if (!!((src0 == NIM_NIL))) goto LA3;
		nimln(272, "gc.nim");
		c0 = usrtocell_51440_1689653243(src0);
		nimln(179, "gc.nim");
		(*c0).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(274, "gc.nim");
	{
		Cell47305* c0;
		nimln(343, "system.nim");
		if (!!(((*dest0) == NIM_NIL))) goto LA7;
		nimln(275, "gc.nim");
		c0 = usrtocell_51440_1689653243((*dest0));
		nimln(276, "gc.nim");
		{
			nimln(177, "gc.nim");
			(*c0).refcount -= ((NI) 8);
			nimln(178, "gc.nim");
			if (!((NU32)((*c0).refcount) < (NU32)(((NI) 8)))) goto LA11;
			nimln(277, "gc.nim");
			rtladdzct_52601_1689653243(c0);
		}
		LA11: ;
	}
	LA7: ;
	nimln(278, "gc.nim");
	(*dest0) = src0;
	popFrame();
}

static N_INLINE(NF, HEX2F_90207_1689653243)(NI x0, NI y0) {
	NF result0;
	nimfr("/", "system.nim")
	result0 = (NF)0;
	nimln(3176, "system.nim");
	result0 = ((NF)(((double) (x0))) / (NF)(((double) (y0))));
	popFrame();
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU32)(a0) + (NU32)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU32)(a0) - (NU32)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU32) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, initStackBottomWith)(void* locals0) {
	setStackBottom(locals0);
}
void PreMainInner() {
	systemInit000();
	stdlib_mathDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_sequtilsDatInit000();
	stdlib_macrosDatInit000();
	glm_arrayUtilsDatInit000();
	glm_vectorDatInit000();
	glm_functionsDatInit000();
	glm_vecDatInit000();
	glm_matrixDatInit000();
	glm_matDatInit000();
	glm_globalsDatInit000();
	glm_mat_transformDatInit000();
	glm_glmDatInit000();
	stdlib_endiansDatInit000();
	HEX00_colorDatInit000();
	HEX00_mathutilsDatInit000();
	HEX00_framebufDatInit000();
	gammaDatInit000();
	stdlib_mathInit000();
	stdlib_parseutilsInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_sequtilsInit000();
	stdlib_macrosInit000();
	glm_arrayUtilsInit000();
	glm_vectorInit000();
	glm_functionsInit000();
	glm_vecInit000();
	glm_matrixInit000();
	glm_matInit000();
	glm_globalsInit000();
	glm_mat_transformInit000();
	glm_glmInit000();
	stdlib_endiansInit000();
	HEX00_colorInit000();
	HEX00_mathutilsInit000();
	HEX00_framebufInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	gammaInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, gammaInit000)(void) {
	NIM_BOOL LOC12;
	NIM_BOOL LOC57;
	nimfr("gamma", "gamma.nim")
	nimln(9, "gamma.nim");
	Width_155002_658669625 = ((NI) 1024);
	nimln(10, "gamma.nim");
	Height_155004_658669625 = ((NI) 300);
nimRegisterGlobalMarker(T658669625_2);
	nimln(12, "gamma.nim");
	asgnRefNoCycle((void**) (&fb_155005_658669625), newframebuf_153010_623370228(((NI)chckRange(Width_155002_658669625, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Height_155004_658669625, ((NI) 0), ((NI) 2147483647)))));
	nimln(15, "gamma.nim");
	nrects_155006_658669625 = ((NI) 64);
	nimln(16, "gamma.nim");
	rectwidth_155007_658669625 = HEX2F_90207_1689653243(Width_155002_658669625, nrects_155006_658669625);
	nimln(17, "gamma.nim");
	step_155008_658669625 = ((NF)(1.0000000000000000e+00) / (NF)(((NF) (nrects_155006_658669625))));
	{
		NI i_155595_658669625;
		nimln(3615, "system.nim");
		i_155595_658669625 = ((NI) 0);
		{
			nimln(3616, "system.nim");
			while (1) {
				NI T658669625_3;
				if (!(i_155595_658669625 < nrects_155006_658669625)) goto LA3;
				nimln(3615, "system.nim");
				i_155019_658669625 = i_155595_658669625;
				b_155020_658669625 = 0;
				nimln(21, "gamma.nim");
				b_155020_658669625 = ((NF)(step_155008_658669625) * (NF)(((NF) (i_155019_658669625))));
				chckNil((void*)c_155584_658669625);
				genericReset((void*)c_155584_658669625, (&NTI153463));
				nimln(22, "gamma.nim");
				chckNil((void*)c_155584_658669625);
				genericReset((void*)c_155584_658669625, (&NTI153463));
				vec3_154208_140325102(((NF32) (b_155020_658669625)), ((NF32) (b_155020_658669625)), ((NF32) (b_155020_658669625)), c_155584_658669625);
				ox_155585_658669625 = 0;
				nimln(23, "gamma.nim");
				ox_155585_658669625 = ((NI) (((NF)(((NF) (i_155019_658669625))) * (NF)(rectwidth_155007_658669625))));
				nimln(25, "gamma.nim");
				rect_154227_623370228(&fb_155005_658669625, ox_155585_658669625, ((NI) 0), ((NI) (rectwidth_155007_658669625)), ((NI) 50), c_155584_658669625);
				nimln(3618, "system.nim");
				T658669625_3 = addInt(i_155595_658669625, ((NI) 1));
				i_155595_658669625 = (NI)(T658669625_3);
			} LA3: ;
		}
	}
	{
		NI i_155803_658669625;
		nimln(3615, "system.nim");
		i_155803_658669625 = ((NI) 0);
		{
			nimln(3616, "system.nim");
			while (1) {
				NI T658669625_4;
				if (!(i_155803_658669625 < nrects_155006_658669625)) goto LA6;
				nimln(3615, "system.nim");
				i_155606_658669625 = i_155803_658669625;
				b_155607_658669625 = 0;
				nimln(30, "gamma.nim");
				b_155607_658669625 = pow(((NF)(step_155008_658669625) * (NF)(((NF) (i_155606_658669625)))), 2.2000000000000002e+00);
				chckNil((void*)c_155793_658669625);
				genericReset((void*)c_155793_658669625, (&NTI153463));
				nimln(31, "gamma.nim");
				chckNil((void*)c_155793_658669625);
				genericReset((void*)c_155793_658669625, (&NTI153463));
				vec3_154208_140325102(((NF32) (b_155607_658669625)), ((NF32) (b_155607_658669625)), ((NF32) (b_155607_658669625)), c_155793_658669625);
				ox_155794_658669625 = 0;
				nimln(32, "gamma.nim");
				ox_155794_658669625 = ((NI) (((NF)(((NF) (i_155606_658669625))) * (NF)(rectwidth_155007_658669625))));
				nimln(34, "gamma.nim");
				rect_154227_623370228(&fb_155005_658669625, ox_155794_658669625, ((NI) 60), ((NI) (rectwidth_155007_658669625)), ((NI) 50), c_155793_658669625);
				nimln(3618, "system.nim");
				T658669625_4 = addInt(i_155803_658669625, ((NI) 1));
				i_155803_658669625 = (NI)(T658669625_4);
			} LA6: ;
		}
	}
	{
		NI i_156008_658669625;
		nimln(3615, "system.nim");
		i_156008_658669625 = ((NI) 0);
		{
			nimln(3616, "system.nim");
			while (1) {
				NF LOC10;
				NI T658669625_5;
				NF LOC11;
				NI T658669625_6;
				if (!(i_156008_658669625 < Width_155002_658669625)) goto LA9;
				nimln(3615, "system.nim");
				i_155814_658669625 = i_156008_658669625;
				chckNil((void*)c_156000_658669625);
				genericReset((void*)c_156000_658669625, (&NTI153463));
				nimln(39, "gamma.nim");
				LOC10 = (NF)0;
				LOC10 = HEX2F_90207_1689653243(Width_155002_658669625, i_155814_658669625);
				nimln(40, "gamma.nim");
				T658669625_5 = subInt(Width_155002_658669625, i_155814_658669625);
				LOC11 = (NF)0;
				LOC11 = HEX2F_90207_1689653243(Width_155002_658669625, (NI)(T658669625_5));
				chckNil((void*)c_156000_658669625);
				genericReset((void*)c_156000_658669625, (&NTI153463));
				vec3_154208_140325102(((NF32) (((NF)(1.0000000000000000e+00) / (NF)(LOC10)))), ((NF32) (((NF)(1.0000000000000000e+00) / (NF)(LOC11)))), 0.0, c_156000_658669625);
				nimln(43, "gamma.nim");
				rect_154227_623370228(&fb_155005_658669625, ((NI)chckRange(i_155814_658669625, ((NI) 0), ((NI) 2147483647))), ((NI) 110), ((NI) 1), ((NI) 50), c_156000_658669625);
				nimln(3618, "system.nim");
				T658669625_6 = addInt(i_156008_658669625, ((NI) 1));
				i_156008_658669625 = (NI)(T658669625_6);
			} LA9: ;
		}
	}
	nimln(45, "gamma.nim");
	LOC12 = (NIM_BOOL)0;
	LOC12 = writeppm_154284_623370228(fb_155005_658669625, ((NimStringDesc*) &T658669625_7), ((NI) 8), NIM_TRUE);
	nimln(49, "gamma.nim");
	asgnRefNoCycle((void**) (&fb_155005_658669625), newframebuf_153010_623370228(((NI)chckRange(Width_155002_658669625, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Height_155004_658669625, ((NI) 0), ((NI) 2147483647)))));
	{
		NI i_156213_658669625;
		nimln(3615, "system.nim");
		i_156213_658669625 = ((NI) 0);
		{
			nimln(3616, "system.nim");
			while (1) {
				NF LOC16;
				NI T658669625_8;
				NF LOC17;
				NI T658669625_9;
				if (!(i_156213_658669625 < Width_155002_658669625)) goto LA15;
				nimln(3615, "system.nim");
				i_156019_658669625 = i_156213_658669625;
				chckNil((void*)c_156205_658669625);
				genericReset((void*)c_156205_658669625, (&NTI153463));
				nimln(53, "gamma.nim");
				LOC16 = (NF)0;
				LOC16 = HEX2F_90207_1689653243(Width_155002_658669625, i_156019_658669625);
				nimln(54, "gamma.nim");
				T658669625_8 = subInt(Width_155002_658669625, i_156019_658669625);
				LOC17 = (NF)0;
				LOC17 = HEX2F_90207_1689653243(Width_155002_658669625, (NI)(T658669625_8));
				chckNil((void*)c_156205_658669625);
				genericReset((void*)c_156205_658669625, (&NTI153463));
				vec3_154208_140325102(((NF32) (((NF)(1.0000000000000000e+00) / (NF)(LOC16)))), ((NF32) (((NF)(1.0000000000000000e+00) / (NF)(LOC17)))), 0.0, c_156205_658669625);
				nimln(57, "gamma.nim");
				rect_154227_623370228(&fb_155005_658669625, ((NI)chckRange(i_156019_658669625, ((NI) 0), ((NI) 2147483647))), ((NI) 110), ((NI) 1), ((NI) 50), c_156205_658669625);
				nimln(3618, "system.nim");
				T658669625_9 = addInt(i_156213_658669625, ((NI) 1));
				i_156213_658669625 = (NI)(T658669625_9);
			} LA15: ;
		}
	}
	nimln(61, "gamma.nim");
	asgnRefNoCycle((void**) (&fb_155005_658669625), newframebuf_153010_623370228(((NI)chckRange(Width_155002_658669625, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Height_155004_658669625, ((NI) 0), ((NI) 2147483647)))));
	{
		NI i_156621_658669625;
		nimln(3615, "system.nim");
		i_156621_658669625 = ((NI) 0);
		{
			nimln(3616, "system.nim");
			while (1) {
				NF LOC21;
				NF LOC22;
				NF32 LOC55;
				NF32 LOC56;
				NI T658669625_10;
				if (!(i_156621_658669625 < Width_155002_658669625)) goto LA20;
				nimln(3615, "system.nim");
				x_156224_658669625 = i_156621_658669625;
				x1_156226_658669625 = 0;
				nimln(66, "gamma.nim");
				LOC21 = (NF)0;
				LOC21 = HEX2F_90207_1689653243(Width_155002_658669625, ((NI) 2));
				x1_156226_658669625 = ((NF)(LOC21) - (NF)(1.5000000000000000e+01));
				x2_156228_658669625 = 0;
				nimln(67, "gamma.nim");
				LOC22 = (NF)0;
				LOC22 = HEX2F_90207_1689653243(Width_155002_658669625, ((NI) 2));
				x2_156228_658669625 = ((NF)(LOC22) + (NF)(1.5000000000000000e+01));
				xw_156229_658669625 = 0;
				nimln(68, "gamma.nim");
				xw_156229_658669625 = ((NF)(x2_156228_658669625) - (NF)(x1_156226_658669625));
				r_156230_658669625 = 0;
				g_156231_658669625 = 0;
				xf_156232_658669625 = 0;
				nimln(72, "gamma.nim");
				xf_156232_658669625 = ((NF) (x_156224_658669625));
				nimln(73, "gamma.nim");
				{
					if (!(xf_156232_658669625 < x1_156226_658669625)) goto LA25;
					nimln(74, "gamma.nim");
					r_156230_658669625 = 0.0;
				}
				goto LA23;
				LA25: ;
				{
					nimln(75, "gamma.nim");
					if (!(xf_156232_658669625 < x2_156228_658669625)) goto LA28;
					nimln(76, "gamma.nim");
					r_156230_658669625 = ((NF32) (((NF)(1.0000000000000000e+00) / (NF)(((NF)(xw_156229_658669625) / (NF)(((NF)(xf_156232_658669625) - (NF)(x1_156226_658669625))))))));
				}
				goto LA23;
				LA28: ;
				{
					nimln(78, "gamma.nim");
					r_156230_658669625 = 1.0000000000000000e+00;
				}
				LA23: ;
				nimln(80, "gamma.nim");
				{
					if (!(xf_156232_658669625 < x1_156226_658669625)) goto LA33;
					nimln(81, "gamma.nim");
					g_156231_658669625 = 1.0000000000000000e+00;
				}
				goto LA31;
				LA33: ;
				{
					nimln(82, "gamma.nim");
					if (!(xf_156232_658669625 < x2_156228_658669625)) goto LA36;
					nimln(83, "gamma.nim");
					g_156231_658669625 = ((NF32) (((NF)(1.0000000000000000e+00) / (NF)(((NF)(xw_156229_658669625) / (NF)(((NF)(xw_156229_658669625) - (NF)(((NF)(xf_156232_658669625) - (NF)(x1_156226_658669625))))))))));
				}
				goto LA31;
				LA36: ;
				{
					nimln(85, "gamma.nim");
					g_156231_658669625 = 0.0;
				}
				LA31: ;
				chckNil((void*)c_156418_658669625);
				genericReset((void*)c_156418_658669625, (&NTI153463));
				nimln(87, "gamma.nim");
				chckNil((void*)c_156418_658669625);
				genericReset((void*)c_156418_658669625, (&NTI153463));
				vec3_154208_140325102(r_156230_658669625, g_156231_658669625, 0.0, c_156418_658669625);
				nimln(89, "gamma.nim");
				rect_154227_623370228(&fb_155005_658669625, ((NI)chckRange(x_156224_658669625, ((NI) 0), ((NI) 2147483647))), ((NI) 0), ((NI) 1), ((NI) 150), c_156418_658669625);
				nimln(92, "gamma.nim");
				{
					if (!(xf_156232_658669625 < x1_156226_658669625)) goto LA41;
					nimln(93, "gamma.nim");
					r_156230_658669625 = 0.0;
				}
				goto LA39;
				LA41: ;
				{
					nimln(94, "gamma.nim");
					if (!(xf_156232_658669625 < x2_156228_658669625)) goto LA44;
					nimln(95, "gamma.nim");
					r_156230_658669625 = ((NF32) (((NF)(1.0000000000000000e+00) / (NF)(((NF)(xw_156229_658669625) / (NF)(((NF)(xf_156232_658669625) - (NF)(x1_156226_658669625))))))));
				}
				goto LA39;
				LA44: ;
				{
					nimln(97, "gamma.nim");
					r_156230_658669625 = 1.0000000000000000e+00;
				}
				LA39: ;
				nimln(99, "gamma.nim");
				{
					if (!(xf_156232_658669625 < x1_156226_658669625)) goto LA49;
					nimln(100, "gamma.nim");
					g_156231_658669625 = 1.0000000000000000e+00;
				}
				goto LA47;
				LA49: ;
				{
					nimln(101, "gamma.nim");
					if (!(xf_156232_658669625 < x2_156228_658669625)) goto LA52;
					nimln(102, "gamma.nim");
					g_156231_658669625 = ((NF32) (((NF)(1.0000000000000000e+00) / (NF)(((NF)(xw_156229_658669625) / (NF)(((NF)(xw_156229_658669625) - (NF)(((NF)(xf_156232_658669625) - (NF)(x1_156226_658669625))))))))));
				}
				goto LA47;
				LA52: ;
				{
					nimln(104, "gamma.nim");
					g_156231_658669625 = 0.0;
				}
				LA47: ;
				nimln(106, "gamma.nim");
				LOC55 = (NF32)0;
				LOC55 = lineartosrgb_151011_2725535669(r_156230_658669625);
				LOC56 = (NF32)0;
				LOC56 = lineartosrgb_151011_2725535669(g_156231_658669625);
				chckNil((void*)c_156418_658669625);
				genericReset((void*)c_156418_658669625, (&NTI153463));
				vec3_154208_140325102(LOC55, LOC56, 0.0, c_156418_658669625);
				nimln(108, "gamma.nim");
				rect_154227_623370228(&fb_155005_658669625, ((NI)chckRange(x_156224_658669625, ((NI) 0), ((NI) 2147483647))), ((NI) 150), ((NI) 1), ((NI) 150), c_156418_658669625);
				nimln(3618, "system.nim");
				T658669625_10 = addInt(i_156621_658669625, ((NI) 1));
				i_156621_658669625 = (NI)(T658669625_10);
			} LA20: ;
		}
	}
	nimln(111, "gamma.nim");
	LOC57 = (NIM_BOOL)0;
	LOC57 = writeppm_154284_623370228(fb_155005_658669625, ((NimStringDesc*) &T658669625_11), ((NI) 8), NIM_FALSE);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, gammaDatInit000)(void) {
}

