/* Generated by Nim Compiler v0.14.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/john/code/Nim/lib -o /media/sf_D_DRIVE/Work/Code/nim-raytracer/src/src/nimcache/gammaramp.o /media/sf_D_DRIVE/Work/Code/nim-raytracer/src/src/nimcache/gammaramp.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <math.h>
typedef struct Framebufobj153002 Framebufobj153002;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell47305 Cell47305;
typedef struct Cellseq47321 Cellseq47321;
typedef struct Gcheap49818 Gcheap49818;
typedef struct Gcstack49816 Gcstack49816;
typedef struct Memregion29485 Memregion29485;
typedef struct Smallchunk29439 Smallchunk29439;
typedef struct Llchunk29479 Llchunk29479;
typedef struct Bigchunk29441 Bigchunk29441;
typedef struct Intset29414 Intset29414;
typedef struct Trunk29410 Trunk29410;
typedef struct Avlnode29483 Avlnode29483;
typedef struct Gcstat49814 Gcstat49814;
typedef struct Cellset47317 Cellset47317;
typedef struct Pagedesc47313 Pagedesc47313;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY153031 TY153031;
typedef struct Basechunk29437 Basechunk29437;
typedef struct Freecell29429 Freecell29429;
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, Globalmarkerproc55802) (void);
struct  Cell47305  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47321  {
NI len;
NI cap;
Cell47305** d;
};
typedef Smallchunk29439* TY29500[512];
typedef Trunk29410* Trunkbuckets29412[256];
struct  Intset29414  {
Trunkbuckets29412 data;
};
struct  Memregion29485  {
NI minlargeobj;
NI maxlargeobj;
TY29500 freesmallchunks;
Llchunk29479* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk29441* freechunkslist;
Intset29414 chunkstarts;
Avlnode29483* root;
Avlnode29483* deleted;
Avlnode29483* last;
Avlnode29483* freeavlnodes;
NIM_BOOL locked;
};
struct  Gcstat49814  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset47317  {
NI counter;
NI max;
Pagedesc47313* head;
Pagedesc47313** data;
};
struct  Gcheap49818  {
Gcstack49816* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47321 zct;
Cellseq47321 decstack;
Cellseq47321 tempstack;
NI recgclock;
Memregion29485 region;
Gcstat49814 stat;
Cellset47317 marked;
Cellseq47321 additionalroots;
};
typedef NF32 TY153463[3];
typedef NF32 TY155083[1];
typedef NF32 TY155137[2];
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Framebufobj153002  {
NI w;
NI h;
TY153031* data;
};
struct  Gcstack49816  {
Gcstack49816* prev;
Gcstack49816* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk29437  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk29439  {
  Basechunk29437 Sup;
Smallchunk29439* next;
Smallchunk29439* prev;
Freecell29429* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk29479  {
NI size;
NI acc;
Llchunk29479* next;
};
struct  Bigchunk29441  {
  Basechunk29437 Sup;
Bigchunk29441* next;
Bigchunk29441* prev;
NI align;
NF data;
};
typedef NI TY29418[16];
struct  Trunk29410  {
Trunk29410* next;
NI key;
TY29418 bits;
};
typedef Avlnode29483* TY29490[2];
struct  Avlnode29483  {
TY29490 link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc47313  {
Pagedesc47313* next;
NI key;
TY29418 bits;
};
struct  Freecell29429  {
Freecell29429* next;
NI zerofield;
};
struct TY153031 {
  TGenericSeq Sup;
  NF32 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d0, NI op0);
N_NIMCALL(void, T3701315435_2)();
N_NIMCALL(void, nimRegisterGlobalMarker)(Globalmarkerproc55802 markerproc0);
N_NIMCALL(Framebufobj153002*, newframebuf_153010_623370228)(NI w0, NI h0);
static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0);
N_NOINLINE(void, raiseRangeError)(NI64 val0);
static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0);
static N_INLINE(Cell47305*, usrtocell_51440_1689653243)(void* usr0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_21201_1689653243)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_52601_1689653243)(Cell47305* c0);
N_NOINLINE(void, addzct_51417_1689653243)(Cellseq47321* s0, Cell47305* c0);
static N_INLINE(NF, HEX2F_90207_1689653243)(NI x0, NI y0);
N_NIMCALL(void, vec3_155024_140325102)(TY153463 a0, TY153463 Result);
N_NIMCALL(NF32, HEX5BHEX5D_155038_140325102)(TY153463 v0, NI ix0);
N_NIMCALL(void, vec3_155077_140325102)(TY155083 a0, NF32 b0, TY155083 c0, TY153463 Result);
N_NIMCALL(NF32, HEX5BHEX5D_155099_140325102)(TY155083 v0, NI ix0);
N_NIMCALL(void, vec3_155128_140325102)(TY155083 a0, TY155137 b0, TY153463 Result);
N_NIMCALL(NF32, HEX5BHEX5D_155158_140325102)(TY155137 v0, NI ix0);
N_NIMCALL(void, vec3_155187_140325102)(NF32 a0, TY155137 b0, TY153463 Result);
N_NIMCALL(void, vec3_155226_140325102)(NF32 a0, TY155083 b0, NF32 c0, TY153463 Result);
N_NIMCALL(void, vec3_155257_140325102)(NF32 a0, NF32 b0, TY155083 c0, TY153463 Result);
N_NIMCALL(void, vec3_155288_140325102)(TY155083 a0, TY155083 b0, NF32 c0, TY153463 Result);
N_NIMCALL(void, vec3_155342_140325102)(TY155083 a0, TY155083 b0, TY155083 c0, TY153463 Result);
N_NIMCALL(void, vec3_155395_140325102)(NF32 a0, TY153463 Result);
N_NIMCALL(void, vec3_155411_140325102)(TY155083 a0, NF32 b0, NF32 c0, TY153463 Result);
N_NIMCALL(void, vec3_155442_140325102)(TY155137 a0, NF32 b0, TY153463 Result);
N_NIMCALL(void, vec3_155481_140325102)(NF32 a0, TY155083 b0, TY155083 c0, TY153463 Result);
N_NIMCALL(void, vec3_155523_140325102)(TY155137 a0, TY155083 b0, TY153463 Result);
N_NOINLINE(void, chckNil)(void* p0);
N_NIMCALL(void, genericReset)(void* dest0, TNimType* mt0);
N_NIMCALL(void, vec3_154208_140325102)(NF32 a0, NF32 b0, NF32 c0, TY153463 Result);
N_NIMCALL(void, rect_154227_623370228)(Framebufobj153002** fb0, NI ox0, NI oy0, NI w0, NI h0, TY153463 color0);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NIM_BOOL, writeppm_154284_623370228)(Framebufobj153002* fb0, NimStringDesc* filename0, NI bits0, NIM_BOOL srgb0);
N_NIMCALL(NF, round_108463_1009420244)(NF x0, NI places0);
static N_INLINE(void, initStackBottomWith)(void* locals0);
N_NOINLINE(void, setStackBottom)(void* thestackbottom0);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_arrayUtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_arrayUtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_vectorInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_vectorDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_functionsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_functionsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_vecInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_vecDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_matrixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_matrixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_matInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_matDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_globalsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_globalsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_mat_transformInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_mat_transformDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_glmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_glmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_colorInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_colorDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_mathutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_mathutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_framebufInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_framebufDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, gammarampInit000)(void);
NIM_EXTERNC N_NOINLINE(void, gammarampDatInit000)(void);
STRING_LITERAL(T3701315435_4, "out/linear-ramp32.ppm", 21);
STRING_LITERAL(T3701315435_6, "out/gamma-ramp32.ppm", 20);
STRING_LITERAL(T3701315435_8, "out/linear-ramp.ppm", 19);
STRING_LITERAL(T3701315435_10, "out/linear-ramp32-perceptual.ppm", 32);
NI Width_155002_3701315435;
NI Height_155004_3701315435;
Framebufobj153002* fb_155005_3701315435;
extern TNimType NTI153004; /* Framebuf */
extern TFrame* frameptr_18436_1689653243;
extern Gcheap49818 gch_49858_1689653243;
NI nrects_155006_3701315435;
NF rectwidth_155007_3701315435;
NF step_155008_3701315435;
NI i_155019_3701315435;
NF b_155020_3701315435;
TY153463 c_155584_3701315435;
extern TNimType NTI153463; /* array[0..2, float32] */
NI ox_155585_3701315435;
NI i_155605_3701315435;
NF b_155606_3701315435;
TY153463 c_155792_3701315435;
NI ox_155793_3701315435;
NI x_155813_3701315435;
NF b_155814_3701315435;
TY153463 c_156000_3701315435;
NI x_156016_3701315435;
NF b_156017_3701315435;
NF q_156029_3701315435;
TY153463 c_156215_3701315435;
N_NIMCALL(void, T3701315435_2)() {
	nimGCvisit((void*)fb_155005_3701315435, 0);
}

static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (a0 <= i0);
		if (!(LOC3)) goto LA4;
		LOC3 = (i0 <= b0);
		LA4: ;
		if (!LOC3) goto LA5;
		result0 = i0;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i0)));
	}
	LA1: ;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_18436_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_18436_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_18436_1689653243;
	frameptr_18436_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_21201_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_18436_1689653243 = (*frameptr_18436_1689653243).prev;
}

static N_INLINE(Cell47305*, usrtocell_51440_1689653243)(void* usr0) {
	Cell47305* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell47305*)0;
	nimln(131, "gc.nim");
	result0 = ((Cell47305*) ((NI)((NU32)(((NI) (usr0))) - (NU32)(((NI)sizeof(Cell47305))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_52601_1689653243)(Cell47305* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(211, "gc.nim");
	addzct_51417_1689653243((&gch_49858_1689653243.zct), c0);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(271, "gc.nim");
	{
		Cell47305* c0;
		nimln(343, "system.nim");
		if (!!((src0 == NIM_NIL))) goto LA3;
		nimln(272, "gc.nim");
		c0 = usrtocell_51440_1689653243(src0);
		nimln(179, "gc.nim");
		(*c0).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(274, "gc.nim");
	{
		Cell47305* c0;
		nimln(343, "system.nim");
		if (!!(((*dest0) == NIM_NIL))) goto LA7;
		nimln(275, "gc.nim");
		c0 = usrtocell_51440_1689653243((*dest0));
		nimln(276, "gc.nim");
		{
			nimln(177, "gc.nim");
			(*c0).refcount -= ((NI) 8);
			nimln(178, "gc.nim");
			if (!((NU32)((*c0).refcount) < (NU32)(((NI) 8)))) goto LA11;
			nimln(277, "gc.nim");
			rtladdzct_52601_1689653243(c0);
		}
		LA11: ;
	}
	LA7: ;
	nimln(278, "gc.nim");
	(*dest0) = src0;
	popFrame();
}

static N_INLINE(NF, HEX2F_90207_1689653243)(NI x0, NI y0) {
	NF result0;
	nimfr("/", "system.nim")
	result0 = (NF)0;
	nimln(3176, "system.nim");
	result0 = ((NF)(((double) (x0))) / (NF)(((double) (y0))));
	popFrame();
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU32)(a0) + (NU32)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, initStackBottomWith)(void* locals0) {
	setStackBottom(locals0);
}
void PreMainInner() {
	systemInit000();
	stdlib_mathDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_sequtilsDatInit000();
	stdlib_macrosDatInit000();
	glm_arrayUtilsDatInit000();
	glm_vectorDatInit000();
	glm_functionsDatInit000();
	glm_vecDatInit000();
	glm_matrixDatInit000();
	glm_matDatInit000();
	glm_globalsDatInit000();
	glm_mat_transformDatInit000();
	glm_glmDatInit000();
	stdlib_endiansDatInit000();
	HEX00_colorDatInit000();
	HEX00_mathutilsDatInit000();
	HEX00_framebufDatInit000();
	gammarampDatInit000();
	stdlib_mathInit000();
	stdlib_parseutilsInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_sequtilsInit000();
	stdlib_macrosInit000();
	glm_arrayUtilsInit000();
	glm_vectorInit000();
	glm_functionsInit000();
	glm_vecInit000();
	glm_matrixInit000();
	glm_matInit000();
	glm_globalsInit000();
	glm_mat_transformInit000();
	glm_glmInit000();
	stdlib_endiansInit000();
	HEX00_colorInit000();
	HEX00_mathutilsInit000();
	HEX00_framebufInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	gammarampInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, gammarampInit000)(void) {
	NIM_BOOL LOC4;
	NIM_BOOL LOC8;
	NIM_BOOL LOC13;
	NIM_BOOL LOC19;
	nimfr("gammaramp", "gammaramp.nim")
	nimln(9, "gammaramp.nim");
	Width_155002_3701315435 = ((NI) 1024);
	nimln(10, "gammaramp.nim");
	Height_155004_3701315435 = ((NI) 100);
nimRegisterGlobalMarker(T3701315435_2);
	nimln(14, "gammaramp.nim");
	asgnRefNoCycle((void**) (&fb_155005_3701315435), newframebuf_153010_623370228(((NI)chckRange(Width_155002_3701315435, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Height_155004_3701315435, ((NI) 0), ((NI) 2147483647)))));
	nimln(17, "gammaramp.nim");
	nrects_155006_3701315435 = ((NI) 32);
	nimln(18, "gammaramp.nim");
	rectwidth_155007_3701315435 = HEX2F_90207_1689653243(Width_155002_3701315435, nrects_155006_3701315435);
	nimln(19, "gammaramp.nim");
	step_155008_3701315435 = ((NF)(1.0000000000000000e+00) / (NF)(((NF) (nrects_155006_3701315435))));
	{
		NI i_155594_3701315435;
		nimln(3615, "system.nim");
		i_155594_3701315435 = ((NI) 0);
		{
			nimln(3616, "system.nim");
			while (1) {
				NI T3701315435_3;
				if (!(i_155594_3701315435 < nrects_155006_3701315435)) goto LA3;
				nimln(3615, "system.nim");
				i_155019_3701315435 = i_155594_3701315435;
				b_155020_3701315435 = 0;
				nimln(23, "gammaramp.nim");
				b_155020_3701315435 = ((NF)(step_155008_3701315435) * (NF)(((NF) (i_155019_3701315435))));
				chckNil((void*)c_155584_3701315435);
				genericReset((void*)c_155584_3701315435, (&NTI153463));
				nimln(24, "gammaramp.nim");
				chckNil((void*)c_155584_3701315435);
				genericReset((void*)c_155584_3701315435, (&NTI153463));
				vec3_154208_140325102(((NF32) (b_155020_3701315435)), ((NF32) (b_155020_3701315435)), ((NF32) (b_155020_3701315435)), c_155584_3701315435);
				ox_155585_3701315435 = 0;
				nimln(25, "gammaramp.nim");
				ox_155585_3701315435 = ((NI) (((NF)(((NF) (i_155019_3701315435))) * (NF)(rectwidth_155007_3701315435))));
				nimln(27, "gammaramp.nim");
				rect_154227_623370228(&fb_155005_3701315435, ox_155585_3701315435, ((NI) 0), ((NI) (rectwidth_155007_3701315435)), ((NI)chckRange(Height_155004_3701315435, ((NI) 0), ((NI) 2147483647))), c_155584_3701315435);
				nimln(3618, "system.nim");
				T3701315435_3 = addInt(i_155594_3701315435, ((NI) 1));
				i_155594_3701315435 = (NI)(T3701315435_3);
			} LA3: ;
		}
	}
	nimln(29, "gammaramp.nim");
	LOC4 = (NIM_BOOL)0;
	LOC4 = writeppm_154284_623370228(fb_155005_3701315435, ((NimStringDesc*) &T3701315435_4), ((NI) 8), NIM_TRUE);
	nimln(33, "gammaramp.nim");
	asgnRefNoCycle((void**) (&fb_155005_3701315435), newframebuf_153010_623370228(((NI)chckRange(Width_155002_3701315435, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Height_155004_3701315435, ((NI) 0), ((NI) 2147483647)))));
	{
		NI i_155802_3701315435;
		nimln(3615, "system.nim");
		i_155802_3701315435 = ((NI) 0);
		{
			nimln(3616, "system.nim");
			while (1) {
				NI T3701315435_5;
				if (!(i_155802_3701315435 < nrects_155006_3701315435)) goto LA7;
				nimln(3615, "system.nim");
				i_155605_3701315435 = i_155802_3701315435;
				b_155606_3701315435 = 0;
				nimln(37, "gammaramp.nim");
				b_155606_3701315435 = pow(((NF)(step_155008_3701315435) * (NF)(((NF) (i_155605_3701315435)))), 2.2000000000000002e+00);
				chckNil((void*)c_155792_3701315435);
				genericReset((void*)c_155792_3701315435, (&NTI153463));
				nimln(38, "gammaramp.nim");
				chckNil((void*)c_155792_3701315435);
				genericReset((void*)c_155792_3701315435, (&NTI153463));
				vec3_154208_140325102(((NF32) (b_155606_3701315435)), ((NF32) (b_155606_3701315435)), ((NF32) (b_155606_3701315435)), c_155792_3701315435);
				ox_155793_3701315435 = 0;
				nimln(39, "gammaramp.nim");
				ox_155793_3701315435 = ((NI) (((NF)(((NF) (i_155605_3701315435))) * (NF)(rectwidth_155007_3701315435))));
				nimln(41, "gammaramp.nim");
				rect_154227_623370228(&fb_155005_3701315435, ox_155793_3701315435, ((NI) 0), ((NI) (rectwidth_155007_3701315435)), ((NI)chckRange(Height_155004_3701315435, ((NI) 0), ((NI) 2147483647))), c_155792_3701315435);
				nimln(3618, "system.nim");
				T3701315435_5 = addInt(i_155802_3701315435, ((NI) 1));
				i_155802_3701315435 = (NI)(T3701315435_5);
			} LA7: ;
		}
	}
	nimln(43, "gammaramp.nim");
	LOC8 = (NIM_BOOL)0;
	LOC8 = writeppm_154284_623370228(fb_155005_3701315435, ((NimStringDesc*) &T3701315435_6), ((NI) 8), NIM_TRUE);
	nimln(47, "gammaramp.nim");
	asgnRefNoCycle((void**) (&fb_155005_3701315435), newframebuf_153010_623370228(((NI)chckRange(Width_155002_3701315435, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Height_155004_3701315435, ((NI) 0), ((NI) 2147483647)))));
	{
		NI i_156005_3701315435;
		nimln(3615, "system.nim");
		i_156005_3701315435 = ((NI) 0);
		{
			nimln(3616, "system.nim");
			while (1) {
				NF LOC12;
				NI T3701315435_7;
				if (!(i_156005_3701315435 < Width_155002_3701315435)) goto LA11;
				nimln(3615, "system.nim");
				x_155813_3701315435 = i_156005_3701315435;
				b_155814_3701315435 = 0;
				nimln(51, "gammaramp.nim");
				LOC12 = (NF)0;
				LOC12 = HEX2F_90207_1689653243(x_155813_3701315435, Width_155002_3701315435);
				b_155814_3701315435 = pow(LOC12, 2.2000000000000002e+00);
				chckNil((void*)c_156000_3701315435);
				genericReset((void*)c_156000_3701315435, (&NTI153463));
				nimln(52, "gammaramp.nim");
				chckNil((void*)c_156000_3701315435);
				genericReset((void*)c_156000_3701315435, (&NTI153463));
				vec3_154208_140325102(((NF32) (b_155814_3701315435)), ((NF32) (b_155814_3701315435)), ((NF32) (b_155814_3701315435)), c_156000_3701315435);
				nimln(54, "gammaramp.nim");
				rect_154227_623370228(&fb_155005_3701315435, ((NI)chckRange(x_155813_3701315435, ((NI) 0), ((NI) 2147483647))), ((NI) 0), ((NI) 1), ((NI)chckRange(Height_155004_3701315435, ((NI) 0), ((NI) 2147483647))), c_156000_3701315435);
				nimln(3618, "system.nim");
				T3701315435_7 = addInt(i_156005_3701315435, ((NI) 1));
				i_156005_3701315435 = (NI)(T3701315435_7);
			} LA11: ;
		}
	}
	nimln(56, "gammaramp.nim");
	LOC13 = (NIM_BOOL)0;
	LOC13 = writeppm_154284_623370228(fb_155005_3701315435, ((NimStringDesc*) &T3701315435_8), ((NI) 8), NIM_TRUE);
	nimln(60, "gammaramp.nim");
	asgnRefNoCycle((void**) (&fb_155005_3701315435), newframebuf_153010_623370228(((NI)chckRange(Width_155002_3701315435, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Height_155004_3701315435, ((NI) 0), ((NI) 2147483647)))));
	{
		NI i_156222_3701315435;
		nimln(3615, "system.nim");
		i_156222_3701315435 = ((NI) 0);
		{
			nimln(3616, "system.nim");
			while (1) {
				NF LOC17;
				NF LOC18;
				NI T3701315435_9;
				if (!(i_156222_3701315435 < Width_155002_3701315435)) goto LA16;
				nimln(3615, "system.nim");
				x_156016_3701315435 = i_156222_3701315435;
				b_156017_3701315435 = 0;
				nimln(64, "gammaramp.nim");
				LOC17 = (NF)0;
				LOC17 = HEX2F_90207_1689653243(x_156016_3701315435, Width_155002_3701315435);
				b_156017_3701315435 = pow(LOC17, 2.2000000000000002e+00);
				q_156029_3701315435 = 0;
				nimln(65, "gammaramp.nim");
				LOC18 = (NF)0;
				LOC18 = round_108463_1009420244(((NF)(b_156017_3701315435) * (NF)(3.2000000000000000e+01)), ((NI) 0));
				q_156029_3701315435 = ((NF)(LOC18) / (NF)(3.2000000000000000e+01));
				chckNil((void*)c_156215_3701315435);
				genericReset((void*)c_156215_3701315435, (&NTI153463));
				nimln(66, "gammaramp.nim");
				chckNil((void*)c_156215_3701315435);
				genericReset((void*)c_156215_3701315435, (&NTI153463));
				vec3_154208_140325102(((NF32) (q_156029_3701315435)), ((NF32) (q_156029_3701315435)), ((NF32) (q_156029_3701315435)), c_156215_3701315435);
				nimln(68, "gammaramp.nim");
				rect_154227_623370228(&fb_155005_3701315435, ((NI)chckRange(x_156016_3701315435, ((NI) 0), ((NI) 2147483647))), ((NI) 0), ((NI) 1), ((NI)chckRange(Height_155004_3701315435, ((NI) 0), ((NI) 2147483647))), c_156215_3701315435);
				nimln(3618, "system.nim");
				T3701315435_9 = addInt(i_156222_3701315435, ((NI) 1));
				i_156222_3701315435 = (NI)(T3701315435_9);
			} LA16: ;
		}
	}
	nimln(70, "gammaramp.nim");
	LOC19 = (NIM_BOOL)0;
	LOC19 = writeppm_154284_623370228(fb_155005_3701315435, ((NimStringDesc*) &T3701315435_10), ((NI) 8), NIM_TRUE);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, gammarampDatInit000)(void) {
}

