/* Generated by Nim Compiler v0.14.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/john/code/Nim/lib -o /media/sf_D_DRIVE/Work/Code/nim-raytracer/src/src/nimcache/gammatransfer.o /media/sf_D_DRIVE/Work/Code/nim-raytracer/src/src/nimcache/gammatransfer.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <math.h>
#include <string.h>
typedef struct Tsurface150492 Tsurface150492;
typedef struct Tcontext150490 Tcontext150490;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY152027 TY152027;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef N_CDECL_PTR(Tsurface150492*, TY151661) (NCSTRING filename0, NF widthinpoints0, NF heightinpoints0);
typedef N_CDECL_PTR(Tcontext150490*, TY150726) (Tsurface150492* target0);
typedef N_CDECL_PTR(void, TY150833) (Tcontext150490* cr0, NF sx0, NF sy0);
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 Tfontslant150418;
typedef NU8 Tfontweight150420;
typedef N_CDECL_PTR(void, TY151081) (Tcontext150490* cr0, NCSTRING family0, Tfontslant150418 slant0, Tfontweight150420 weight0);
typedef NF TY129056[3];
typedef N_CDECL_PTR(void, TY150748) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void, TY150806) (Tcontext150490* cr0, NF width0);
typedef N_CDECL_PTR(void, TY150775) (Tcontext150490* cr0, NF red0, NF green0, NF blue0);
typedef N_CDECL_PTR(void, TY150880) (Tcontext150490* cr0, NF x0, NF y0);
typedef N_CDECL_PTR(void, TY150888) (Tcontext150490* cr0, NF x0, NF y0);
typedef N_CDECL_PTR(void, TY150964) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void, TY150818) (Tcontext150490* cr0, NF* dashes0, NI dashes0Len0, NF offset0);
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CDECL_PTR(void, TY151087) (Tcontext150490* cr0, NF size0);
typedef N_CDECL_PTR(void, TY151121) (Tcontext150490* cr0, NCSTRING utf80);
typedef N_CDECL_PTR(void, TY150838) (Tcontext150490* cr0, NF angle0);
typedef N_CDECL_PTR(void, TY150751) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void, TY150828) (Tcontext150490* cr0, NF tx0, NF ty0);
typedef N_CDECL_PTR(void, TY150732) (Tcontext150490* cr0);
typedef N_CDECL_PTR(void, TY151323) (Tsurface150492* surface0);
struct  Tsurface150492  {
char dummy;
};
struct  Tcontext150490  {
char dummy;
};
struct TY152027 {
  TGenericSeq Sup;
  NF data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, setfont_152006_4122035716)(Tcontext150490* ctx0, NimStringDesc* fontname0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_21201_1689653243)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NF, degtorad_152072_1009420244)(NF d0);
N_NIMCALL(void, drawchart_152010_4122035716)(NF gamma0, TY129056 color0);
N_NIMCALL(void*, newSeq)(TNimType* typ0, NI len0);
N_NIMCALL(NF, HEX5BHEX5D_140781_140325102)(TY129056 v0, NI ix0);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, vec3_130965_140325102)(NF a0, NF b0, NF c0, TY129056 Result);
static N_INLINE(void, initStackBottomWith)(void* locals0);
N_NOINLINE(void, setStackBottom)(void* thestackbottom0);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_arrayUtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_arrayUtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_vectorInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_vectorDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_functionsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_functionsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_vecInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_vecDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_matrixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_matrixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_matInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_matDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_globalsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_globalsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_mat_transformInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_mat_transformDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_glmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_glmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, cairo_cairoInit000)(void);
NIM_EXTERNC N_NOINLINE(void, cairo_cairoDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, gammatransferInit000)(void);
NIM_EXTERNC N_NOINLINE(void, gammatransferDatInit000)(void);
NIM_CONST struct {
  TGenericSeq Sup;
  NF data[2];
} T4122035716_3 = {{2, 2}, {2.9999999999999999e-02,
2.0000000000000000e-02}};
NIM_CONST TY152027* T4122035716_2 = ((TY152027*)&T4122035716_3);
STRING_LITERAL(T4122035716_5, "Source Sans Pro", 15);
STRING_LITERAL(T4122035716_6, "Verdana", 7);
NF Width_152001_4122035716;
NF Height_152002_4122035716;
Tsurface150492* surface_152003_4122035716;
extern TY151661 Dl_151660;
Tcontext150490* ctx_152004_4122035716;
extern TY150726 Dl_150725;
NF scalefactor_152005_4122035716;
extern TY150833 Dl_150832;
extern TY151081 Dl_151080;
extern TFrame* frameptr_18436_1689653243;
extern TY150748 Dl_150747;
extern TY150806 Dl_150805;
extern TY150775 Dl_150774;
extern TY150880 Dl_150879;
extern TY150888 Dl_150887;
extern TY150964 Dl_150963;
extern TY150818 Dl_150817;
extern TNimType NTI152027; /* seq[float64] */
extern TY151087 Dl_151086;
extern TY151121 Dl_151120;
extern TY150838 Dl_150837;
extern TY150751 Dl_150750;
NF labelyoffs_152159_4122035716;
extern TY150828 Dl_150827;
extern TY150732 Dl_150731;
extern TY151323 Dl_151322;

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_18436_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_18436_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_18436_1689653243;
	frameptr_18436_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_21201_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_18436_1689653243 = (*frameptr_18436_1689653243).prev;
}

N_NIMCALL(void, setfont_152006_4122035716)(Tcontext150490* ctx0, NimStringDesc* fontname0) {
	nimfr("setFont", "gammatransfer.nim")
	nimln(24, "gammatransfer.nim");
	Dl_151080(ctx0, fontname0->data, ((Tfontslant150418) 0), ((Tfontweight150420) 0));
	popFrame();
}

static N_INLINE(NF, degtorad_152072_1009420244)(NF d0) {
	NF result0;
	result0 = (NF)0;
	result0 = ((NF)(d0) * (NF)(1.7453292519943295e-02));
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU32)(a0) + (NU32)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(void, drawchart_152010_4122035716)(NF gamma0, TY129056 color0) {
	TY152027* LOC1;
	NF d10;
	NF d20;
	NF LOC2;
	NI steps0;
	NF LOC3;
	NF LOC4;
	NF LOC5;
	nimfr("drawChart", "gammatransfer.nim")
	nimln(27, "gammatransfer.nim");
	Dl_150747(ctx_152004_4122035716);
	nimln(30, "gammatransfer.nim");
	Dl_150805(ctx_152004_4122035716, 6.0000000000000001e-03);
	nimln(33, "gammatransfer.nim");
	Dl_150774(ctx_152004_4122035716, 6.9999999999999996e-01, 6.9999999999999996e-01, 6.9999999999999996e-01);
	nimln(34, "gammatransfer.nim");
	Dl_150879(ctx_152004_4122035716, 0.0, 1.0000000000000000e+00);
	nimln(35, "gammatransfer.nim");
	Dl_150887(ctx_152004_4122035716, 1.0000000000000000e+00, 0.0);
	nimln(36, "gammatransfer.nim");
	Dl_150963(ctx_152004_4122035716);
	nimln(39, "gammatransfer.nim");
	Dl_150817(ctx_152004_4122035716, T4122035716_2->data, T4122035716_2->Sup.len, 0.0);
	nimln(41, "gammatransfer.nim");
	Dl_150879(ctx_152004_4122035716, 1.0000000000000000e+00, 1.0000000000000000e+00);
	nimln(42, "gammatransfer.nim");
	Dl_150887(ctx_152004_4122035716, 1.0000000000000000e+00, 0.0);
	nimln(43, "gammatransfer.nim");
	Dl_150963(ctx_152004_4122035716);
	nimln(45, "gammatransfer.nim");
	Dl_150879(ctx_152004_4122035716, 0.0, 0.0);
	nimln(46, "gammatransfer.nim");
	Dl_150887(ctx_152004_4122035716, 1.0000000000000000e+00, 0.0);
	nimln(47, "gammatransfer.nim");
	Dl_150963(ctx_152004_4122035716);
	nimln(50, "gammatransfer.nim");
	Dl_150774(ctx_152004_4122035716, 4.0000000000000002e-01, 4.0000000000000002e-01, 4.0000000000000002e-01);
	nimln(51, "gammatransfer.nim");
	Dl_150805(ctx_152004_4122035716, 1.0000000000000000e-02);
	nimln(52, "gammatransfer.nim");
	LOC1 = (TY152027*)0;
	LOC1 = (TY152027*) newSeq((&NTI152027), 0);
	Dl_150817(ctx_152004_4122035716, LOC1->data, LOC1->Sup.len, 0.0);
	nimln(55, "gammatransfer.nim");
	d10 = 5.9999999999999998e-02;
	nimln(56, "gammatransfer.nim");
	d20 = 2.9999999999999999e-02;
	nimln(58, "gammatransfer.nim");
	Dl_150879(ctx_152004_4122035716, 0.0, ((NF)(1.0000000000000000e+00) + (NF)(d10)));
	nimln(59, "gammatransfer.nim");
	Dl_150887(ctx_152004_4122035716, 0.0, ((NF)(0.0) - (NF)(d20)));
	nimln(60, "gammatransfer.nim");
	Dl_150963(ctx_152004_4122035716);
	nimln(63, "gammatransfer.nim");
	Dl_150879(ctx_152004_4122035716, ((NF)(0.0) - (NF)(d10)), 1.0000000000000000e+00);
	nimln(64, "gammatransfer.nim");
	Dl_150887(ctx_152004_4122035716, ((NF)(1.0000000000000000e+00) + (NF)(d20)), 1.0000000000000000e+00);
	nimln(65, "gammatransfer.nim");
	Dl_150963(ctx_152004_4122035716);
	nimln(68, "gammatransfer.nim");
	Dl_151080(ctx_152004_4122035716, "Source Sans Pro", ((Tfontslant150418) 0), ((Tfontweight150420) 0));
	nimln(69, "gammatransfer.nim");
	Dl_151086(ctx_152004_4122035716, 1.1000000000000000e-01);
	nimln(71, "gammatransfer.nim");
	Dl_150879(ctx_152004_4122035716, -1.0000000000000001e-01, 1.1100000000000001e+00);
	nimln(72, "gammatransfer.nim");
	Dl_151120(ctx_152004_4122035716, "0");
	nimln(74, "gammatransfer.nim");
	Dl_150879(ctx_152004_4122035716, 9.6999999999999997e-01, 1.1100000000000001e+00);
	nimln(75, "gammatransfer.nim");
	Dl_151120(ctx_152004_4122035716, "1");
	nimln(77, "gammatransfer.nim");
	Dl_150879(ctx_152004_4122035716, -1.0000000000000001e-01, 5.9999999999999998e-02);
	nimln(78, "gammatransfer.nim");
	Dl_151120(ctx_152004_4122035716, "1");
	nimln(80, "gammatransfer.nim");
	Dl_151086(ctx_152004_4122035716, 8.9999999999999997e-02);
	nimln(81, "gammatransfer.nim");
	Dl_150879(ctx_152004_4122035716, 4.6999999999999997e-01, 1.1100000000000001e+00);
	nimln(82, "gammatransfer.nim");
	Dl_151120(ctx_152004_4122035716, "in");
	nimln(84, "gammatransfer.nim");
	Dl_150747(ctx_152004_4122035716);
	nimln(85, "gammatransfer.nim");
	Dl_151086(ctx_152004_4122035716, 8.9999999999999997e-02);
	nimln(86, "gammatransfer.nim");
	Dl_150879(ctx_152004_4122035716, -4.4999999999999998e-02, 5.8000000000000007e-01);
	nimln(87, "gammatransfer.nim");
	LOC2 = (NF)0;
	LOC2 = degtorad_152072_1009420244(-9.0000000000000000e+01);
	Dl_150837(ctx_152004_4122035716, LOC2);
	nimln(88, "gammatransfer.nim");
	Dl_151120(ctx_152004_4122035716, "out");
	nimln(89, "gammatransfer.nim");
	Dl_150750(ctx_152004_4122035716);
	nimln(93, "gammatransfer.nim");
	steps0 = ((NI) 500);
	nimln(95, "gammatransfer.nim");
	LOC3 = (NF)0;
	LOC3 = HEX5BHEX5D_140781_140325102(color0, ((NI) 0));
	LOC4 = (NF)0;
	LOC4 = HEX5BHEX5D_140781_140325102(color0, ((NI) 1));
	LOC5 = (NF)0;
	LOC5 = HEX5BHEX5D_140781_140325102(color0, ((NI) 2));
	Dl_150774(ctx_152004_4122035716, LOC3, LOC4, LOC5);
	nimln(96, "gammatransfer.nim");
	Dl_150805(ctx_152004_4122035716, 1.6000000000000000e-02);
	nimln(97, "gammatransfer.nim");
	Dl_150879(ctx_152004_4122035716, 0.0, 1.0000000000000000e+00);
	{
		NI i_152120_4122035716;
		NI res_152155_4122035716;
		i_152120_4122035716 = (NI)0;
		nimln(1873, "system.nim");
		res_152155_4122035716 = ((NI) 0);
		{
			nimln(1874, "system.nim");
			while (1) {
				NF x0;
				NF y0;
				NF LOC9;
				NI T4122035716_4;
				if (!(res_152155_4122035716 <= steps0)) goto LA8;
				nimln(1875, "system.nim");
				i_152120_4122035716 = res_152155_4122035716;
				nimln(101, "gammatransfer.nim");
				x0 = ((NF)(((NF) (i_152120_4122035716))) / (NF)(((NF) (steps0))));
				nimln(102, "gammatransfer.nim");
				LOC9 = (NF)0;
				LOC9 = pow(x0, gamma0);
				y0 = ((NF)(1.0000000000000000e+00) - (NF)(LOC9));
				nimln(103, "gammatransfer.nim");
				Dl_150887(ctx_152004_4122035716, x0, y0);
				nimln(1894, "system.nim");
				T4122035716_4 = addInt(res_152155_4122035716, ((NI) 1));
				res_152155_4122035716 = (NI)(T4122035716_4);
			} LA8: ;
		}
	}
	nimln(105, "gammatransfer.nim");
	Dl_150963(ctx_152004_4122035716);
	nimln(106, "gammatransfer.nim");
	Dl_150750(ctx_152004_4122035716);
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals0) {
	setStackBottom(locals0);
}
void PreMainInner() {
	systemInit000();
	stdlib_mathDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_sequtilsDatInit000();
	stdlib_macrosDatInit000();
	glm_arrayUtilsDatInit000();
	glm_vectorDatInit000();
	glm_functionsDatInit000();
	glm_vecDatInit000();
	glm_matrixDatInit000();
	glm_matDatInit000();
	glm_globalsDatInit000();
	glm_mat_transformDatInit000();
	glm_glmDatInit000();
	cairo_cairoDatInit000();
	gammatransferDatInit000();
	stdlib_mathInit000();
	stdlib_parseutilsInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_sequtilsInit000();
	stdlib_macrosInit000();
	glm_arrayUtilsInit000();
	glm_vectorInit000();
	glm_functionsInit000();
	glm_vecInit000();
	glm_matrixInit000();
	glm_matInit000();
	glm_globalsInit000();
	glm_mat_transformInit000();
	glm_glmInit000();
	cairo_cairoInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	gammatransferInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, gammatransferInit000)(void) {
	TY129056 LOC1;
	TY129056 LOC2;
	TY129056 LOC3;
	nimfr("gammatransfer", "gammatransfer.nim")
	nimln(6, "gammatransfer.nim");
	Width_152001_4122035716 = 4.9000000000000000e+02;
	nimln(7, "gammatransfer.nim");
	Height_152002_4122035716 = 2.0000000000000000e+02;
	nimln(10, "gammatransfer.nim");
	surface_152003_4122035716 = Dl_151660("out/gammatransfer.svg", Width_152001_4122035716, Height_152002_4122035716);
	nimln(11, "gammatransfer.nim");
	ctx_152004_4122035716 = Dl_150725(surface_152003_4122035716);
	nimln(19, "gammatransfer.nim");
	scalefactor_152005_4122035716 = 1.2000000000000000e+02;
	nimln(21, "gammatransfer.nim");
	Dl_150832(ctx_152004_4122035716, scalefactor_152005_4122035716, scalefactor_152005_4122035716);
	nimln(111, "gammatransfer.nim");
	labelyoffs_152159_4122035716 = 3.4999999999999998e-01;
	nimln(113, "gammatransfer.nim");
	Dl_150827(ctx_152004_4122035716, 1.7000000000000001e-01, 2.0999999999999999e-01);
	nimln(114, "gammatransfer.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	vec3_130965_140325102(1.0000000000000000e+00, 2.0000000000000001e-01, 5.0000000000000000e-01, LOC1);
	drawchart_152010_4122035716(4.5454545454545453e-01, LOC1);
	nimln(116, "gammatransfer.nim");
	setfont_152006_4122035716(ctx_152004_4122035716, ((NimStringDesc*) &T4122035716_5));
	nimln(117, "gammatransfer.nim");
	Dl_151086(ctx_152004_4122035716, 1.1000000000000000e-01);
	nimln(118, "gammatransfer.nim");
	Dl_150774(ctx_152004_4122035716, 2.9999999999999999e-01, 2.9999999999999999e-01, 2.9999999999999999e-01);
	nimln(119, "gammatransfer.nim");
	Dl_150879(ctx_152004_4122035716, 2.7000000000000002e-01, ((NF)(1.0000000000000000e+00) + (NF)(labelyoffs_152159_4122035716)));
	nimln(120, "gammatransfer.nim");
	Dl_151120(ctx_152004_4122035716, "a)  ");
	nimln(122, "gammatransfer.nim");
	setfont_152006_4122035716(ctx_152004_4122035716, ((NimStringDesc*) &T4122035716_6));
	nimln(123, "gammatransfer.nim");
	Dl_151120(ctx_152004_4122035716, "\316\263");
	nimln(124, "gammatransfer.nim");
	setfont_152006_4122035716(ctx_152004_4122035716, ((NimStringDesc*) &T4122035716_5));
	nimln(125, "gammatransfer.nim");
	Dl_151120(ctx_152004_4122035716, "=1/2.2");
	nimln(129, "gammatransfer.nim");
	Dl_150827(ctx_152004_4122035716, 1.3999999999999999e+00, 0.0);
	nimln(130, "gammatransfer.nim");
	memset((void*)LOC2, 0, sizeof(LOC2));
	vec3_130965_140325102(2.9999999999999999e-01, 6.9999999999999996e-01, 9.0000000000000002e-01, LOC2);
	drawchart_152010_4122035716(1.0000000000000000e+00, LOC2);
	nimln(132, "gammatransfer.nim");
	setfont_152006_4122035716(ctx_152004_4122035716, ((NimStringDesc*) &T4122035716_5));
	nimln(133, "gammatransfer.nim");
	Dl_150879(ctx_152004_4122035716, 3.1000000000000000e-01, ((NF)(1.0000000000000000e+00) + (NF)(labelyoffs_152159_4122035716)));
	nimln(134, "gammatransfer.nim");
	Dl_151120(ctx_152004_4122035716, "b)  ");
	nimln(136, "gammatransfer.nim");
	setfont_152006_4122035716(ctx_152004_4122035716, ((NimStringDesc*) &T4122035716_6));
	nimln(137, "gammatransfer.nim");
	Dl_151120(ctx_152004_4122035716, "\316\263");
	nimln(138, "gammatransfer.nim");
	setfont_152006_4122035716(ctx_152004_4122035716, ((NimStringDesc*) &T4122035716_5));
	nimln(139, "gammatransfer.nim");
	Dl_151120(ctx_152004_4122035716, "=1.0");
	nimln(143, "gammatransfer.nim");
	Dl_150827(ctx_152004_4122035716, 1.3999999999999999e+00, 0.0);
	nimln(144, "gammatransfer.nim");
	memset((void*)LOC3, 0, sizeof(LOC3));
	vec3_130965_140325102(0.0, 5.9999999999999998e-01, 5.0000000000000000e-01, LOC3);
	drawchart_152010_4122035716(2.2000000000000002e+00, LOC3);
	nimln(146, "gammatransfer.nim");
	setfont_152006_4122035716(ctx_152004_4122035716, ((NimStringDesc*) &T4122035716_5));
	nimln(147, "gammatransfer.nim");
	Dl_150879(ctx_152004_4122035716, 2.9999999999999999e-01, ((NF)(1.0000000000000000e+00) + (NF)(labelyoffs_152159_4122035716)));
	nimln(148, "gammatransfer.nim");
	Dl_151120(ctx_152004_4122035716, "c)  ");
	nimln(150, "gammatransfer.nim");
	setfont_152006_4122035716(ctx_152004_4122035716, ((NimStringDesc*) &T4122035716_6));
	nimln(151, "gammatransfer.nim");
	Dl_151120(ctx_152004_4122035716, "\316\263");
	nimln(152, "gammatransfer.nim");
	setfont_152006_4122035716(ctx_152004_4122035716, ((NimStringDesc*) &T4122035716_5));
	nimln(153, "gammatransfer.nim");
	Dl_151120(ctx_152004_4122035716, "=2.2");
	nimln(155, "gammatransfer.nim");
	Dl_150731(ctx_152004_4122035716);
	nimln(156, "gammatransfer.nim");
	Dl_151322(surface_152003_4122035716);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, gammatransferDatInit000)(void) {
}

