/* Generated by Nim Compiler v0.14.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/john/code/Nim/lib -o /media/sf_D_DRIVE/Work/Code/nim-raytracer/src/src/nimcache/glm_vec.o /media/sf_D_DRIVE/Work/Code/nim-raytracer/src/src/nimcache/glm_vec.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#include <math.h>
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY145737 TY145737;
typedef struct TY146121 TY146121;
typedef struct TY146176 TY146176;
typedef NF TY128923[1];
typedef NF TY128962[2];
typedef NF TY129056[3];
typedef NF TY129288[4];
typedef NF TY130980[3];
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef struct {
N_NIMCALL_PTR(NF, ClPrc) (NF a_131302_2824150814, NF b_131304_2824150814, void* ClEnv);
void* ClEnv;
} TY131300;
typedef N_CLOSURE_PTR(NF, T140325102_6) (NF a_131285_2824150814, NF b_131287_2824150814, void* ClEnv);
typedef NimStringDesc* TY131215[3];
typedef NI TY131466[3];
typedef NF TY134957[2];
typedef NF TY135118[4];
typedef N_CLOSURE_PTR(NF, T140325102_9) (NF a_145821_2824150814, NF b_145823_2824150814, void* ClEnv);
struct  TY145737  {
NI HEX3Astate;
NF s145670;
};
typedef struct {
N_NIMCALL_PTR(NF, ClPrc) (NF a_145700_2824150814, void* ClEnv);
void* ClEnv;
} TY145698;
struct  TY146121  {
NI HEX3Astate;
NF s146054;
};
struct  TY146176  {
NI HEX3Astate;
NF s146136;
};
typedef N_CLOSURE_PTR(NF, T140325102_16) (NF a_147884_2824150814, NF b_147886_2824150814, void* ClEnv);
typedef NF32 TY151018[3];
typedef NF32 TY151081[3];
typedef NF32 TY155127[1];
typedef NF32 TY155181[2];
typedef struct {
N_NIMCALL_PTR(NF32, ClPrc) (NF32 a_155705_2824150814, NF32 b_155707_2824150814, void* ClEnv);
void* ClEnv;
} TY155703;
typedef N_CLOSURE_PTR(NF32, T140325102_17) (NF32 a_155688_2824150814, NF32 b_155690_2824150814, void* ClEnv);
N_NIMCALL(void, vec1_128916_140325102)(TY128923 Result);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_21201_1689653243)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, vec2_128955_140325102)(TY128962 Result);
N_NIMCALL(void, vec3_129049_140325102)(TY129056 Result);
N_NIMCALL(void, vec4_129281_140325102)(TY129288 Result);
N_NIMCALL(void, vec3_130965_140325102)(NF a0, NF b0, NF c0, TY129056 Result);
N_NIMCALL(void, cross_130999_140325102)(TY129056 x0, TY129056 y0, TY129056 Result);
N_NIMCALL(NF, y_131011_140325102)(TY129056 v0);
N_NIMCALL(NF, z_131025_140325102)(TY129056 v0);
N_NIMCALL(NF, x_131063_140325102)(TY129056 v0);
N_NOINLINE(void, chckNil)(void* p0);
N_NIMCALL(void, genericReset)(void* dest0, TNimType* mt0);
N_NIMCALL(NimStringDesc*, HEX24_131139_140325102)(TY129056 v0);
N_NIMCALL(NimStringDesc*, HEX24_131154_2824150814)(NF* a0, NI a0Len0);
N_NIMCALL(NF, dot_131225_140325102)(TY129056 a0, TY129056 b0);
N_NIMCALL(NF, sum_131431_1009420244)(NF* x0, NI x0Len0);
N_NIMCALL(void, HEX2A_131242_140325102)(TY129056 v0, TY129056 u0, TY129056 Result);
N_NIMCALL(void, zipwith_131289_2824150814)(TY129056 a0, TY129056 b0, TY131300 op0, TY129056 Result);
N_NIMCALL(NF, HEX3Aanonymous_131278_140325102)(NF a0, NF b0);
N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr0, NimStringDesc** a0, NI a0Len0);
N_NIMCALL(NimStringDesc*, nimFloatToStr)(NF f0);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void, zipwith_145825_2824150814)(TY129288 a0, TY129288 b0, TY131300 op0, TY129288 Result);
N_NIMCALL(NF, HEX3Aanonymous_145814_140325102)(NF a0, NF b0);
N_NIMCALL(void, T140325102_11)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ0, NI size0);
N_NIMCALL(void, map_145691_2824150814)(TY129288 a0, TY145698 f0, TY129288 Result);
N_CLOSURE(NF, HEX3Aanonymous_145683_140325102)(NF a0, void* ClEnv);
N_NIMCALL(void, HEX2F_146047_140325102)(TY129056 a0, NF s0, TY129056 Result);
N_NIMCALL(void, T140325102_13)(void* p, NI op);
N_NIMCALL(void, map_146075_2824150814)(TY129056 a0, TY145698 f0, TY129056 Result);
N_CLOSURE(NF, HEX3Aanonymous_146067_140325102)(NF a0, void* ClEnv);
N_NIMCALL(NF, length_146001_140325102)(TY129056 vec0);
N_NIMCALL(NF, length2_146009_140325102)(TY129056 vec0);
N_NIMCALL(void, T140325102_15)(void* p, NI op);
N_CLOSURE(NF, HEX3Aanonymous_146152_140325102)(NF a0, void* ClEnv);
N_NIMCALL(NF, HEX3Aanonymous_147877_140325102)(NF a0, NF b0);
N_NIMCALL(NF32, HEX5BHEX5D_155082_140325102)(TY151018 v0, NI ix0);
N_NIMCALL(NF32, HEX5BHEX5D_155143_140325102)(TY155127 v0, NI ix0);
N_NIMCALL(NF32, HEX5BHEX5D_155202_140325102)(TY155181 v0, NI ix0);
N_NIMCALL(void, zipwith_155692_2824150814)(TY151018 a0, TY151018 b0, TY155703 op0, TY151018 Result);
N_NIMCALL(NF32, HEX3Aanonymous_155681_140325102)(NF32 a0, NF32 b0);
NIM_CONST TY128923 T140325102_2 = {0.0}
;
NIM_CONST TY128962 T140325102_3 = {0.0,
0.0}
;
NIM_CONST TY129056 T140325102_4 = {0.0,
0.0,
0.0}
;
NIM_CONST TY129288 T140325102_5 = {0.0,
0.0,
0.0,
0.0}
;
STRING_LITERAL(T140325102_7, "Should not use this as main module: $# [$#, $#]", 47);
NIM_CONST TY131466 T140325102_8 = {((NI) 1),
((NI) 2),
((NI) 3)}
;
extern TFrame* frameptr_18436_1689653243;
extern TNimType NTI124; /* float */
TNimType NTI129056; /* array[0..2, float] */
TY129056 v_130984_140325102;
TY129056 u_130997_140325102;
TY129056 c_131136_140325102;
TY131466 arr_131468_140325102;
TNimType NTI128962; /* array[0..1, float] */
TNimType NTI129288; /* array[0..3, float] */
TNimType NTI145737; /* object */
extern TNimType NTI101021; /* range -1..0(int) */
TNimType NTI145736; /* ref object */
TNimType NTI146121; /* object */
TNimType NTI146120; /* ref object */
TNimType NTI146176; /* object */
TNimType NTI146175; /* ref object */
extern TNimType NTI126; /* float32 */
TNimType NTI151018; /* array[0..2, float32] */

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_18436_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_18436_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_18436_1689653243;
	frameptr_18436_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_21201_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_18436_1689653243 = (*frameptr_18436_1689653243).prev;
}

N_NIMCALL(void, vec1_128916_140325102)(TY128923 Result) {
	nimfr("vec1", "macros.nim")
	nimln(333, "macros.nim");
	memcpy((void*)Result, (NIM_CONST void*)T140325102_2, sizeof(TY128923));
	popFrame();
}

N_NIMCALL(void, vec2_128955_140325102)(TY128962 Result) {
	nimfr("vec2", "macros.nim")
	nimln(333, "macros.nim");
	memcpy((void*)Result, (NIM_CONST void*)T140325102_3, sizeof(TY128962));
	popFrame();
}

N_NIMCALL(void, vec3_129049_140325102)(TY129056 Result) {
	nimfr("vec3", "macros.nim")
	nimln(333, "macros.nim");
	memcpy((void*)Result, (NIM_CONST void*)T140325102_4, sizeof(TY129056));
	popFrame();
}

N_NIMCALL(void, vec4_129281_140325102)(TY129288 Result) {
	nimfr("vec4", "macros.nim")
	nimln(333, "macros.nim");
	memcpy((void*)Result, (NIM_CONST void*)T140325102_5, sizeof(TY129288));
	popFrame();
}

N_NIMCALL(void, vec3_130965_140325102)(NF a0, NF b0, NF c0, TY129056 Result) {
	TY130980 LOC1;
	nimfr("vec3", "macros.nim")
	nimln(333, "macros.nim");
	LOC1[0] = a0;
	LOC1[1] = b0;
	LOC1[2] = c0;
	memcpy((void*)Result, (NIM_CONST void*)(*(TY129056*) (LOC1)), sizeof(TY129056));
	popFrame();
}

N_NIMCALL(NF, y_131011_140325102)(TY129056 v0) {
	NF result0;
	nimfr("y", "macros.nim")
	result0 = (NF)0;
	nimln(333, "macros.nim");
	result0 = v0[(((NI) 1))- 0];
	popFrame();
	return result0;
}

N_NIMCALL(NF, z_131025_140325102)(TY129056 v0) {
	NF result0;
	nimfr("z", "macros.nim")
	result0 = (NF)0;
	nimln(333, "macros.nim");
	result0 = v0[(((NI) 2))- 0];
	popFrame();
	return result0;
}

N_NIMCALL(NF, x_131063_140325102)(TY129056 v0) {
	NF result0;
	nimfr("x", "macros.nim")
	result0 = (NF)0;
	nimln(333, "macros.nim");
	result0 = v0[(((NI) 0))- 0];
	popFrame();
	return result0;
}

N_NIMCALL(void, cross_130999_140325102)(TY129056 x0, TY129056 y0, TY129056 Result) {
	NF LOC1;
	NF LOC2;
	NF LOC3;
	NF LOC4;
	NF LOC5;
	NF LOC6;
	NF LOC7;
	NF LOC8;
	NF LOC9;
	NF LOC10;
	NF LOC11;
	NF LOC12;
	nimfr("cross", "vec.nim")
	nimln(26, "vec.nim");
	LOC1 = (NF)0;
	LOC1 = y_131011_140325102(x0);
	LOC2 = (NF)0;
	LOC2 = z_131025_140325102(y0);
	LOC3 = (NF)0;
	LOC3 = y_131011_140325102(y0);
	LOC4 = (NF)0;
	LOC4 = z_131025_140325102(x0);
	nimln(27, "vec.nim");
	LOC5 = (NF)0;
	LOC5 = z_131025_140325102(x0);
	LOC6 = (NF)0;
	LOC6 = x_131063_140325102(y0);
	LOC7 = (NF)0;
	LOC7 = z_131025_140325102(y0);
	LOC8 = (NF)0;
	LOC8 = x_131063_140325102(x0);
	nimln(28, "vec.nim");
	LOC9 = (NF)0;
	LOC9 = x_131063_140325102(x0);
	LOC10 = (NF)0;
	LOC10 = y_131011_140325102(y0);
	LOC11 = (NF)0;
	LOC11 = x_131063_140325102(y0);
	LOC12 = (NF)0;
	LOC12 = y_131011_140325102(x0);
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI129056));
	vec3_130965_140325102(((NF)(((NF)(LOC1) * (NF)(LOC2))) - (NF)(((NF)(LOC3) * (NF)(LOC4)))), ((NF)(((NF)(LOC5) * (NF)(LOC6))) - (NF)(((NF)(LOC7) * (NF)(LOC8)))), ((NF)(((NF)(LOC9) * (NF)(LOC10))) - (NF)(((NF)(LOC11) * (NF)(LOC12)))), Result);
	popFrame();
}

N_NIMCALL(NimStringDesc*, HEX24_131139_140325102)(TY129056 v0) {
	NimStringDesc* result0;
	nimfr("$", "macros.nim")
	result0 = (NimStringDesc*)0;
	nimln(333, "macros.nim");
	result0 = HEX24_131154_2824150814(v0, 3);
	popFrame();
	return result0;
}

N_NIMCALL(NF, HEX3Aanonymous_131278_140325102)(NF a0, NF b0) {
	NF result0;
	nimfr(":anonymous", "macros.nim")
	result0 = (NF)0;
	nimln(333, "macros.nim");
	result0 = ((NF)(a0) * (NF)(b0));
	popFrame();
	return result0;
}

N_NIMCALL(void, HEX2A_131242_140325102)(TY129056 v0, TY129056 u0, TY129056 Result) {
	TY131300 LOC1;
	nimfr("*", "macros.nim")
	nimln(333, "macros.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.ClPrc = ((T140325102_6) (HEX3Aanonymous_131278_140325102)); LOC1.ClEnv = NIM_NIL;
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI129056));
	zipwith_131289_2824150814(v0, u0, LOC1, Result);
	popFrame();
}

N_NIMCALL(NF, dot_131225_140325102)(TY129056 a0, TY129056 b0) {
	NF result0;
	TY129056 LOC1;
	nimfr("dot", "macros.nim")
	result0 = (NF)0;
	nimln(333, "macros.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	HEX2A_131242_140325102(a0, b0, LOC1);
	result0 = sum_131431_1009420244(LOC1, 3);
	popFrame();
	return result0;
}

N_NIMCALL(void, vec2_134944_140325102)(NF a0, NF b0, TY128962 Result) {
	TY134957 LOC1;
	nimfr("vec2", "macros.nim")
	nimln(333, "macros.nim");
	LOC1[0] = a0;
	LOC1[1] = b0;
	memcpy((void*)Result, (NIM_CONST void*)(*(TY128962*) (LOC1)), sizeof(TY128962));
	popFrame();
}

N_NIMCALL(void, vec4_135101_140325102)(NF a0, NF b0, NF c0, NF d0, TY129288 Result) {
	TY135118 LOC1;
	nimfr("vec4", "macros.nim")
	nimln(333, "macros.nim");
	LOC1[0] = a0;
	LOC1[1] = b0;
	LOC1[2] = c0;
	LOC1[3] = d0;
	memcpy((void*)Result, (NIM_CONST void*)(*(TY129288*) (LOC1)), sizeof(TY129288));
	popFrame();
}

N_NIMCALL(void, vec3_140730_140325102)(NF a0, TY129056 Result) {
	TY130980 LOC1;
	nimfr("vec3", "macros.nim")
	nimln(333, "macros.nim");
	LOC1[0] = a0;
	LOC1[1] = a0;
	LOC1[2] = a0;
	memcpy((void*)Result, (NIM_CONST void*)(*(TY129056*) (LOC1)), sizeof(TY129056));
	popFrame();
}

N_NIMCALL(NF, HEX5BHEX5D_140781_140325102)(TY129056 v0, NI ix0) {
	NF result0;
	nimfr("[]", "macros.nim")
	result0 = (NF)0;
	nimln(333, "macros.nim");
	if ((NU)(ix0) > (NU)(2)) raiseIndexError();
	result0 = v0[(ix0)- 0];
	popFrame();
	return result0;
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_141227_140325102)(NF* v0, NI ix0, NF c0) {
	nimfr("[]=", "macros.nim")
	nimln(333, "macros.nim");
	if ((NU)(ix0) > (NU)(2)) raiseIndexError();
	v0[(ix0)- 0] = c0;
	popFrame();
}

N_NIMCALL(NF, HEX3Aanonymous_145814_140325102)(NF a0, NF b0) {
	NF result0;
	nimfr(":anonymous", "macros.nim")
	result0 = (NF)0;
	nimln(333, "macros.nim");
	result0 = ((NF)(a0) + (NF)(b0));
	popFrame();
	return result0;
}

N_NIMCALL(void, HEX2B_145778_140325102)(TY129288 v0, TY129288 u0, TY129288 Result) {
	TY131300 LOC1;
	nimfr("+", "macros.nim")
	nimln(333, "macros.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.ClPrc = ((T140325102_9) (HEX3Aanonymous_145814_140325102)); LOC1.ClEnv = NIM_NIL;
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI129288));
	zipwith_145825_2824150814(v0, u0, LOC1, Result);
	popFrame();
}
N_NIMCALL(void, T140325102_11)(void* p, NI op) {
	TY145737* a;
	a = (TY145737*)p;
}

N_CLOSURE(NF, HEX3Aanonymous_145683_140325102)(NF a0, void* ClEnv) {
	NF result0;
	TY145737* HEX3Aenvp_145740_140325102;
	nimfr(":anonymous", "macros.nim")
	result0 = (NF)0;
	HEX3Aenvp_145740_140325102 = (TY145737*) ClEnv;
	nimln(333, "macros.nim");
	result0 = ((NF)(a0) * (NF)((*HEX3Aenvp_145740_140325102).s145670));
	popFrame();
	return result0;
}

N_NIMCALL(void, HEX2A_145663_140325102)(TY129288 a0, NF s0, TY129288 Result) {
	TY145737* HEX3Aenv_145742_140325102;
	TY145698 LOC1;
	nimfr("*", "macros.nim")
	HEX3Aenv_145742_140325102 = (TY145737*)0;
	nimln(198, "system.nim");
	HEX3Aenv_145742_140325102 = (TY145737*) newObj((&NTI145736), sizeof(TY145737));
	nimln(333, "macros.nim");
	(*HEX3Aenv_145742_140325102).s145670 = s0;
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.ClPrc = HEX3Aanonymous_145683_140325102; LOC1.ClEnv = HEX3Aenv_145742_140325102;
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI129288));
	map_145691_2824150814(a0, LOC1, Result);
	popFrame();
}
N_NIMCALL(void, T140325102_13)(void* p, NI op) {
	TY146121* a;
	a = (TY146121*)p;
}

N_CLOSURE(NF, HEX3Aanonymous_146067_140325102)(NF a0, void* ClEnv) {
	NF result0;
	TY146121* HEX3Aenvp_146124_140325102;
	nimfr(":anonymous", "macros.nim")
	result0 = (NF)0;
	HEX3Aenvp_146124_140325102 = (TY146121*) ClEnv;
	nimln(333, "macros.nim");
	result0 = ((NF)(a0) / (NF)((*HEX3Aenvp_146124_140325102).s146054));
	popFrame();
	return result0;
}

N_NIMCALL(void, HEX2F_146047_140325102)(TY129056 a0, NF s0, TY129056 Result) {
	TY146121* HEX3Aenv_146126_140325102;
	TY145698 LOC1;
	nimfr("/", "macros.nim")
	HEX3Aenv_146126_140325102 = (TY146121*)0;
	nimln(198, "system.nim");
	HEX3Aenv_146126_140325102 = (TY146121*) newObj((&NTI146120), sizeof(TY146121));
	nimln(333, "macros.nim");
	(*HEX3Aenv_146126_140325102).s146054 = s0;
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.ClPrc = HEX3Aanonymous_146067_140325102; LOC1.ClEnv = HEX3Aenv_146126_140325102;
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI129056));
	map_146075_2824150814(a0, LOC1, Result);
	popFrame();
}

N_NIMCALL(NF, length2_146009_140325102)(TY129056 vec0) {
	NF result0;
	TY129056 LOC1;
	nimfr("length2", "macros.nim")
	result0 = (NF)0;
	nimln(334, "macros.nim");
	nimln(335, "macros.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	HEX2A_131242_140325102(vec0, vec0, LOC1);
	result0 = sum_131431_1009420244(LOC1, 3);
	popFrame();
	return result0;
}

N_NIMCALL(NF, length_146001_140325102)(TY129056 vec0) {
	NF result0;
	NF LOC1;
	nimfr("length", "macros.nim")
	result0 = (NF)0;
	nimln(333, "macros.nim");
	LOC1 = (NF)0;
	LOC1 = length2_146009_140325102(vec0);
	result0 = sqrt(LOC1);
	popFrame();
	return result0;
}

N_NIMCALL(void, normalize_145992_140325102)(TY129056 v0, TY129056 Result) {
	NF LOC1;
	TY129056 LOC2;
	nimfr("normalize", "macros.nim")
	nimln(333, "macros.nim");
	LOC1 = (NF)0;
	LOC1 = length_146001_140325102(v0);
	memset((void*)LOC2, 0, sizeof(LOC2));
	HEX2F_146047_140325102(v0, LOC1, LOC2);
	memcpy((void*)Result, (NIM_CONST void*)LOC2, sizeof(TY129056));
	popFrame();
}
N_NIMCALL(void, T140325102_15)(void* p, NI op) {
	TY146176* a;
	a = (TY146176*)p;
}

N_CLOSURE(NF, HEX3Aanonymous_146152_140325102)(NF a0, void* ClEnv) {
	NF result0;
	TY146176* HEX3Aenvp_146179_140325102;
	nimfr(":anonymous", "macros.nim")
	result0 = (NF)0;
	HEX3Aenvp_146179_140325102 = (TY146176*) ClEnv;
	nimln(333, "macros.nim");
	result0 = ((NF)(a0) * (NF)((*HEX3Aenvp_146179_140325102).s146136));
	popFrame();
	return result0;
}

N_NIMCALL(void, HEX2A_146132_140325102)(NF s0, TY129056 a0, TY129056 Result) {
	TY146176* HEX3Aenv_146181_140325102;
	TY145698 LOC1;
	nimfr("*", "macros.nim")
	HEX3Aenv_146181_140325102 = (TY146176*)0;
	nimln(198, "system.nim");
	HEX3Aenv_146181_140325102 = (TY146176*) newObj((&NTI146175), sizeof(TY146176));
	nimln(333, "macros.nim");
	(*HEX3Aenv_146181_140325102).s146136 = s0;
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.ClPrc = HEX3Aanonymous_146152_140325102; LOC1.ClEnv = HEX3Aenv_146181_140325102;
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI129056));
	map_146075_2824150814(a0, LOC1, Result);
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_146338_140325102)(NF* v0, NI ix0, NF c0) {
	nimfr("[]=", "macros.nim")
	nimln(333, "macros.nim");
	if ((NU)(ix0) > (NU)(3)) raiseIndexError();
	v0[(ix0)- 0] = c0;
	popFrame();
}

N_NIMCALL(NF, HEX5BHEX5D_146829_140325102)(TY129288 v0, NI ix0) {
	NF result0;
	nimfr("[]", "macros.nim")
	result0 = (NF)0;
	nimln(333, "macros.nim");
	if ((NU)(ix0) > (NU)(3)) raiseIndexError();
	result0 = v0[(ix0)- 0];
	popFrame();
	return result0;
}

N_NIMCALL(NF, HEX3Aanonymous_147877_140325102)(NF a0, NF b0) {
	NF result0;
	nimfr(":anonymous", "macros.nim")
	result0 = (NF)0;
	nimln(333, "macros.nim");
	result0 = ((NF)(a0) - (NF)(b0));
	popFrame();
	return result0;
}

N_NIMCALL(void, HEX2D_147841_140325102)(TY129056 v0, TY129056 u0, TY129056 Result) {
	TY131300 LOC1;
	nimfr("-", "macros.nim")
	nimln(333, "macros.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.ClPrc = ((T140325102_16) (HEX3Aanonymous_147877_140325102)); LOC1.ClEnv = NIM_NIL;
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI129056));
	zipwith_131289_2824150814(v0, u0, LOC1, Result);
	popFrame();
}

N_NIMCALL(NF32, r_151024_140325102)(TY151018 v0) {
	NF32 result0;
	nimfr("r", "macros.nim")
	result0 = (NF32)0;
	nimln(333, "macros.nim");
	result0 = v0[(((NI) 0))- 0];
	popFrame();
	return result0;
}

N_NIMCALL(NF32, g_151038_140325102)(TY151018 v0) {
	NF32 result0;
	nimfr("g", "macros.nim")
	result0 = (NF32)0;
	nimln(333, "macros.nim");
	result0 = v0[(((NI) 1))- 0];
	popFrame();
	return result0;
}

N_NIMCALL(NF32, b_151052_140325102)(TY151018 v0) {
	NF32 result0;
	nimfr("b", "macros.nim")
	result0 = (NF32)0;
	nimln(333, "macros.nim");
	result0 = v0[(((NI) 2))- 0];
	popFrame();
	return result0;
}

N_NIMCALL(void, vec3_151066_140325102)(NF32 a0, NF32 b0, NF32 c0, TY151018 Result) {
	TY151081 LOC1;
	nimfr("vec3", "macros.nim")
	nimln(333, "macros.nim");
	LOC1[0] = a0;
	LOC1[1] = b0;
	LOC1[2] = c0;
	memcpy((void*)Result, (NIM_CONST void*)(*(TY151018*) (LOC1)), sizeof(TY151018));
	popFrame();
}

N_NIMCALL(NF, r_153406_140325102)(TY129056 v0) {
	NF result0;
	nimfr("r", "macros.nim")
	result0 = (NF)0;
	nimln(333, "macros.nim");
	result0 = v0[(((NI) 0))- 0];
	popFrame();
	return result0;
}

N_NIMCALL(NF, g_153421_140325102)(TY129056 v0) {
	NF result0;
	nimfr("g", "macros.nim")
	result0 = (NF)0;
	nimln(333, "macros.nim");
	result0 = v0[(((NI) 1))- 0];
	popFrame();
	return result0;
}

N_NIMCALL(NF, b_153436_140325102)(TY129056 v0) {
	NF result0;
	nimfr("b", "macros.nim")
	result0 = (NF)0;
	nimln(333, "macros.nim");
	result0 = v0[(((NI) 2))- 0];
	popFrame();
	return result0;
}

N_NIMCALL(NF32, HEX5BHEX5D_155082_140325102)(TY151018 v0, NI ix0) {
	NF32 result0;
	nimfr("[]", "macros.nim")
	result0 = (NF32)0;
	nimln(333, "macros.nim");
	if ((NU)(ix0) > (NU)(2)) raiseIndexError();
	result0 = v0[(ix0)- 0];
	popFrame();
	return result0;
}

N_NIMCALL(void, vec3_155068_140325102)(TY151018 a0, TY151018 Result) {
	TY151081 LOC1;
	nimfr("vec3", "macros.nim")
	nimln(333, "macros.nim");
	LOC1[0] = HEX5BHEX5D_155082_140325102(a0, ((NI) 0));
	LOC1[1] = HEX5BHEX5D_155082_140325102(a0, ((NI) 1));
	LOC1[2] = HEX5BHEX5D_155082_140325102(a0, ((NI) 2));
	memcpy((void*)Result, (NIM_CONST void*)(*(TY151018*) (LOC1)), sizeof(TY151018));
	popFrame();
}

N_NIMCALL(NF32, HEX5BHEX5D_155143_140325102)(TY155127 v0, NI ix0) {
	NF32 result0;
	nimfr("[]", "macros.nim")
	result0 = (NF32)0;
	nimln(333, "macros.nim");
	if ((NU)(ix0) > (NU)(0)) raiseIndexError();
	result0 = v0[(ix0)- 0];
	popFrame();
	return result0;
}

N_NIMCALL(void, vec3_155121_140325102)(TY155127 a0, NF32 b0, TY155127 c0, TY151018 Result) {
	TY151081 LOC1;
	nimfr("vec3", "macros.nim")
	nimln(333, "macros.nim");
	LOC1[0] = HEX5BHEX5D_155143_140325102(a0, ((NI) 0));
	LOC1[1] = b0;
	LOC1[2] = HEX5BHEX5D_155143_140325102(c0, ((NI) 0));
	memcpy((void*)Result, (NIM_CONST void*)(*(TY151018*) (LOC1)), sizeof(TY151018));
	popFrame();
}

N_NIMCALL(NF32, HEX5BHEX5D_155202_140325102)(TY155181 v0, NI ix0) {
	NF32 result0;
	nimfr("[]", "macros.nim")
	result0 = (NF32)0;
	nimln(333, "macros.nim");
	if ((NU)(ix0) > (NU)(1)) raiseIndexError();
	result0 = v0[(ix0)- 0];
	popFrame();
	return result0;
}

N_NIMCALL(void, vec3_155172_140325102)(TY155127 a0, TY155181 b0, TY151018 Result) {
	TY151081 LOC1;
	nimfr("vec3", "macros.nim")
	nimln(333, "macros.nim");
	LOC1[0] = HEX5BHEX5D_155143_140325102(a0, ((NI) 0));
	LOC1[1] = HEX5BHEX5D_155202_140325102(b0, ((NI) 0));
	LOC1[2] = HEX5BHEX5D_155202_140325102(b0, ((NI) 1));
	memcpy((void*)Result, (NIM_CONST void*)(*(TY151018*) (LOC1)), sizeof(TY151018));
	popFrame();
}

N_NIMCALL(void, vec3_155231_140325102)(NF32 a0, TY155181 b0, TY151018 Result) {
	TY151081 LOC1;
	nimfr("vec3", "macros.nim")
	nimln(333, "macros.nim");
	LOC1[0] = a0;
	LOC1[1] = HEX5BHEX5D_155202_140325102(b0, ((NI) 0));
	LOC1[2] = HEX5BHEX5D_155202_140325102(b0, ((NI) 1));
	memcpy((void*)Result, (NIM_CONST void*)(*(TY151018*) (LOC1)), sizeof(TY151018));
	popFrame();
}

N_NIMCALL(void, vec3_155270_140325102)(NF32 a0, TY155127 b0, NF32 c0, TY151018 Result) {
	TY151081 LOC1;
	nimfr("vec3", "macros.nim")
	nimln(333, "macros.nim");
	LOC1[0] = a0;
	LOC1[1] = HEX5BHEX5D_155143_140325102(b0, ((NI) 0));
	LOC1[2] = c0;
	memcpy((void*)Result, (NIM_CONST void*)(*(TY151018*) (LOC1)), sizeof(TY151018));
	popFrame();
}

N_NIMCALL(void, vec3_155301_140325102)(NF32 a0, NF32 b0, TY155127 c0, TY151018 Result) {
	TY151081 LOC1;
	nimfr("vec3", "macros.nim")
	nimln(333, "macros.nim");
	LOC1[0] = a0;
	LOC1[1] = b0;
	LOC1[2] = HEX5BHEX5D_155143_140325102(c0, ((NI) 0));
	memcpy((void*)Result, (NIM_CONST void*)(*(TY151018*) (LOC1)), sizeof(TY151018));
	popFrame();
}

N_NIMCALL(void, vec3_155332_140325102)(TY155127 a0, TY155127 b0, NF32 c0, TY151018 Result) {
	TY151081 LOC1;
	nimfr("vec3", "macros.nim")
	nimln(333, "macros.nim");
	LOC1[0] = HEX5BHEX5D_155143_140325102(a0, ((NI) 0));
	LOC1[1] = HEX5BHEX5D_155143_140325102(b0, ((NI) 0));
	LOC1[2] = c0;
	memcpy((void*)Result, (NIM_CONST void*)(*(TY151018*) (LOC1)), sizeof(TY151018));
	popFrame();
}

N_NIMCALL(void, vec3_155386_140325102)(TY155127 a0, TY155127 b0, TY155127 c0, TY151018 Result) {
	TY151081 LOC1;
	nimfr("vec3", "macros.nim")
	nimln(333, "macros.nim");
	LOC1[0] = HEX5BHEX5D_155143_140325102(a0, ((NI) 0));
	LOC1[1] = HEX5BHEX5D_155143_140325102(b0, ((NI) 0));
	LOC1[2] = HEX5BHEX5D_155143_140325102(c0, ((NI) 0));
	memcpy((void*)Result, (NIM_CONST void*)(*(TY151018*) (LOC1)), sizeof(TY151018));
	popFrame();
}

N_NIMCALL(void, vec3_155439_140325102)(NF32 a0, TY151018 Result) {
	TY151081 LOC1;
	nimfr("vec3", "macros.nim")
	nimln(333, "macros.nim");
	LOC1[0] = a0;
	LOC1[1] = a0;
	LOC1[2] = a0;
	memcpy((void*)Result, (NIM_CONST void*)(*(TY151018*) (LOC1)), sizeof(TY151018));
	popFrame();
}

N_NIMCALL(void, vec3_155455_140325102)(TY155127 a0, NF32 b0, NF32 c0, TY151018 Result) {
	TY151081 LOC1;
	nimfr("vec3", "macros.nim")
	nimln(333, "macros.nim");
	LOC1[0] = HEX5BHEX5D_155143_140325102(a0, ((NI) 0));
	LOC1[1] = b0;
	LOC1[2] = c0;
	memcpy((void*)Result, (NIM_CONST void*)(*(TY151018*) (LOC1)), sizeof(TY151018));
	popFrame();
}

N_NIMCALL(void, vec3_155486_140325102)(TY155181 a0, NF32 b0, TY151018 Result) {
	TY151081 LOC1;
	nimfr("vec3", "macros.nim")
	nimln(333, "macros.nim");
	LOC1[0] = HEX5BHEX5D_155202_140325102(a0, ((NI) 0));
	LOC1[1] = HEX5BHEX5D_155202_140325102(a0, ((NI) 1));
	LOC1[2] = b0;
	memcpy((void*)Result, (NIM_CONST void*)(*(TY151018*) (LOC1)), sizeof(TY151018));
	popFrame();
}

N_NIMCALL(void, vec3_155525_140325102)(NF32 a0, TY155127 b0, TY155127 c0, TY151018 Result) {
	TY151081 LOC1;
	nimfr("vec3", "macros.nim")
	nimln(333, "macros.nim");
	LOC1[0] = a0;
	LOC1[1] = HEX5BHEX5D_155143_140325102(b0, ((NI) 0));
	LOC1[2] = HEX5BHEX5D_155143_140325102(c0, ((NI) 0));
	memcpy((void*)Result, (NIM_CONST void*)(*(TY151018*) (LOC1)), sizeof(TY151018));
	popFrame();
}

N_NIMCALL(void, vec3_155567_140325102)(TY155181 a0, TY155127 b0, TY151018 Result) {
	TY151081 LOC1;
	nimfr("vec3", "macros.nim")
	nimln(333, "macros.nim");
	LOC1[0] = HEX5BHEX5D_155202_140325102(a0, ((NI) 0));
	LOC1[1] = HEX5BHEX5D_155202_140325102(a0, ((NI) 1));
	LOC1[2] = HEX5BHEX5D_155143_140325102(b0, ((NI) 0));
	memcpy((void*)Result, (NIM_CONST void*)(*(TY151018*) (LOC1)), sizeof(TY151018));
	popFrame();
}

N_NIMCALL(NF32, HEX3Aanonymous_155681_140325102)(NF32 a0, NF32 b0) {
	NF32 result0;
	nimfr(":anonymous", "macros.nim")
	result0 = (NF32)0;
	nimln(333, "macros.nim");
	result0 = ((NF32)(a0) + (NF32)(b0));
	popFrame();
	return result0;
}

N_NIMCALL(void, HEX2B_155645_140325102)(TY151018 v0, TY151018 u0, TY151018 Result) {
	TY155703 LOC1;
	nimfr("+", "macros.nim")
	nimln(333, "macros.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.ClPrc = ((T140325102_17) (HEX3Aanonymous_155681_140325102)); LOC1.ClEnv = NIM_NIL;
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI151018));
	zipwith_155692_2824150814(v0, u0, LOC1, Result);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, glm_vecInit000)(void) {
	nimfr("vec", "vec.nim")
	nimln(32, "vec.nim");
	{
		TY131215 LOC5;
		NF LOC6;
		NF LOC7;
		NimStringDesc* LOC8;
		if (!NIM_FALSE) goto LA3;
		nimln(33, "vec.nim");
		chckNil((void*)v_130984_140325102);
		genericReset((void*)v_130984_140325102, (&NTI129056));
		vec3_130965_140325102(1.0000000000000000e+00, 5.0000000000000000e-01, 0.0, v_130984_140325102);
		nimln(34, "vec.nim");
		chckNil((void*)u_130997_140325102);
		genericReset((void*)u_130997_140325102, (&NTI129056));
		vec3_130965_140325102(1.0000000000000000e+00, 1.0000000000000000e+00, 0.0, u_130997_140325102);
		nimln(35, "vec.nim");
		chckNil((void*)c_131136_140325102);
		genericReset((void*)c_131136_140325102, (&NTI129056));
		cross_130999_140325102(v_130984_140325102, u_130997_140325102, c_131136_140325102);
		nimln(36, "vec.nim");
		memset((void*)LOC5, 0, sizeof(LOC5));
		LOC5[0] = HEX24_131139_140325102(c_131136_140325102);
		LOC6 = (NF)0;
		LOC6 = dot_131225_140325102(c_131136_140325102, v_130984_140325102);
		LOC5[1] = nimFloatToStr(LOC6);
		LOC7 = (NF)0;
		LOC7 = dot_131225_140325102(c_131136_140325102, u_130997_140325102);
		LOC5[2] = nimFloatToStr(LOC7);
		LOC8 = (NimStringDesc*)0;
		LOC8 = nsuFormatOpenArray(((NimStringDesc*) &T140325102_7), LOC5, 3);
		printf("%s\012", LOC8? (LOC8)->data:"nil");
		fflush(stdout);
		nimln(37, "vec.nim");
		memcpy((void*)arr_131468_140325102, (NIM_CONST void*)T140325102_8, sizeof(TY131466));
	}
	LA3: ;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, glm_vecDatInit000)(void) {
static TNimNode* T140325102_10[2];
static TNimNode* T140325102_12[2];
static TNimNode* T140325102_14[2];
static TNimNode T140325102_0[9];
NTI129056.size = sizeof(TY129056);
NTI129056.kind = 16;
NTI129056.base = (&NTI124);
NTI129056.flags = 3;
NTI128962.size = sizeof(TY128962);
NTI128962.kind = 16;
NTI128962.base = (&NTI124);
NTI128962.flags = 3;
NTI129288.size = sizeof(TY129288);
NTI129288.kind = 16;
NTI129288.base = (&NTI124);
NTI129288.flags = 3;
NTI145737.size = sizeof(TY145737);
NTI145737.kind = 18;
NTI145737.base = 0;
NTI145737.flags = 3;
T140325102_10[0] = &T140325102_0[1];
T140325102_0[1].kind = 1;
T140325102_0[1].offset = offsetof(TY145737, HEX3Astate);
T140325102_0[1].typ = (&NTI101021);
T140325102_0[1].name = ":state";
T140325102_10[1] = &T140325102_0[2];
T140325102_0[2].kind = 1;
T140325102_0[2].offset = offsetof(TY145737, s145670);
T140325102_0[2].typ = (&NTI124);
T140325102_0[2].name = "s145670";
T140325102_0[0].len = 2; T140325102_0[0].kind = 2; T140325102_0[0].sons = &T140325102_10[0];
NTI145737.node = &T140325102_0[0];
NTI145736.size = sizeof(TY145737*);
NTI145736.kind = 22;
NTI145736.base = (&NTI145737);
NTI145736.flags = 2;
NTI145736.marker = T140325102_11;
NTI146121.size = sizeof(TY146121);
NTI146121.kind = 18;
NTI146121.base = 0;
NTI146121.flags = 3;
T140325102_12[0] = &T140325102_0[4];
T140325102_0[4].kind = 1;
T140325102_0[4].offset = offsetof(TY146121, HEX3Astate);
T140325102_0[4].typ = (&NTI101021);
T140325102_0[4].name = ":state";
T140325102_12[1] = &T140325102_0[5];
T140325102_0[5].kind = 1;
T140325102_0[5].offset = offsetof(TY146121, s146054);
T140325102_0[5].typ = (&NTI124);
T140325102_0[5].name = "s146054";
T140325102_0[3].len = 2; T140325102_0[3].kind = 2; T140325102_0[3].sons = &T140325102_12[0];
NTI146121.node = &T140325102_0[3];
NTI146120.size = sizeof(TY146121*);
NTI146120.kind = 22;
NTI146120.base = (&NTI146121);
NTI146120.flags = 2;
NTI146120.marker = T140325102_13;
NTI146176.size = sizeof(TY146176);
NTI146176.kind = 18;
NTI146176.base = 0;
NTI146176.flags = 3;
T140325102_14[0] = &T140325102_0[7];
T140325102_0[7].kind = 1;
T140325102_0[7].offset = offsetof(TY146176, HEX3Astate);
T140325102_0[7].typ = (&NTI101021);
T140325102_0[7].name = ":state";
T140325102_14[1] = &T140325102_0[8];
T140325102_0[8].kind = 1;
T140325102_0[8].offset = offsetof(TY146176, s146136);
T140325102_0[8].typ = (&NTI124);
T140325102_0[8].name = "s146136";
T140325102_0[6].len = 2; T140325102_0[6].kind = 2; T140325102_0[6].sons = &T140325102_14[0];
NTI146176.node = &T140325102_0[6];
NTI146175.size = sizeof(TY146176*);
NTI146175.kind = 22;
NTI146175.base = (&NTI146176);
NTI146175.flags = 2;
NTI146175.marker = T140325102_15;
NTI151018.size = sizeof(TY151018);
NTI151018.kind = 16;
NTI151018.base = (&NTI126);
NTI151018.flags = 3;
}

