/* Generated by Nim Compiler v0.14.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/john/code/Nim/lib -o /media/sf_D_DRIVE/Work/Code/nim-raytracer/src/src/nimcache/glm_mat.o /media/sf_D_DRIVE/Work/Code/nim-raytracer/src/src/nimcache/glm_mat.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef NF TY128962[2];
typedef TY128962 TY134940[2];
typedef TY128962 TY134987[2];
typedef NF TY129056[3];
typedef TY129056 TY135043[2];
typedef TY129056 TY135086[2];
typedef NF TY129288[4];
typedef TY129288 TY135097[2];
typedef TY129288 TY135152[2];
typedef TY128962 TY135163[3];
typedef TY128962 TY135215[3];
typedef TY129056 TY135226[3];
typedef TY129056 TY135284[3];
typedef TY129288 TY135359[3];
typedef TY129288 TY135423[3];
typedef TY128962 TY135434[4];
typedef TY128962 TY135499[4];
typedef TY129056 TY135510[4];
typedef TY129056 TY135583[4];
typedef TY129288 TY135594[4];
typedef TY129288 TY135675[4];
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef TY129056 TY142238[3];
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef TY129288 TY148410[4];
N_NIMCALL(void, vec2_134944_140325102)(NF a0, NF b0, TY128962 Result);
N_NIMCALL(void, mat2_134972_65709178)(TY128962 a0, TY128962 b0, TY134940 Result);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_21201_1689653243)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, mat2x2_135017_65709178)(TY128962 a0, TY128962 b0, TY134940 Result);
N_NIMCALL(void, mat2x3_135071_65709178)(TY129056 a0, TY129056 b0, TY135043 Result);
N_NIMCALL(void, vec4_135101_140325102)(NF a0, NF b0, NF c0, NF d0, TY129288 Result);
N_NIMCALL(void, mat2x4_135137_65709178)(TY129288 a0, TY129288 b0, TY135097 Result);
N_NIMCALL(void, mat3x2_135197_65709178)(TY128962 a0, TY128962 b0, TY128962 c0, TY135163 Result);
N_NIMCALL(void, mat3_135266_65709178)(TY129056 a0, TY129056 b0, TY129056 c0, TY135226 Result);
N_NIMCALL(void, mat3x3_135330_65709178)(TY129056 a0, TY129056 b0, TY129056 c0, TY135226 Result);
N_NIMCALL(void, mat3x4_135405_65709178)(TY129288 a0, TY129288 b0, TY129288 c0, TY135359 Result);
N_NIMCALL(void, mat4x2_135478_65709178)(TY128962 a0, TY128962 b0, TY128962 c0, TY128962 d0, TY135434 Result);
N_NIMCALL(void, mat4x3_135562_65709178)(TY129056 a0, TY129056 b0, TY129056 c0, TY129056 d0, TY135510 Result);
N_NIMCALL(void, mat4_135654_65709178)(TY129288 a0, TY129288 b0, TY129288 c0, TY129288 d0, TY135594 Result);
N_NIMCALL(void, mat4x4_135741_65709178)(TY129288 a0, TY129288 b0, TY129288 c0, TY129288 d0, TY135594 Result);
N_NIMCALL(void, mat2_134933_65709178)(TY134940 Result);
N_NOINLINE(void, chckNil)(void* p0);
N_NIMCALL(void, genericReset)(void* dest0, TNimType* mt0);
N_NIMCALL(void, mat2x2_134991_65709178)(TY134940 Result);
N_NIMCALL(void, mat2x3_135036_65709178)(TY135043 Result);
N_NIMCALL(void, vec3_130965_140325102)(NF a0, NF b0, NF c0, TY129056 Result);
N_NIMCALL(void, mat2x4_135090_65709178)(TY135097 Result);
N_NIMCALL(void, mat3x2_135156_65709178)(TY135163 Result);
N_NIMCALL(void, mat3_135219_65709178)(TY135226 Result);
N_NIMCALL(void, mat3x3_135288_65709178)(TY135226 Result);
N_NIMCALL(void, mat3x4_135352_65709178)(TY135359 Result);
N_NIMCALL(void, mat4x2_135427_65709178)(TY135434 Result);
N_NIMCALL(void, mat4x3_135503_65709178)(TY135510 Result);
N_NIMCALL(void, mat4_135587_65709178)(TY135594 Result);
N_NIMCALL(void, mat4x4_135679_65709178)(TY135594 Result);
N_NIMCALL(void, vec3_140730_140325102)(NF a0, TY129056 Result);
N_NIMCALL(void, inverse_140747_65709178)(TY129056* m0, TY135226 Result);
N_NIMCALL(NF, HEX5BHEX5D_140781_140325102)(TY129056 v0, NI ix0);
N_NIMCALL(NF*, HEX5BHEX5D_140757_65709178)(TY129056* m0, NI ix0);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void, HEX5BHEX5DHEX3D_141227_140325102)(NF* v0, NI ix0, NF c0);
N_NIMCALL(void, HEX2A_142193_65709178)(TY129056 v0, TY135226 m0, TY129056 Result);
N_NIMCALL(void, matvecproduct_142230_2824150814)(TY129056 v0, TY142238 mat0, TY129056 Result);
N_NIMCALL(void, HEX2AHEX3D_142332_65709178)(TY129056* m0, NF s0);
N_NIMCALL(NimStringDesc*, HEX24_142787_65709178)(TY135226 m0);
N_NIMCALL(NimStringDesc*, HEX24_142806_2824150814)(TY142238 arr0);
N_NIMCALL(void, mat3_142936_65709178)(NF s0, TY135226 Result);
N_NIMCALL(NimStringDesc*, HEX24_148405_2824150814)(TY148410 arr0);
extern TFrame* frameptr_18436_1689653243;
extern TNimType NTI128962; /* array[0..1, float] */
TNimType NTI134940; /* array[0..1, Vec2[system.float]] */
extern TNimType NTI129056; /* array[0..2, float] */
TNimType NTI135043; /* array[0..1, Vec3[system.float]] */
extern TNimType NTI129288; /* array[0..3, float] */
TNimType NTI135097; /* array[0..1, Vec4[system.float]] */
TNimType NTI135163; /* array[0..2, Vec2[system.float]] */
TNimType NTI135226; /* array[0..2, Vec3[system.float]] */
TNimType NTI135359; /* array[0..2, Vec4[system.float]] */
TNimType NTI135434; /* array[0..3, Vec2[system.float]] */
TNimType NTI135510; /* array[0..3, Vec3[system.float]] */
TNimType NTI135594; /* array[0..3, Vec4[system.float]] */
TY135226 m22_140728_65709178;
TY129056 v2_140745_65709178;
TY135226 m22i_142191_65709178;
TY129056 v2m_142317_65709178;
TY129056 v2r_142330_65709178;

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_18436_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_18436_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_18436_1689653243;
	frameptr_18436_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_21201_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_18436_1689653243 = (*frameptr_18436_1689653243).prev;
}

N_NIMCALL(void, mat2_134972_65709178)(TY128962 a0, TY128962 b0, TY134940 Result) {
	TY134987 LOC1;
	nimfr("mat2", "macros.nim")
	nimln(333, "macros.nim");
	memcpy((void*)LOC1[0], (NIM_CONST void*)a0, sizeof(TY128962));
	memcpy((void*)LOC1[1], (NIM_CONST void*)b0, sizeof(TY128962));
	memcpy((void*)Result, (NIM_CONST void*)(*(TY134940*) (LOC1)), sizeof(TY134940));
	popFrame();
}

N_NIMCALL(void, mat2x2_135017_65709178)(TY128962 a0, TY128962 b0, TY134940 Result) {
	TY134987 LOC1;
	nimfr("mat2x2", "macros.nim")
	nimln(333, "macros.nim");
	memcpy((void*)LOC1[0], (NIM_CONST void*)a0, sizeof(TY128962));
	memcpy((void*)LOC1[1], (NIM_CONST void*)b0, sizeof(TY128962));
	memcpy((void*)Result, (NIM_CONST void*)(*(TY134940*) (LOC1)), sizeof(TY134940));
	popFrame();
}

N_NIMCALL(void, mat2x3_135071_65709178)(TY129056 a0, TY129056 b0, TY135043 Result) {
	TY135086 LOC1;
	nimfr("mat2x3", "macros.nim")
	nimln(333, "macros.nim");
	memcpy((void*)LOC1[0], (NIM_CONST void*)a0, sizeof(TY129056));
	memcpy((void*)LOC1[1], (NIM_CONST void*)b0, sizeof(TY129056));
	memcpy((void*)Result, (NIM_CONST void*)(*(TY135043*) (LOC1)), sizeof(TY135043));
	popFrame();
}

N_NIMCALL(void, mat2x4_135137_65709178)(TY129288 a0, TY129288 b0, TY135097 Result) {
	TY135152 LOC1;
	nimfr("mat2x4", "macros.nim")
	nimln(333, "macros.nim");
	memcpy((void*)LOC1[0], (NIM_CONST void*)a0, sizeof(TY129288));
	memcpy((void*)LOC1[1], (NIM_CONST void*)b0, sizeof(TY129288));
	memcpy((void*)Result, (NIM_CONST void*)(*(TY135097*) (LOC1)), sizeof(TY135097));
	popFrame();
}

N_NIMCALL(void, mat3x2_135197_65709178)(TY128962 a0, TY128962 b0, TY128962 c0, TY135163 Result) {
	TY135215 LOC1;
	nimfr("mat3x2", "macros.nim")
	nimln(333, "macros.nim");
	memcpy((void*)LOC1[0], (NIM_CONST void*)a0, sizeof(TY128962));
	memcpy((void*)LOC1[1], (NIM_CONST void*)b0, sizeof(TY128962));
	memcpy((void*)LOC1[2], (NIM_CONST void*)c0, sizeof(TY128962));
	memcpy((void*)Result, (NIM_CONST void*)(*(TY135163*) (LOC1)), sizeof(TY135163));
	popFrame();
}

N_NIMCALL(void, mat3_135266_65709178)(TY129056 a0, TY129056 b0, TY129056 c0, TY135226 Result) {
	TY135284 LOC1;
	nimfr("mat3", "macros.nim")
	nimln(333, "macros.nim");
	memcpy((void*)LOC1[0], (NIM_CONST void*)a0, sizeof(TY129056));
	memcpy((void*)LOC1[1], (NIM_CONST void*)b0, sizeof(TY129056));
	memcpy((void*)LOC1[2], (NIM_CONST void*)c0, sizeof(TY129056));
	memcpy((void*)Result, (NIM_CONST void*)(*(TY135226*) (LOC1)), sizeof(TY135226));
	popFrame();
}

N_NIMCALL(void, mat3x3_135330_65709178)(TY129056 a0, TY129056 b0, TY129056 c0, TY135226 Result) {
	TY135284 LOC1;
	nimfr("mat3x3", "macros.nim")
	nimln(333, "macros.nim");
	memcpy((void*)LOC1[0], (NIM_CONST void*)a0, sizeof(TY129056));
	memcpy((void*)LOC1[1], (NIM_CONST void*)b0, sizeof(TY129056));
	memcpy((void*)LOC1[2], (NIM_CONST void*)c0, sizeof(TY129056));
	memcpy((void*)Result, (NIM_CONST void*)(*(TY135226*) (LOC1)), sizeof(TY135226));
	popFrame();
}

N_NIMCALL(void, mat3x4_135405_65709178)(TY129288 a0, TY129288 b0, TY129288 c0, TY135359 Result) {
	TY135423 LOC1;
	nimfr("mat3x4", "macros.nim")
	nimln(333, "macros.nim");
	memcpy((void*)LOC1[0], (NIM_CONST void*)a0, sizeof(TY129288));
	memcpy((void*)LOC1[1], (NIM_CONST void*)b0, sizeof(TY129288));
	memcpy((void*)LOC1[2], (NIM_CONST void*)c0, sizeof(TY129288));
	memcpy((void*)Result, (NIM_CONST void*)(*(TY135359*) (LOC1)), sizeof(TY135359));
	popFrame();
}

N_NIMCALL(void, mat4x2_135478_65709178)(TY128962 a0, TY128962 b0, TY128962 c0, TY128962 d0, TY135434 Result) {
	TY135499 LOC1;
	nimfr("mat4x2", "macros.nim")
	nimln(333, "macros.nim");
	memcpy((void*)LOC1[0], (NIM_CONST void*)a0, sizeof(TY128962));
	memcpy((void*)LOC1[1], (NIM_CONST void*)b0, sizeof(TY128962));
	memcpy((void*)LOC1[2], (NIM_CONST void*)c0, sizeof(TY128962));
	memcpy((void*)LOC1[3], (NIM_CONST void*)d0, sizeof(TY128962));
	memcpy((void*)Result, (NIM_CONST void*)(*(TY135434*) (LOC1)), sizeof(TY135434));
	popFrame();
}

N_NIMCALL(void, mat4x3_135562_65709178)(TY129056 a0, TY129056 b0, TY129056 c0, TY129056 d0, TY135510 Result) {
	TY135583 LOC1;
	nimfr("mat4x3", "macros.nim")
	nimln(333, "macros.nim");
	memcpy((void*)LOC1[0], (NIM_CONST void*)a0, sizeof(TY129056));
	memcpy((void*)LOC1[1], (NIM_CONST void*)b0, sizeof(TY129056));
	memcpy((void*)LOC1[2], (NIM_CONST void*)c0, sizeof(TY129056));
	memcpy((void*)LOC1[3], (NIM_CONST void*)d0, sizeof(TY129056));
	memcpy((void*)Result, (NIM_CONST void*)(*(TY135510*) (LOC1)), sizeof(TY135510));
	popFrame();
}

N_NIMCALL(void, mat4_135654_65709178)(TY129288 a0, TY129288 b0, TY129288 c0, TY129288 d0, TY135594 Result) {
	TY135675 LOC1;
	nimfr("mat4", "macros.nim")
	nimln(333, "macros.nim");
	memcpy((void*)LOC1[0], (NIM_CONST void*)a0, sizeof(TY129288));
	memcpy((void*)LOC1[1], (NIM_CONST void*)b0, sizeof(TY129288));
	memcpy((void*)LOC1[2], (NIM_CONST void*)c0, sizeof(TY129288));
	memcpy((void*)LOC1[3], (NIM_CONST void*)d0, sizeof(TY129288));
	memcpy((void*)Result, (NIM_CONST void*)(*(TY135594*) (LOC1)), sizeof(TY135594));
	popFrame();
}

N_NIMCALL(void, mat4x4_135741_65709178)(TY129288 a0, TY129288 b0, TY129288 c0, TY129288 d0, TY135594 Result) {
	TY135675 LOC1;
	nimfr("mat4x4", "macros.nim")
	nimln(333, "macros.nim");
	memcpy((void*)LOC1[0], (NIM_CONST void*)a0, sizeof(TY129288));
	memcpy((void*)LOC1[1], (NIM_CONST void*)b0, sizeof(TY129288));
	memcpy((void*)LOC1[2], (NIM_CONST void*)c0, sizeof(TY129288));
	memcpy((void*)LOC1[3], (NIM_CONST void*)d0, sizeof(TY129288));
	memcpy((void*)Result, (NIM_CONST void*)(*(TY135594*) (LOC1)), sizeof(TY135594));
	popFrame();
}

N_NIMCALL(void, mat2_134933_65709178)(TY134940 Result) {
	TY128962 LOC1;
	TY128962 LOC2;
	nimfr("mat2", "macros.nim")
	nimln(333, "macros.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	vec2_134944_140325102(1.0000000000000000e+00, 0.0, LOC1);
	memset((void*)LOC2, 0, sizeof(LOC2));
	vec2_134944_140325102(0.0, 1.0000000000000000e+00, LOC2);
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI134940));
	mat2_134972_65709178(LOC1, LOC2, Result);
	popFrame();
}

N_NIMCALL(void, mat2x2_134991_65709178)(TY134940 Result) {
	TY128962 LOC1;
	TY128962 LOC2;
	nimfr("mat2x2", "macros.nim")
	nimln(333, "macros.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	vec2_134944_140325102(1.0000000000000000e+00, 0.0, LOC1);
	memset((void*)LOC2, 0, sizeof(LOC2));
	vec2_134944_140325102(0.0, 1.0000000000000000e+00, LOC2);
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI134940));
	mat2x2_135017_65709178(LOC1, LOC2, Result);
	popFrame();
}

N_NIMCALL(void, mat2x3_135036_65709178)(TY135043 Result) {
	TY129056 LOC1;
	TY129056 LOC2;
	nimfr("mat2x3", "macros.nim")
	nimln(333, "macros.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	vec3_130965_140325102(1.0000000000000000e+00, 0.0, 0.0, LOC1);
	memset((void*)LOC2, 0, sizeof(LOC2));
	vec3_130965_140325102(0.0, 1.0000000000000000e+00, 0.0, LOC2);
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI135043));
	mat2x3_135071_65709178(LOC1, LOC2, Result);
	popFrame();
}

N_NIMCALL(void, mat2x4_135090_65709178)(TY135097 Result) {
	TY129288 LOC1;
	TY129288 LOC2;
	nimfr("mat2x4", "macros.nim")
	nimln(333, "macros.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	vec4_135101_140325102(1.0000000000000000e+00, 0.0, 0.0, 0.0, LOC1);
	memset((void*)LOC2, 0, sizeof(LOC2));
	vec4_135101_140325102(0.0, 1.0000000000000000e+00, 0.0, 0.0, LOC2);
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI135097));
	mat2x4_135137_65709178(LOC1, LOC2, Result);
	popFrame();
}

N_NIMCALL(void, mat3x2_135156_65709178)(TY135163 Result) {
	TY128962 LOC1;
	TY128962 LOC2;
	TY128962 LOC3;
	nimfr("mat3x2", "macros.nim")
	nimln(333, "macros.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	vec2_134944_140325102(1.0000000000000000e+00, 0.0, LOC1);
	memset((void*)LOC2, 0, sizeof(LOC2));
	vec2_134944_140325102(0.0, 1.0000000000000000e+00, LOC2);
	memset((void*)LOC3, 0, sizeof(LOC3));
	vec2_134944_140325102(0.0, 0.0, LOC3);
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI135163));
	mat3x2_135197_65709178(LOC1, LOC2, LOC3, Result);
	popFrame();
}

N_NIMCALL(void, mat3_135219_65709178)(TY135226 Result) {
	TY129056 LOC1;
	TY129056 LOC2;
	TY129056 LOC3;
	nimfr("mat3", "macros.nim")
	nimln(333, "macros.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	vec3_130965_140325102(1.0000000000000000e+00, 0.0, 0.0, LOC1);
	memset((void*)LOC2, 0, sizeof(LOC2));
	vec3_130965_140325102(0.0, 1.0000000000000000e+00, 0.0, LOC2);
	memset((void*)LOC3, 0, sizeof(LOC3));
	vec3_130965_140325102(0.0, 0.0, 1.0000000000000000e+00, LOC3);
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI135226));
	mat3_135266_65709178(LOC1, LOC2, LOC3, Result);
	popFrame();
}

N_NIMCALL(void, mat3x3_135288_65709178)(TY135226 Result) {
	TY129056 LOC1;
	TY129056 LOC2;
	TY129056 LOC3;
	nimfr("mat3x3", "macros.nim")
	nimln(333, "macros.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	vec3_130965_140325102(1.0000000000000000e+00, 0.0, 0.0, LOC1);
	memset((void*)LOC2, 0, sizeof(LOC2));
	vec3_130965_140325102(0.0, 1.0000000000000000e+00, 0.0, LOC2);
	memset((void*)LOC3, 0, sizeof(LOC3));
	vec3_130965_140325102(0.0, 0.0, 1.0000000000000000e+00, LOC3);
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI135226));
	mat3x3_135330_65709178(LOC1, LOC2, LOC3, Result);
	popFrame();
}

N_NIMCALL(void, mat3x4_135352_65709178)(TY135359 Result) {
	TY129288 LOC1;
	TY129288 LOC2;
	TY129288 LOC3;
	nimfr("mat3x4", "macros.nim")
	nimln(333, "macros.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	vec4_135101_140325102(1.0000000000000000e+00, 0.0, 0.0, 0.0, LOC1);
	memset((void*)LOC2, 0, sizeof(LOC2));
	vec4_135101_140325102(0.0, 1.0000000000000000e+00, 0.0, 0.0, LOC2);
	memset((void*)LOC3, 0, sizeof(LOC3));
	vec4_135101_140325102(0.0, 0.0, 1.0000000000000000e+00, 0.0, LOC3);
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI135359));
	mat3x4_135405_65709178(LOC1, LOC2, LOC3, Result);
	popFrame();
}

N_NIMCALL(void, mat4x2_135427_65709178)(TY135434 Result) {
	TY128962 LOC1;
	TY128962 LOC2;
	TY128962 LOC3;
	TY128962 LOC4;
	nimfr("mat4x2", "macros.nim")
	nimln(333, "macros.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	vec2_134944_140325102(1.0000000000000000e+00, 0.0, LOC1);
	memset((void*)LOC2, 0, sizeof(LOC2));
	vec2_134944_140325102(0.0, 1.0000000000000000e+00, LOC2);
	memset((void*)LOC3, 0, sizeof(LOC3));
	vec2_134944_140325102(0.0, 0.0, LOC3);
	memset((void*)LOC4, 0, sizeof(LOC4));
	vec2_134944_140325102(0.0, 0.0, LOC4);
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI135434));
	mat4x2_135478_65709178(LOC1, LOC2, LOC3, LOC4, Result);
	popFrame();
}

N_NIMCALL(void, mat4x3_135503_65709178)(TY135510 Result) {
	TY129056 LOC1;
	TY129056 LOC2;
	TY129056 LOC3;
	TY129056 LOC4;
	nimfr("mat4x3", "macros.nim")
	nimln(333, "macros.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	vec3_130965_140325102(1.0000000000000000e+00, 0.0, 0.0, LOC1);
	memset((void*)LOC2, 0, sizeof(LOC2));
	vec3_130965_140325102(0.0, 1.0000000000000000e+00, 0.0, LOC2);
	memset((void*)LOC3, 0, sizeof(LOC3));
	vec3_130965_140325102(0.0, 0.0, 1.0000000000000000e+00, LOC3);
	memset((void*)LOC4, 0, sizeof(LOC4));
	vec3_130965_140325102(0.0, 0.0, 0.0, LOC4);
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI135510));
	mat4x3_135562_65709178(LOC1, LOC2, LOC3, LOC4, Result);
	popFrame();
}

N_NIMCALL(void, mat4_135587_65709178)(TY135594 Result) {
	TY129288 LOC1;
	TY129288 LOC2;
	TY129288 LOC3;
	TY129288 LOC4;
	nimfr("mat4", "macros.nim")
	nimln(333, "macros.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	vec4_135101_140325102(1.0000000000000000e+00, 0.0, 0.0, 0.0, LOC1);
	memset((void*)LOC2, 0, sizeof(LOC2));
	vec4_135101_140325102(0.0, 1.0000000000000000e+00, 0.0, 0.0, LOC2);
	memset((void*)LOC3, 0, sizeof(LOC3));
	vec4_135101_140325102(0.0, 0.0, 1.0000000000000000e+00, 0.0, LOC3);
	memset((void*)LOC4, 0, sizeof(LOC4));
	vec4_135101_140325102(0.0, 0.0, 0.0, 1.0000000000000000e+00, LOC4);
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI135594));
	mat4_135654_65709178(LOC1, LOC2, LOC3, LOC4, Result);
	popFrame();
}

N_NIMCALL(void, mat4x4_135679_65709178)(TY135594 Result) {
	TY129288 LOC1;
	TY129288 LOC2;
	TY129288 LOC3;
	TY129288 LOC4;
	nimfr("mat4x4", "macros.nim")
	nimln(333, "macros.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	vec4_135101_140325102(1.0000000000000000e+00, 0.0, 0.0, 0.0, LOC1);
	memset((void*)LOC2, 0, sizeof(LOC2));
	vec4_135101_140325102(0.0, 1.0000000000000000e+00, 0.0, 0.0, LOC2);
	memset((void*)LOC3, 0, sizeof(LOC3));
	vec4_135101_140325102(0.0, 0.0, 1.0000000000000000e+00, 0.0, LOC3);
	memset((void*)LOC4, 0, sizeof(LOC4));
	vec4_135101_140325102(0.0, 0.0, 0.0, 1.0000000000000000e+00, LOC4);
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI135594));
	mat4x4_135741_65709178(LOC1, LOC2, LOC3, LOC4, Result);
	popFrame();
}

N_NIMCALL(NF*, HEX5BHEX5D_140757_65709178)(TY129056* m0, NI ix0) {
	NF* result0;
	nimfr("[]", "macros.nim")
	result0 = (NF*)0;
	nimln(333, "macros.nim");
	if ((NU)(ix0) > (NU)(2)) raiseIndexError();
	result0 = m0[(ix0)- 0];
	popFrame();
	return result0;
}

N_NIMCALL(void, inverse_140747_65709178)(TY129056* m0, TY135226 Result) {
	NF od0;
	NF* LOC1;
	NF LOC2;
	NF* LOC3;
	NF LOC4;
	NF* LOC5;
	NF LOC6;
	NF* LOC7;
	NF LOC8;
	NF* LOC9;
	NF LOC10;
	NF* LOC11;
	NF LOC12;
	NF* LOC13;
	NF LOC14;
	NF* LOC15;
	NF LOC16;
	NF* LOC17;
	NF LOC18;
	NF* LOC19;
	NF LOC20;
	NF* LOC21;
	NF LOC22;
	NF* LOC23;
	NF LOC24;
	NF* LOC25;
	NF LOC26;
	NF* LOC27;
	NF LOC28;
	NF* LOC29;
	NF LOC30;
	NF* LOC31;
	NF* LOC32;
	NF LOC33;
	NF* LOC34;
	NF LOC35;
	NF* LOC36;
	NF LOC37;
	NF* LOC38;
	NF LOC39;
	NF* LOC40;
	NF* LOC41;
	NF LOC42;
	NF* LOC43;
	NF LOC44;
	NF* LOC45;
	NF LOC46;
	NF* LOC47;
	NF LOC48;
	NF* LOC49;
	NF* LOC50;
	NF LOC51;
	NF* LOC52;
	NF LOC53;
	NF* LOC54;
	NF LOC55;
	NF* LOC56;
	NF LOC57;
	NF* LOC58;
	NF* LOC59;
	NF LOC60;
	NF* LOC61;
	NF LOC62;
	NF* LOC63;
	NF LOC64;
	NF* LOC65;
	NF LOC66;
	NF* LOC67;
	NF* LOC68;
	NF LOC69;
	NF* LOC70;
	NF LOC71;
	NF* LOC72;
	NF LOC73;
	NF* LOC74;
	NF LOC75;
	NF* LOC76;
	NF* LOC77;
	NF LOC78;
	NF* LOC79;
	NF LOC80;
	NF* LOC81;
	NF LOC82;
	NF* LOC83;
	NF LOC84;
	NF* LOC85;
	NF* LOC86;
	NF LOC87;
	NF* LOC88;
	NF LOC89;
	NF* LOC90;
	NF LOC91;
	NF* LOC92;
	NF LOC93;
	NF* LOC94;
	NF* LOC95;
	NF LOC96;
	NF* LOC97;
	NF LOC98;
	NF* LOC99;
	NF LOC100;
	NF* LOC101;
	NF LOC102;
	NF* LOC103;
	NF* LOC104;
	NF LOC105;
	NF* LOC106;
	NF LOC107;
	NF* LOC108;
	NF LOC109;
	NF* LOC110;
	NF LOC111;
	nimfr("inverse", "mat.nim")
	nimln(34, "mat.nim");
	nimln(36, "mat.nim");
	nimln(35, "mat.nim");
	LOC1 = (NF*)0;
	LOC1 = HEX5BHEX5D_140757_65709178(m0, ((NI) 0));
	LOC2 = (NF)0;
	LOC2 = HEX5BHEX5D_140781_140325102(LOC1, ((NI) 0));
	LOC3 = (NF*)0;
	LOC3 = HEX5BHEX5D_140757_65709178(m0, ((NI) 1));
	LOC4 = (NF)0;
	LOC4 = HEX5BHEX5D_140781_140325102(LOC3, ((NI) 1));
	LOC5 = (NF*)0;
	LOC5 = HEX5BHEX5D_140757_65709178(m0, ((NI) 2));
	LOC6 = (NF)0;
	LOC6 = HEX5BHEX5D_140781_140325102(LOC5, ((NI) 2));
	LOC7 = (NF*)0;
	LOC7 = HEX5BHEX5D_140757_65709178(m0, ((NI) 2));
	LOC8 = (NF)0;
	LOC8 = HEX5BHEX5D_140781_140325102(LOC7, ((NI) 1));
	LOC9 = (NF*)0;
	LOC9 = HEX5BHEX5D_140757_65709178(m0, ((NI) 1));
	LOC10 = (NF)0;
	LOC10 = HEX5BHEX5D_140781_140325102(LOC9, ((NI) 2));
	nimln(36, "mat.nim");
	LOC11 = (NF*)0;
	LOC11 = HEX5BHEX5D_140757_65709178(m0, ((NI) 1));
	LOC12 = (NF)0;
	LOC12 = HEX5BHEX5D_140781_140325102(LOC11, ((NI) 0));
	LOC13 = (NF*)0;
	LOC13 = HEX5BHEX5D_140757_65709178(m0, ((NI) 0));
	LOC14 = (NF)0;
	LOC14 = HEX5BHEX5D_140781_140325102(LOC13, ((NI) 1));
	LOC15 = (NF*)0;
	LOC15 = HEX5BHEX5D_140757_65709178(m0, ((NI) 2));
	LOC16 = (NF)0;
	LOC16 = HEX5BHEX5D_140781_140325102(LOC15, ((NI) 2));
	LOC17 = (NF*)0;
	LOC17 = HEX5BHEX5D_140757_65709178(m0, ((NI) 2));
	LOC18 = (NF)0;
	LOC18 = HEX5BHEX5D_140781_140325102(LOC17, ((NI) 1));
	LOC19 = (NF*)0;
	LOC19 = HEX5BHEX5D_140757_65709178(m0, ((NI) 0));
	LOC20 = (NF)0;
	LOC20 = HEX5BHEX5D_140781_140325102(LOC19, ((NI) 2));
	nimln(37, "mat.nim");
	LOC21 = (NF*)0;
	LOC21 = HEX5BHEX5D_140757_65709178(m0, ((NI) 2));
	LOC22 = (NF)0;
	LOC22 = HEX5BHEX5D_140781_140325102(LOC21, ((NI) 0));
	LOC23 = (NF*)0;
	LOC23 = HEX5BHEX5D_140757_65709178(m0, ((NI) 0));
	LOC24 = (NF)0;
	LOC24 = HEX5BHEX5D_140781_140325102(LOC23, ((NI) 1));
	LOC25 = (NF*)0;
	LOC25 = HEX5BHEX5D_140757_65709178(m0, ((NI) 1));
	LOC26 = (NF)0;
	LOC26 = HEX5BHEX5D_140781_140325102(LOC25, ((NI) 2));
	LOC27 = (NF*)0;
	LOC27 = HEX5BHEX5D_140757_65709178(m0, ((NI) 1));
	LOC28 = (NF)0;
	LOC28 = HEX5BHEX5D_140781_140325102(LOC27, ((NI) 1));
	LOC29 = (NF*)0;
	LOC29 = HEX5BHEX5D_140757_65709178(m0, ((NI) 0));
	LOC30 = (NF)0;
	LOC30 = HEX5BHEX5D_140781_140325102(LOC29, ((NI) 2));
	od0 = ((NF)(1.0000000000000000e+00) / (NF)(((NF)(((NF)(((NF)(LOC2) * (NF)(((NF)(((NF)(LOC4) * (NF)(LOC6))) - (NF)(((NF)(LOC8) * (NF)(LOC10))))))) - (NF)(((NF)(LOC12) * (NF)(((NF)(((NF)(LOC14) * (NF)(LOC16))) - (NF)(((NF)(LOC18) * (NF)(LOC20))))))))) + (NF)(((NF)(LOC22) * (NF)(((NF)(((NF)(LOC24) * (NF)(LOC26))) - (NF)(((NF)(LOC28) * (NF)(LOC30))))))))));
	nimln(39, "mat.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI135226));
	mat3_135219_65709178(Result);
	nimln(40, "mat.nim");
	LOC31 = (NF*)0;
	LOC31 = HEX5BHEX5D_140757_65709178(Result, ((NI) 0));
	LOC32 = (NF*)0;
	LOC32 = HEX5BHEX5D_140757_65709178(m0, ((NI) 1));
	LOC33 = (NF)0;
	LOC33 = HEX5BHEX5D_140781_140325102(LOC32, ((NI) 1));
	LOC34 = (NF*)0;
	LOC34 = HEX5BHEX5D_140757_65709178(m0, ((NI) 2));
	LOC35 = (NF)0;
	LOC35 = HEX5BHEX5D_140781_140325102(LOC34, ((NI) 2));
	LOC36 = (NF*)0;
	LOC36 = HEX5BHEX5D_140757_65709178(m0, ((NI) 2));
	LOC37 = (NF)0;
	LOC37 = HEX5BHEX5D_140781_140325102(LOC36, ((NI) 1));
	LOC38 = (NF*)0;
	LOC38 = HEX5BHEX5D_140757_65709178(m0, ((NI) 1));
	LOC39 = (NF)0;
	LOC39 = HEX5BHEX5D_140781_140325102(LOC38, ((NI) 2));
	HEX5BHEX5DHEX3D_141227_140325102(LOC31, ((NI) 0), ((NF)(((NF)(((NF)(LOC33) * (NF)(LOC35))) - (NF)(((NF)(LOC37) * (NF)(LOC39))))) * (NF)(od0)));
	nimln(41, "mat.nim");
	LOC40 = (NF*)0;
	LOC40 = HEX5BHEX5D_140757_65709178(Result, ((NI) 1));
	LOC41 = (NF*)0;
	LOC41 = HEX5BHEX5D_140757_65709178(m0, ((NI) 1));
	LOC42 = (NF)0;
	LOC42 = HEX5BHEX5D_140781_140325102(LOC41, ((NI) 0));
	LOC43 = (NF*)0;
	LOC43 = HEX5BHEX5D_140757_65709178(m0, ((NI) 2));
	LOC44 = (NF)0;
	LOC44 = HEX5BHEX5D_140781_140325102(LOC43, ((NI) 2));
	LOC45 = (NF*)0;
	LOC45 = HEX5BHEX5D_140757_65709178(m0, ((NI) 2));
	LOC46 = (NF)0;
	LOC46 = HEX5BHEX5D_140781_140325102(LOC45, ((NI) 0));
	LOC47 = (NF*)0;
	LOC47 = HEX5BHEX5D_140757_65709178(m0, ((NI) 1));
	LOC48 = (NF)0;
	LOC48 = HEX5BHEX5D_140781_140325102(LOC47, ((NI) 2));
	HEX5BHEX5DHEX3D_141227_140325102(LOC40, ((NI) 0), ((NF)(-(((NF)(((NF)(LOC42) * (NF)(LOC44))) - (NF)(((NF)(LOC46) * (NF)(LOC48)))))) * (NF)(od0)));
	nimln(42, "mat.nim");
	LOC49 = (NF*)0;
	LOC49 = HEX5BHEX5D_140757_65709178(Result, ((NI) 2));
	LOC50 = (NF*)0;
	LOC50 = HEX5BHEX5D_140757_65709178(m0, ((NI) 1));
	LOC51 = (NF)0;
	LOC51 = HEX5BHEX5D_140781_140325102(LOC50, ((NI) 0));
	LOC52 = (NF*)0;
	LOC52 = HEX5BHEX5D_140757_65709178(m0, ((NI) 2));
	LOC53 = (NF)0;
	LOC53 = HEX5BHEX5D_140781_140325102(LOC52, ((NI) 1));
	LOC54 = (NF*)0;
	LOC54 = HEX5BHEX5D_140757_65709178(m0, ((NI) 2));
	LOC55 = (NF)0;
	LOC55 = HEX5BHEX5D_140781_140325102(LOC54, ((NI) 0));
	LOC56 = (NF*)0;
	LOC56 = HEX5BHEX5D_140757_65709178(m0, ((NI) 1));
	LOC57 = (NF)0;
	LOC57 = HEX5BHEX5D_140781_140325102(LOC56, ((NI) 1));
	HEX5BHEX5DHEX3D_141227_140325102(LOC49, ((NI) 0), ((NF)(((NF)(((NF)(LOC51) * (NF)(LOC53))) - (NF)(((NF)(LOC55) * (NF)(LOC57))))) * (NF)(od0)));
	nimln(43, "mat.nim");
	LOC58 = (NF*)0;
	LOC58 = HEX5BHEX5D_140757_65709178(Result, ((NI) 0));
	LOC59 = (NF*)0;
	LOC59 = HEX5BHEX5D_140757_65709178(m0, ((NI) 0));
	LOC60 = (NF)0;
	LOC60 = HEX5BHEX5D_140781_140325102(LOC59, ((NI) 1));
	LOC61 = (NF*)0;
	LOC61 = HEX5BHEX5D_140757_65709178(m0, ((NI) 2));
	LOC62 = (NF)0;
	LOC62 = HEX5BHEX5D_140781_140325102(LOC61, ((NI) 2));
	LOC63 = (NF*)0;
	LOC63 = HEX5BHEX5D_140757_65709178(m0, ((NI) 2));
	LOC64 = (NF)0;
	LOC64 = HEX5BHEX5D_140781_140325102(LOC63, ((NI) 1));
	LOC65 = (NF*)0;
	LOC65 = HEX5BHEX5D_140757_65709178(m0, ((NI) 0));
	LOC66 = (NF)0;
	LOC66 = HEX5BHEX5D_140781_140325102(LOC65, ((NI) 2));
	HEX5BHEX5DHEX3D_141227_140325102(LOC58, ((NI) 1), ((NF)(-(((NF)(((NF)(LOC60) * (NF)(LOC62))) - (NF)(((NF)(LOC64) * (NF)(LOC66)))))) * (NF)(od0)));
	nimln(44, "mat.nim");
	LOC67 = (NF*)0;
	LOC67 = HEX5BHEX5D_140757_65709178(Result, ((NI) 1));
	LOC68 = (NF*)0;
	LOC68 = HEX5BHEX5D_140757_65709178(m0, ((NI) 0));
	LOC69 = (NF)0;
	LOC69 = HEX5BHEX5D_140781_140325102(LOC68, ((NI) 0));
	LOC70 = (NF*)0;
	LOC70 = HEX5BHEX5D_140757_65709178(m0, ((NI) 2));
	LOC71 = (NF)0;
	LOC71 = HEX5BHEX5D_140781_140325102(LOC70, ((NI) 2));
	LOC72 = (NF*)0;
	LOC72 = HEX5BHEX5D_140757_65709178(m0, ((NI) 2));
	LOC73 = (NF)0;
	LOC73 = HEX5BHEX5D_140781_140325102(LOC72, ((NI) 0));
	LOC74 = (NF*)0;
	LOC74 = HEX5BHEX5D_140757_65709178(m0, ((NI) 0));
	LOC75 = (NF)0;
	LOC75 = HEX5BHEX5D_140781_140325102(LOC74, ((NI) 2));
	HEX5BHEX5DHEX3D_141227_140325102(LOC67, ((NI) 1), ((NF)(((NF)(((NF)(LOC69) * (NF)(LOC71))) - (NF)(((NF)(LOC73) * (NF)(LOC75))))) * (NF)(od0)));
	nimln(45, "mat.nim");
	LOC76 = (NF*)0;
	LOC76 = HEX5BHEX5D_140757_65709178(Result, ((NI) 2));
	LOC77 = (NF*)0;
	LOC77 = HEX5BHEX5D_140757_65709178(m0, ((NI) 0));
	LOC78 = (NF)0;
	LOC78 = HEX5BHEX5D_140781_140325102(LOC77, ((NI) 0));
	LOC79 = (NF*)0;
	LOC79 = HEX5BHEX5D_140757_65709178(m0, ((NI) 2));
	LOC80 = (NF)0;
	LOC80 = HEX5BHEX5D_140781_140325102(LOC79, ((NI) 1));
	LOC81 = (NF*)0;
	LOC81 = HEX5BHEX5D_140757_65709178(m0, ((NI) 2));
	LOC82 = (NF)0;
	LOC82 = HEX5BHEX5D_140781_140325102(LOC81, ((NI) 0));
	LOC83 = (NF*)0;
	LOC83 = HEX5BHEX5D_140757_65709178(m0, ((NI) 0));
	LOC84 = (NF)0;
	LOC84 = HEX5BHEX5D_140781_140325102(LOC83, ((NI) 1));
	HEX5BHEX5DHEX3D_141227_140325102(LOC76, ((NI) 1), ((NF)(-(((NF)(((NF)(LOC78) * (NF)(LOC80))) - (NF)(((NF)(LOC82) * (NF)(LOC84)))))) * (NF)(od0)));
	nimln(46, "mat.nim");
	LOC85 = (NF*)0;
	LOC85 = HEX5BHEX5D_140757_65709178(Result, ((NI) 0));
	LOC86 = (NF*)0;
	LOC86 = HEX5BHEX5D_140757_65709178(m0, ((NI) 0));
	LOC87 = (NF)0;
	LOC87 = HEX5BHEX5D_140781_140325102(LOC86, ((NI) 1));
	LOC88 = (NF*)0;
	LOC88 = HEX5BHEX5D_140757_65709178(m0, ((NI) 1));
	LOC89 = (NF)0;
	LOC89 = HEX5BHEX5D_140781_140325102(LOC88, ((NI) 2));
	LOC90 = (NF*)0;
	LOC90 = HEX5BHEX5D_140757_65709178(m0, ((NI) 1));
	LOC91 = (NF)0;
	LOC91 = HEX5BHEX5D_140781_140325102(LOC90, ((NI) 1));
	LOC92 = (NF*)0;
	LOC92 = HEX5BHEX5D_140757_65709178(m0, ((NI) 0));
	LOC93 = (NF)0;
	LOC93 = HEX5BHEX5D_140781_140325102(LOC92, ((NI) 2));
	HEX5BHEX5DHEX3D_141227_140325102(LOC85, ((NI) 2), ((NF)(((NF)(((NF)(LOC87) * (NF)(LOC89))) - (NF)(((NF)(LOC91) * (NF)(LOC93))))) * (NF)(od0)));
	nimln(47, "mat.nim");
	LOC94 = (NF*)0;
	LOC94 = HEX5BHEX5D_140757_65709178(Result, ((NI) 1));
	LOC95 = (NF*)0;
	LOC95 = HEX5BHEX5D_140757_65709178(m0, ((NI) 0));
	LOC96 = (NF)0;
	LOC96 = HEX5BHEX5D_140781_140325102(LOC95, ((NI) 0));
	LOC97 = (NF*)0;
	LOC97 = HEX5BHEX5D_140757_65709178(m0, ((NI) 1));
	LOC98 = (NF)0;
	LOC98 = HEX5BHEX5D_140781_140325102(LOC97, ((NI) 2));
	LOC99 = (NF*)0;
	LOC99 = HEX5BHEX5D_140757_65709178(m0, ((NI) 1));
	LOC100 = (NF)0;
	LOC100 = HEX5BHEX5D_140781_140325102(LOC99, ((NI) 0));
	LOC101 = (NF*)0;
	LOC101 = HEX5BHEX5D_140757_65709178(m0, ((NI) 0));
	LOC102 = (NF)0;
	LOC102 = HEX5BHEX5D_140781_140325102(LOC101, ((NI) 2));
	HEX5BHEX5DHEX3D_141227_140325102(LOC94, ((NI) 2), ((NF)(-(((NF)(((NF)(LOC96) * (NF)(LOC98))) - (NF)(((NF)(LOC100) * (NF)(LOC102)))))) * (NF)(od0)));
	nimln(48, "mat.nim");
	LOC103 = (NF*)0;
	LOC103 = HEX5BHEX5D_140757_65709178(Result, ((NI) 2));
	LOC104 = (NF*)0;
	LOC104 = HEX5BHEX5D_140757_65709178(m0, ((NI) 0));
	LOC105 = (NF)0;
	LOC105 = HEX5BHEX5D_140781_140325102(LOC104, ((NI) 0));
	LOC106 = (NF*)0;
	LOC106 = HEX5BHEX5D_140757_65709178(m0, ((NI) 1));
	LOC107 = (NF)0;
	LOC107 = HEX5BHEX5D_140781_140325102(LOC106, ((NI) 1));
	LOC108 = (NF*)0;
	LOC108 = HEX5BHEX5D_140757_65709178(m0, ((NI) 1));
	LOC109 = (NF)0;
	LOC109 = HEX5BHEX5D_140781_140325102(LOC108, ((NI) 0));
	LOC110 = (NF*)0;
	LOC110 = HEX5BHEX5D_140757_65709178(m0, ((NI) 0));
	LOC111 = (NF)0;
	LOC111 = HEX5BHEX5D_140781_140325102(LOC110, ((NI) 1));
	HEX5BHEX5DHEX3D_141227_140325102(LOC103, ((NI) 2), ((NF)(((NF)(((NF)(LOC105) * (NF)(LOC107))) - (NF)(((NF)(LOC109) * (NF)(LOC111))))) * (NF)(od0)));
	popFrame();
}

N_NIMCALL(void, HEX2A_142193_65709178)(TY129056 v0, TY135226 m0, TY129056 Result) {
	nimfr("*", "macros.nim")
	nimln(333, "macros.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI129056));
	matvecproduct_142230_2824150814(v0, m0, Result);
	popFrame();
}

N_NIMCALL(void, HEX2AHEX3D_142332_65709178)(TY129056* m0, NF s0) {
	TY142238 a0;
	NF* LOC1;
	NF* LOC2;
	NF LOC3;
	NF* LOC4;
	NF* LOC5;
	NF LOC6;
	NF* LOC7;
	NF* LOC8;
	NF LOC9;
	NF* LOC10;
	NF* LOC11;
	NF LOC12;
	NF* LOC13;
	NF* LOC14;
	NF LOC15;
	NF* LOC16;
	NF* LOC17;
	NF LOC18;
	NF* LOC19;
	NF* LOC20;
	NF LOC21;
	NF* LOC22;
	NF* LOC23;
	NF LOC24;
	NF* LOC25;
	NF* LOC26;
	NF LOC27;
	nimfr("*=", "macros.nim")
	memset((void*)a0, 0, sizeof(a0));
	nimln(334, "macros.nim");
	memcpy((void*)a0, (NIM_CONST void*)m0, sizeof(TY142238));
	nimln(335, "macros.nim");
	LOC1 = (NF*)0;
	LOC1 = HEX5BHEX5D_140757_65709178(m0, ((NI) 0));
	LOC2 = (NF*)0;
	LOC2 = HEX5BHEX5D_140757_65709178(m0, ((NI) 0));
	LOC3 = (NF)0;
	LOC3 = HEX5BHEX5D_140781_140325102(LOC2, ((NI) 0));
	HEX5BHEX5DHEX3D_141227_140325102(LOC1, ((NI) 0), ((NF)(LOC3) * (NF)(s0)));
	nimln(336, "macros.nim");
	LOC4 = (NF*)0;
	LOC4 = HEX5BHEX5D_140757_65709178(m0, ((NI) 0));
	LOC5 = (NF*)0;
	LOC5 = HEX5BHEX5D_140757_65709178(m0, ((NI) 0));
	LOC6 = (NF)0;
	LOC6 = HEX5BHEX5D_140781_140325102(LOC5, ((NI) 1));
	HEX5BHEX5DHEX3D_141227_140325102(LOC4, ((NI) 1), ((NF)(LOC6) * (NF)(s0)));
	nimln(337, "macros.nim");
	LOC7 = (NF*)0;
	LOC7 = HEX5BHEX5D_140757_65709178(m0, ((NI) 0));
	LOC8 = (NF*)0;
	LOC8 = HEX5BHEX5D_140757_65709178(m0, ((NI) 0));
	LOC9 = (NF)0;
	LOC9 = HEX5BHEX5D_140781_140325102(LOC8, ((NI) 2));
	HEX5BHEX5DHEX3D_141227_140325102(LOC7, ((NI) 2), ((NF)(LOC9) * (NF)(s0)));
	nimln(338, "macros.nim");
	LOC10 = (NF*)0;
	LOC10 = HEX5BHEX5D_140757_65709178(m0, ((NI) 1));
	LOC11 = (NF*)0;
	LOC11 = HEX5BHEX5D_140757_65709178(m0, ((NI) 1));
	LOC12 = (NF)0;
	LOC12 = HEX5BHEX5D_140781_140325102(LOC11, ((NI) 0));
	HEX5BHEX5DHEX3D_141227_140325102(LOC10, ((NI) 0), ((NF)(LOC12) * (NF)(s0)));
	nimln(339, "macros.nim");
	LOC13 = (NF*)0;
	LOC13 = HEX5BHEX5D_140757_65709178(m0, ((NI) 1));
	LOC14 = (NF*)0;
	LOC14 = HEX5BHEX5D_140757_65709178(m0, ((NI) 1));
	LOC15 = (NF)0;
	LOC15 = HEX5BHEX5D_140781_140325102(LOC14, ((NI) 1));
	HEX5BHEX5DHEX3D_141227_140325102(LOC13, ((NI) 1), ((NF)(LOC15) * (NF)(s0)));
	nimln(340, "macros.nim");
	LOC16 = (NF*)0;
	LOC16 = HEX5BHEX5D_140757_65709178(m0, ((NI) 1));
	LOC17 = (NF*)0;
	LOC17 = HEX5BHEX5D_140757_65709178(m0, ((NI) 1));
	LOC18 = (NF)0;
	LOC18 = HEX5BHEX5D_140781_140325102(LOC17, ((NI) 2));
	HEX5BHEX5DHEX3D_141227_140325102(LOC16, ((NI) 2), ((NF)(LOC18) * (NF)(s0)));
	nimln(341, "macros.nim");
	LOC19 = (NF*)0;
	LOC19 = HEX5BHEX5D_140757_65709178(m0, ((NI) 2));
	LOC20 = (NF*)0;
	LOC20 = HEX5BHEX5D_140757_65709178(m0, ((NI) 2));
	LOC21 = (NF)0;
	LOC21 = HEX5BHEX5D_140781_140325102(LOC20, ((NI) 0));
	HEX5BHEX5DHEX3D_141227_140325102(LOC19, ((NI) 0), ((NF)(LOC21) * (NF)(s0)));
	nimln(342, "macros.nim");
	LOC22 = (NF*)0;
	LOC22 = HEX5BHEX5D_140757_65709178(m0, ((NI) 2));
	LOC23 = (NF*)0;
	LOC23 = HEX5BHEX5D_140757_65709178(m0, ((NI) 2));
	LOC24 = (NF)0;
	LOC24 = HEX5BHEX5D_140781_140325102(LOC23, ((NI) 1));
	HEX5BHEX5DHEX3D_141227_140325102(LOC22, ((NI) 1), ((NF)(LOC24) * (NF)(s0)));
	nimln(343, "macros.nim");
	LOC25 = (NF*)0;
	LOC25 = HEX5BHEX5D_140757_65709178(m0, ((NI) 2));
	LOC26 = (NF*)0;
	LOC26 = HEX5BHEX5D_140757_65709178(m0, ((NI) 2));
	LOC27 = (NF)0;
	LOC27 = HEX5BHEX5D_140781_140325102(LOC26, ((NI) 2));
	HEX5BHEX5DHEX3D_141227_140325102(LOC25, ((NI) 2), ((NF)(LOC27) * (NF)(s0)));
	popFrame();
}

N_NIMCALL(NimStringDesc*, HEX24_142787_65709178)(TY135226 m0) {
	NimStringDesc* result0;
	nimfr("$", "macros.nim")
	result0 = (NimStringDesc*)0;
	nimln(333, "macros.nim");
	result0 = HEX24_142806_2824150814(m0);
	popFrame();
	return result0;
}

N_NIMCALL(void, mat3_142936_65709178)(NF s0, TY135226 Result) {
	TY129056 LOC1;
	TY129056 LOC2;
	TY129056 LOC3;
	nimfr("mat3", "macros.nim")
	nimln(333, "macros.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	vec3_130965_140325102(s0, 0.0, 0.0, LOC1);
	memset((void*)LOC2, 0, sizeof(LOC2));
	vec3_130965_140325102(0.0, s0, 0.0, LOC2);
	memset((void*)LOC3, 0, sizeof(LOC3));
	vec3_130965_140325102(0.0, 0.0, s0, LOC3);
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI135226));
	mat3x3_135330_65709178(LOC1, LOC2, LOC3, Result);
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_145935_65709178)(TY129288* m0, NI ix0, TY129288 c0) {
	nimfr("[]=", "macros.nim")
	nimln(333, "macros.nim");
	if ((NU)(ix0) > (NU)(3)) raiseIndexError();
	memcpy((void*)m0[(ix0)- 0], (NIM_CONST void*)c0, sizeof(TY129288));
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5D_145632_65709178)(TY135594 m0, NI ix0, TY129288 Result) {
	nimfr("[]", "macros.nim")
	nimln(333, "macros.nim");
	if ((NU)(ix0) > (NU)(3)) raiseIndexError();
	memcpy((void*)Result, (NIM_CONST void*)m0[(ix0)- 0], sizeof(TY129288));
	popFrame();
}

N_NIMCALL(void, mat4_146186_65709178)(NF s0, TY135594 Result) {
	TY129288 LOC1;
	TY129288 LOC2;
	TY129288 LOC3;
	TY129288 LOC4;
	nimfr("mat4", "macros.nim")
	nimln(333, "macros.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	vec4_135101_140325102(s0, 0.0, 0.0, 0.0, LOC1);
	memset((void*)LOC2, 0, sizeof(LOC2));
	vec4_135101_140325102(0.0, s0, 0.0, 0.0, LOC2);
	memset((void*)LOC3, 0, sizeof(LOC3));
	vec4_135101_140325102(0.0, 0.0, s0, 0.0, LOC3);
	memset((void*)LOC4, 0, sizeof(LOC4));
	vec4_135101_140325102(0.0, 0.0, 0.0, s0, LOC4);
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI135594));
	mat4x4_135741_65709178(LOC1, LOC2, LOC3, LOC4, Result);
	popFrame();
}

N_NIMCALL(NF*, HEX5BHEX5D_146293_65709178)(TY129288* m0, NI ix0) {
	NF* result0;
	nimfr("[]", "macros.nim")
	result0 = (NF*)0;
	nimln(333, "macros.nim");
	if ((NU)(ix0) > (NU)(3)) raiseIndexError();
	result0 = m0[(ix0)- 0];
	popFrame();
	return result0;
}

N_NIMCALL(NimStringDesc*, HEX24_148386_65709178)(TY135594 m0) {
	NimStringDesc* result0;
	nimfr("$", "macros.nim")
	result0 = (NimStringDesc*)0;
	nimln(333, "macros.nim");
	result0 = HEX24_148405_2824150814(m0);
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, glm_matInit000)(void) {
	nimfr("mat", "mat.nim")
	nimln(117, "mat.nim");
	{
		TY129056 LOC5;
		TY129056 LOC6;
		TY129056 LOC7;
		NimStringDesc* LOC8;
		TY135226 LOC9;
		NimStringDesc* LOC10;
		if (!NIM_FALSE) goto LA3;
		nimln(119, "mat.nim");
		memset((void*)LOC5, 0, sizeof(LOC5));
		vec3_130965_140325102(1.0000000000000000e+00, 5.0000000000000000e+00, 1.0000000000000000e+01, LOC5);
		memset((void*)LOC6, 0, sizeof(LOC6));
		vec3_130965_140325102(6.6000000000000003e-01, 1.0000000000000000e+00, 7.0000000000000000e+01, LOC6);
		memset((void*)LOC7, 0, sizeof(LOC7));
		vec3_130965_140325102(1.0000000000000000e+01, 2.0000000000000000e+00, 1.0000000000000000e+00, LOC7);
		chckNil((void*)m22_140728_65709178);
		genericReset((void*)m22_140728_65709178, (&NTI135226));
		mat3_135266_65709178(LOC5, LOC6, LOC7, m22_140728_65709178);
		nimln(120, "mat.nim");
		chckNil((void*)v2_140745_65709178);
		genericReset((void*)v2_140745_65709178, (&NTI129056));
		vec3_140730_140325102(2.0000000000000000e+00, v2_140745_65709178);
		nimln(121, "mat.nim");
		chckNil((void*)m22i_142191_65709178);
		genericReset((void*)m22i_142191_65709178, (&NTI135226));
		inverse_140747_65709178(m22_140728_65709178, m22i_142191_65709178);
		nimln(122, "mat.nim");
		chckNil((void*)v2m_142317_65709178);
		genericReset((void*)v2m_142317_65709178, (&NTI129056));
		HEX2A_142193_65709178(v2_140745_65709178, m22_140728_65709178, v2m_142317_65709178);
		nimln(123, "mat.nim");
		chckNil((void*)v2r_142330_65709178);
		genericReset((void*)v2r_142330_65709178, (&NTI129056));
		HEX2A_142193_65709178(v2m_142317_65709178, m22i_142191_65709178, v2r_142330_65709178);
		nimln(126, "mat.nim");
		HEX2AHEX3D_142332_65709178(m22_140728_65709178, 3.0000000000000000e+00);
		nimln(127, "mat.nim");
		LOC8 = (NimStringDesc*)0;
		LOC8 = HEX24_142787_65709178(m22_140728_65709178);
		printf("%s\012", LOC8? (LOC8)->data:"nil");
		fflush(stdout);
		nimln(129, "mat.nim");
		memset((void*)LOC9, 0, sizeof(LOC9));
		mat3_142936_65709178(5.0000000000000000e+00, LOC9);
		LOC10 = (NimStringDesc*)0;
		LOC10 = HEX24_142787_65709178(LOC9);
		printf("%s\012", LOC10? (LOC10)->data:"nil");
		fflush(stdout);
	}
	LA3: ;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, glm_matDatInit000)(void) {
NTI134940.size = sizeof(TY134940);
NTI134940.kind = 16;
NTI134940.base = (&NTI128962);
NTI134940.flags = 3;
NTI135043.size = sizeof(TY135043);
NTI135043.kind = 16;
NTI135043.base = (&NTI129056);
NTI135043.flags = 3;
NTI135097.size = sizeof(TY135097);
NTI135097.kind = 16;
NTI135097.base = (&NTI129288);
NTI135097.flags = 3;
NTI135163.size = sizeof(TY135163);
NTI135163.kind = 16;
NTI135163.base = (&NTI128962);
NTI135163.flags = 3;
NTI135226.size = sizeof(TY135226);
NTI135226.kind = 16;
NTI135226.base = (&NTI129056);
NTI135226.flags = 3;
NTI135359.size = sizeof(TY135359);
NTI135359.kind = 16;
NTI135359.base = (&NTI129288);
NTI135359.flags = 3;
NTI135434.size = sizeof(TY135434);
NTI135434.kind = 16;
NTI135434.base = (&NTI128962);
NTI135434.flags = 3;
NTI135510.size = sizeof(TY135510);
NTI135510.kind = 16;
NTI135510.base = (&NTI129056);
NTI135510.flags = 3;
NTI135594.size = sizeof(TY135594);
NTI135594.kind = 16;
NTI135594.base = (&NTI129288);
NTI135594.flags = 3;
}

