/* Generated by Nim Compiler v0.14.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/john/code/Nim/lib -o /media/sf_D_DRIVE/Work/Code/nim-raytracer/src/src/nimcache/glm_vector.o /media/sf_D_DRIVE/Work/Code/nim-raytracer/src/src/nimcache/glm_vector.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
typedef struct TY118097 TY118097;
typedef struct TY118098 TY118098;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TY118938 TY118938;
typedef struct NimStringDesc NimStringDesc;
typedef struct TY14805 TY14805;
typedef struct Cell47305 Cell47305;
typedef struct Cellseq47321 Cellseq47321;
typedef struct Gcheap49818 Gcheap49818;
typedef struct Gcstack49816 Gcstack49816;
typedef struct Memregion29485 Memregion29485;
typedef struct Smallchunk29439 Smallchunk29439;
typedef struct Llchunk29479 Llchunk29479;
typedef struct Bigchunk29441 Bigchunk29441;
typedef struct Intset29414 Intset29414;
typedef struct Trunk29410 Trunk29410;
typedef struct Avlnode29483 Avlnode29483;
typedef struct Gcstat49814 Gcstat49814;
typedef struct Cellset47317 Cellset47317;
typedef struct Pagedesc47313 Pagedesc47313;
typedef struct Basechunk29437 Basechunk29437;
typedef struct Freecell29429 Freecell29429;
struct  TGenericSeq  {
NI len;
NI reserved;
};
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (NIM_CHAR item_118272_1556796702, void* ClEnv);
void* ClEnv;
} TY118270;
typedef N_CLOSURE_PTR(NIM_BOOL, T2406155209_9) (NIM_CHAR item_118272_1556796702);
struct  TY118938  {
NI HEX3Astate;
NI veclength118214;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NIM_CHAR TY118604[1];
typedef TY118098* TY118804[2];
typedef NimStringDesc* TY118973[1];
struct  Cell47305  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47321  {
NI len;
NI cap;
Cell47305** d;
};
typedef Smallchunk29439* TY29500[512];
typedef Trunk29410* Trunkbuckets29412[256];
struct  Intset29414  {
Trunkbuckets29412 data;
};
struct  Memregion29485  {
NI minlargeobj;
NI maxlargeobj;
TY29500 freesmallchunks;
Llchunk29479* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk29441* freechunkslist;
Intset29414 chunkstarts;
Avlnode29483* root;
Avlnode29483* deleted;
Avlnode29483* last;
Avlnode29483* freeavlnodes;
NIM_BOOL locked;
};
struct  Gcstat49814  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset47317  {
NI counter;
NI max;
Pagedesc47313* head;
Pagedesc47313** data;
};
struct  Gcheap49818  {
Gcstack49816* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47321 zct;
Cellseq47321 decstack;
Cellseq47321 tempstack;
NI recgclock;
Memregion29485 region;
Gcstat49814 stat;
Cellset47317 marked;
Cellseq47321 additionalroots;
};
typedef NimStringDesc* TY119013[2];
struct  Gcstack49816  {
Gcstack49816* prev;
Gcstack49816* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk29437  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk29439  {
  Basechunk29437 Sup;
Smallchunk29439* next;
Smallchunk29439* prev;
Freecell29429* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk29479  {
NI size;
NI acc;
Llchunk29479* next;
};
struct  Bigchunk29441  {
  Basechunk29437 Sup;
Bigchunk29441* next;
Bigchunk29441* prev;
NI align;
NF data;
};
typedef NI TY29418[16];
struct  Trunk29410  {
Trunk29410* next;
NI key;
TY29418 bits;
};
typedef Avlnode29483* TY29490[2];
struct  Avlnode29483  {
TY29490 link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc47313  {
Pagedesc47313* next;
NI key;
TY29418 bits;
};
struct  Freecell29429  {
Freecell29429* next;
NI zerofield;
};
struct TY118098 {
  TGenericSeq Sup;
  NIM_CHAR data[SEQ_DECL_SIZE];
};
struct TY118097 {
  TGenericSeq Sup;
  TY118098* data[SEQ_DECL_SIZE];
};
struct TY14805 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_NIMCALL(NF, floor_117001_2406155209)(NF f0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_21201_1689653243)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NF, round_117007_2406155209)(NF f0);
N_NIMCALL(NF, pow_117013_2406155209)(NF a0, NF b0);
static N_INLINE(void, HEX2AHEX3D_108493_1689653243)(NF* x0, NF y0);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NF, fmod_117048_2406155209)(NF a0, NF b0);
N_NIMCALL(NI, pow_117652_2406155209)(NI a0, NI b0);
N_NIMCALL(NI, fmod_117660_2406155209)(NI a0, NI b0);
N_NIMCALL(NI, getcomponentix_118086_2406155209)(NI shiftn0, NI length0, NI componentix0);
static N_INLINE(NF, HEX2F_90207_1689653243)(NI x0, NI y0);
static N_INLINE(NI, subInt)(NI a0, NI b0);
N_NIMCALL(TY118097*, shifts_118093_2406155209)(TY118098* data0);
N_NIMCALL(void, T2406155209_4)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d0, NI op0);
N_NIMCALL(void, T2406155209_5)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ0, NI len0);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq0, NI elemsize0);
N_NIMCALL(void, genericSeqAssign)(void* dest0, void* src_86004_1689653243, TNimType* mt0);
static N_INLINE(TY118098*, filter_118264_1556796702)(TY118098* seq10, TY118270 pred0);
N_NIMCALL(TY118098*, newseq_118278_1689653243)(NI len0);
N_NIMCALL(TY118098*, reversed_118350_3792311747)(NIM_CHAR* a0, NI a0Len0);
N_NIMCALL(TY118098*, reversed_118366_3792311747)(NIM_CHAR* a0, NI a0Len0, NI first0, NI last0);
N_NIMCALL(TY118098*, concat_118812_1556796702)(TY118098** seqs0, NI seqs0Len0);
N_NIMCALL(TY118097*, getcombinationsforlength_118212_2406155209)(NI veclength0, NI uptovec0);
N_NIMCALL(void, T2406155209_12)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ0, NI size0);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x0);
N_CLOSURE(NIM_BOOL, HEX3Aanonymous_118259_2406155209)(NIM_CHAR x0, void* ClEnv);
N_NIMCALL(NI, glength_118255_2406155209)(NIM_CHAR s0);
N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s0);
N_NIMCALL(NimStringDesc*, nimCharToStr)(NIM_CHAR x0);
N_NIMCALL(void, failedassertimpl_90839_1689653243)(NimStringDesc* msg0);
N_NIMCALL(TY14805*, componentgetters_118967_2406155209)(NIM_CHAR c0, NimStringDesc* sm0);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src0);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src0);
static N_INLINE(void, nimGCunrefNoCycle)(void* p0);
static N_INLINE(Cell47305*, usrtocell_51440_1689653243)(void* usr0);
static N_INLINE(void, rtladdzct_52601_1689653243)(Cell47305* c0);
N_NOINLINE(void, addzct_51417_1689653243)(Cellseq47321* s0, Cell47305* c0);
N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr0, NimStringDesc** a0, NI a0Len0);
N_NIMCALL(TY14805*, parameterconstructor_119033_2406155209)(NIM_CHAR c0, NimStringDesc* sm0);
N_NIMCALL(TY14805*, repeatstr_119083_2406155209)(NimStringDesc* a0, NI n0);
NIM_CONST struct {
  TGenericSeq Sup;
  NIM_CHAR data[1];
} T2406155209_14 = {{1, 1}, {86}};
NIM_CONST TY118098* T2406155209_13 = ((TY118098*)&T2406155209_14);
STRING_LITERAL(T2406155209_19, "len(a) == L seq modified while iterating over it", 48);
STRING_LITERAL(T2406155209_22, "$1[$2]", 6);
STRING_LITERAL(T2406155209_24, "$1:T", 4);
STRING_LITERAL(T2406155209_25, "$1:Vec$2[T]", 11);
extern TFrame* frameptr_18436_1689653243;
extern TNimType NTI136; /* char */
TNimType NTI118098; /* seq[char] */
TNimType NTI118097; /* seq[seq[char]] */
TNimType NTI118938; /* object */
extern TNimType NTI101021; /* range -1..0(int) */
extern TNimType NTI104; /* int */
TNimType NTI118937; /* ref object */
extern TNimType NTI14805; /* seq[string] */
extern Gcheap49818 gch_49858_1689653243;

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_18436_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_18436_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_18436_1689653243;
	frameptr_18436_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_21201_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_18436_1689653243 = (*frameptr_18436_1689653243).prev;
}

N_NIMCALL(NF, floor_117001_2406155209)(NF f0) {
	NF result0;
	nimfr("floor", "vector.nim")
	result0 = (NF)0;
	nimln(11, "vector.nim");
	result0 = ((NF) (((NI) (f0))));
	popFrame();
	return result0;
}

N_NIMCALL(NF, round_117007_2406155209)(NF f0) {
	NF result0;
	NF flo0;
	NF d0;
	nimfr("round", "vector.nim")
	result0 = (NF)0;
	nimln(14, "vector.nim");
	flo0 = floor_117001_2406155209(f0);
	nimln(15, "vector.nim");
	d0 = ((NF)(f0) - (NF)(flo0));
	nimln(16, "vector.nim");
	{
		nimln(347, "system.nim");
		if (!(5.0000000000000000e-01 <= d0)) goto LA3;
		nimln(16, "vector.nim");
		result0 = ((NF)(flo0) + (NF)(1.0000000000000000e+00));
	}
	goto LA1;
	LA3: ;
	{
		nimln(17, "vector.nim");
		result0 = flo0;
	}
	LA1: ;
	popFrame();
	return result0;
}

static N_INLINE(void, HEX2AHEX3D_108493_1689653243)(NF* x0, NF y0) {
	nimfr("*=", "system.nim")
	nimln(3332, "system.nim");
	(*x0) = ((NF)((*x0)) * (NF)(y0));
	popFrame();
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU32)(a0) + (NU32)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NF, pow_117013_2406155209)(NF a0, NF b0) {
	NF result0;
	nimfr("pow", "vector.nim")
	result0 = (NF)0;
	nimln(20, "vector.nim");
	result0 = 1.0000000000000000e+00;
	{
		NI i_117027_2406155209;
		NI HEX3Atmp_117041_2406155209;
		NI res_117044_2406155209;
		i_117027_2406155209 = (NI)0;
		HEX3Atmp_117041_2406155209 = (NI)0;
		nimln(21, "vector.nim");
		HEX3Atmp_117041_2406155209 = ((NI) (b0));
		nimln(1873, "system.nim");
		res_117044_2406155209 = ((NI) 1);
		{
			nimln(1874, "system.nim");
			while (1) {
				NI T2406155209_2;
				if (!(res_117044_2406155209 <= HEX3Atmp_117041_2406155209)) goto LA3;
				nimln(1875, "system.nim");
				i_117027_2406155209 = res_117044_2406155209;
				nimln(22, "vector.nim");
				HEX2AHEX3D_108493_1689653243((&result0), a0);
				nimln(1894, "system.nim");
				T2406155209_2 = addInt(res_117044_2406155209, ((NI) 1));
				res_117044_2406155209 = (NI)(T2406155209_2);
			} LA3: ;
		}
	}
	popFrame();
	return result0;
}

N_NIMCALL(NF, fmod_117048_2406155209)(NF a0, NF b0) {
	NF result0;
	NF diff0;
	NF LOC1;
	nimfr("fmod", "vector.nim")
{	result0 = (NF)0;
	nimln(25, "vector.nim");
	LOC1 = (NF)0;
	LOC1 = floor_117001_2406155209(((NF)(a0) / (NF)(b0)));
	diff0 = ((NF)(LOC1) * (NF)(b0));
	nimln(26, "vector.nim");
	result0 = ((NF)(a0) - (NF)(diff0));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NI, pow_117652_2406155209)(NI a0, NI b0) {
	NI result0;
	NF LOC1;
	NF LOC2;
	nimfr("pow", "vector.nim")
	result0 = (NI)0;
	nimln(91, "vector.nim");
	LOC1 = (NF)0;
	LOC1 = pow_117013_2406155209(((NF) (a0)), ((NF) (b0)));
	LOC2 = (NF)0;
	LOC2 = floor_117001_2406155209(LOC1);
	result0 = ((NI) (LOC2));
	popFrame();
	return result0;
}

N_NIMCALL(NI, fmod_117660_2406155209)(NI a0, NI b0) {
	NI result0;
	NF LOC1;
	NF LOC2;
	nimfr("fmod", "vector.nim")
	result0 = (NI)0;
	nimln(92, "vector.nim");
	LOC1 = (NF)0;
	LOC1 = fmod_117048_2406155209(((NF) (a0)), ((NF) (b0)));
	LOC2 = (NF)0;
	LOC2 = floor_117001_2406155209(LOC1);
	result0 = ((NI) (LOC2));
	popFrame();
	return result0;
}

static N_INLINE(NF, HEX2F_90207_1689653243)(NI x0, NI y0) {
	NF result0;
	nimfr("/", "system.nim")
	result0 = (NF)0;
	nimln(3176, "system.nim");
	result0 = ((NF)(((double) (x0))) / (NF)(((double) (y0))));
	popFrame();
	return result0;
}

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU32)(a0) - (NU32)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU32) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NI, getcomponentix_118086_2406155209)(NI shiftn0, NI length0, NI componentix0) {
	NI result0;
	NI LOC1;
	NI LOC2;
	NI T2406155209_3;
	NI LOC3;
	NF LOC4;
	NF LOC5;
	nimfr("getComponentIx", "vector.nim")
	result0 = (NI)0;
	nimln(118, "vector.nim");
	LOC1 = (NI)0;
	LOC1 = pow_117652_2406155209(length0, componentix0);
	LOC2 = (NI)0;
	LOC2 = fmod_117660_2406155209(shiftn0, LOC1);
	T2406155209_3 = subInt(componentix0, ((NI) 1));
	LOC3 = (NI)0;
	LOC3 = pow_117652_2406155209(length0, (NI)(T2406155209_3));
	LOC4 = (NF)0;
	LOC4 = HEX2F_90207_1689653243(LOC2, LOC3);
	LOC5 = (NF)0;
	LOC5 = floor_117001_2406155209(LOC4);
	result0 = ((NI) (LOC5));
	popFrame();
	return result0;
}
N_NIMCALL(void, T2406155209_4)(void* p, NI op) {
	TY118098* a;
	NI LOC1;
	a = (TY118098*)p;
	LOC1 = (NI)0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}
N_NIMCALL(void, T2406155209_5)(void* p, NI op) {
	TY118097* a;
	NI LOC1;
	a = (TY118097*)p;
	LOC1 = (NI)0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}

N_NIMCALL(TY118097*, shifts_118093_2406155209)(TY118098* data0) {
	TY118097* result0;
	NI length0;
	NI shifts0;
	nimfr("shifts", "vector.nim")
	result0 = (TY118097*)0;
	nimln(122, "vector.nim");
	length0 = (data0 ? data0->Sup.len : 0);
	nimln(123, "vector.nim");
	shifts0 = pow_117652_2406155209(length0, length0);
	nimln(124, "vector.nim");
	result0 = (TY118097*) newSeq((&NTI118097), 0);
	{
		NI i_118135_2406155209;
		NI HEX3Atmp_118193_2406155209;
		NI T2406155209_6;
		NI res_118196_2406155209;
		i_118135_2406155209 = (NI)0;
		HEX3Atmp_118193_2406155209 = (NI)0;
		nimln(126, "vector.nim");
		T2406155209_6 = subInt(shifts0, ((NI) 1));
		HEX3Atmp_118193_2406155209 = (NI)(T2406155209_6);
		nimln(1873, "system.nim");
		res_118196_2406155209 = ((NI) 0);
		{
			nimln(1874, "system.nim");
			while (1) {
				TY118098* cs0;
				NI T2406155209_8;
				if (!(res_118196_2406155209 <= HEX3Atmp_118193_2406155209)) goto LA3;
				nimln(1875, "system.nim");
				i_118135_2406155209 = res_118196_2406155209;
				nimln(127, "vector.nim");
				cs0 = (TY118098*) newSeq((&NTI118098), 0);
				{
					NI j_118163_2406155209;
					NI res_118189_2406155209;
					j_118163_2406155209 = (NI)0;
					nimln(1873, "system.nim");
					res_118189_2406155209 = ((NI) 1);
					{
						nimln(1874, "system.nim");
						while (1) {
							NI LOC7;
							NI T2406155209_7;
							if (!(res_118189_2406155209 <= length0)) goto LA6;
							nimln(1875, "system.nim");
							j_118163_2406155209 = res_118189_2406155209;
							nimln(129, "vector.nim");
							LOC7 = (NI)0;
							LOC7 = getcomponentix_118086_2406155209(i_118135_2406155209, length0, j_118163_2406155209);
							if ((NU)(LOC7) >= (NU)(data0->Sup.len)) raiseIndexError();
							cs0 = (TY118098*) incrSeqV2(&(cs0)->Sup, sizeof(NIM_CHAR));
							cs0->data[cs0->Sup.len] = data0->data[LOC7];
							++cs0->Sup.len;
							nimln(1894, "system.nim");
							T2406155209_7 = addInt(res_118189_2406155209, ((NI) 1));
							res_118189_2406155209 = (NI)(T2406155209_7);
						} LA6: ;
					}
				}
				nimln(130, "vector.nim");
				result0 = (TY118097*) incrSeqV2(&(result0)->Sup, sizeof(TY118098*));
				genericSeqAssign((&result0->data[result0->Sup.len]), cs0, (&NTI118098));
				++result0->Sup.len;
				nimln(1894, "system.nim");
				T2406155209_8 = addInt(res_118196_2406155209, ((NI) 1));
				res_118196_2406155209 = (NI)(T2406155209_8);
			} LA3: ;
		}
	}
	popFrame();
	return result0;
}

static N_INLINE(TY118098*, filter_118264_1556796702)(TY118098* seq10, TY118270 pred0) {
	TY118098* result0;
	nimfr("filter", "sequtils.nim")
	result0 = (TY118098*)0;
	nimln(283, "sequtils.nim");
	result0 = newseq_118278_1689653243(((NI) 0));
	{
		NI i_118312_1556796702;
		NI HEX3Atmp_118324_1556796702;
		NI i_118327_1556796702;
		i_118312_1556796702 = (NI)0;
		HEX3Atmp_118324_1556796702 = (NI)0;
		nimln(284, "sequtils.nim");
		HEX3Atmp_118324_1556796702 = (seq10 ? seq10->Sup.len : 0);
		nimln(3615, "system.nim");
		i_118327_1556796702 = ((NI) 0);
		{
			nimln(3616, "system.nim");
			while (1) {
				NI T2406155209_10;
				if (!(i_118327_1556796702 < HEX3Atmp_118324_1556796702)) goto LA3;
				nimln(3615, "system.nim");
				i_118312_1556796702 = i_118327_1556796702;
				nimln(285, "sequtils.nim");
				{
					NIM_BOOL LOC6;
					if ((NU)(i_118312_1556796702) >= (NU)(seq10->Sup.len)) raiseIndexError();
					LOC6 = (NIM_BOOL)0;
					LOC6 = pred0.ClEnv? pred0.ClPrc(seq10->data[i_118312_1556796702], pred0.ClEnv):((T2406155209_9)(pred0.ClPrc))(seq10->data[i_118312_1556796702]);
					if (!LOC6) goto LA7;
					nimln(286, "sequtils.nim");
					if ((NU)(i_118312_1556796702) >= (NU)(seq10->Sup.len)) raiseIndexError();
					result0 = (TY118098*) incrSeqV2(&(result0)->Sup, sizeof(NIM_CHAR));
					result0->data[result0->Sup.len] = seq10->data[i_118312_1556796702];
					++result0->Sup.len;
				}
				LA7: ;
				nimln(3618, "system.nim");
				T2406155209_10 = addInt(i_118327_1556796702, ((NI) 1));
				i_118327_1556796702 = (NI)(T2406155209_10);
			} LA3: ;
		}
	}
	popFrame();
	return result0;
}
N_NIMCALL(void, T2406155209_12)(void* p, NI op) {
	TY118938* a;
	a = (TY118938*)p;
}

N_NIMCALL(NI, glength_118255_2406155209)(NIM_CHAR s0) {
	NI result0;
	nimfr("glength", "vector.nim")
	result0 = (NI)0;
	nimln(143, "vector.nim");
	switch (((NU8)(s0))) {
	case 86:
	case 49:
	{
		nimln(144, "vector.nim");
		result0 = ((NI) 1);
	}
	break;
	default:
	{
		NimStringDesc* LOC3;
		nimln(145, "vector.nim");
		LOC3 = (NimStringDesc*)0;
		LOC3 = nimCharToStr(s0);
		result0 = nsuParseInt(LOC3);
	}
	break;
	}
	popFrame();
	return result0;
}

N_CLOSURE(NIM_BOOL, HEX3Aanonymous_118259_2406155209)(NIM_CHAR x0, void* ClEnv) {
	NIM_BOOL result0;
	TY118938* HEX3Aenvp_118941_2406155209;
	NI LOC1;
	nimfr(":anonymous", "vector.nim")
{	result0 = (NIM_BOOL)0;
	HEX3Aenvp_118941_2406155209 = (TY118938*) ClEnv;
	nimln(146, "vector.nim");
	LOC1 = (NI)0;
	LOC1 = glength_118255_2406155209(x0);
	result0 = (LOC1 <= (*HEX3Aenvp_118941_2406155209).veclength118214);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(TY118097*, getcombinationsforlength_118212_2406155209)(NI veclength0, NI uptovec0) {
	TY118097* result0;
	TY118938* HEX3Aenv_118943_2406155209;
	TY118098* vx0;
	TY118098* available0;
	TY118270 LOC5;
	NI count0;
	nimfr("getCombinationsForLength", "vector.nim")
	result0 = (TY118097*)0;
	HEX3Aenv_118943_2406155209 = (TY118938*)0;
	nimln(198, "system.nim");
	HEX3Aenv_118943_2406155209 = (TY118938*) newObj((&NTI118937), sizeof(TY118938));
	nimln(137, "vector.nim");
	(*HEX3Aenv_118943_2406155209).veclength118214 = veclength0;
	nimln(138, "vector.nim");
	genericSeqAssign((&vx0), T2406155209_13, (&NTI118098));
	{
		NI i_118243_2406155209;
		NI res_118949_2406155209;
		i_118243_2406155209 = (NI)0;
		nimln(1873, "system.nim");
		res_118949_2406155209 = ((NI) 1);
		{
			nimln(1874, "system.nim");
			while (1) {
				NIM_CHAR c0;
				NimStringDesc* LOC4;
				NI T2406155209_15;
				if (!(res_118949_2406155209 <= uptovec0)) goto LA3;
				nimln(1875, "system.nim");
				i_118243_2406155209 = res_118949_2406155209;
				nimln(140, "vector.nim");
				LOC4 = (NimStringDesc*)0;
				LOC4 = nimIntToStr(i_118243_2406155209);
				if ((NU)(((NI) 0)) > (NU)(LOC4->Sup.len)) raiseIndexError();
				c0 = LOC4->data[((NI) 0)];
				nimln(141, "vector.nim");
				vx0 = (TY118098*) incrSeqV2(&(vx0)->Sup, sizeof(NIM_CHAR));
				vx0->data[vx0->Sup.len] = c0;
				++vx0->Sup.len;
				nimln(1894, "system.nim");
				T2406155209_15 = addInt(res_118949_2406155209, ((NI) 1));
				res_118949_2406155209 = (NI)(T2406155209_15);
			} LA3: ;
		}
	}
	nimln(146, "vector.nim");
	memset((void*)(&LOC5), 0, sizeof(LOC5));
	LOC5.ClPrc = HEX3Aanonymous_118259_2406155209; LOC5.ClEnv = HEX3Aenv_118943_2406155209;
	available0 = filter_118264_1556796702(vx0, LOC5);
	nimln(147, "vector.nim");
	result0 = (TY118097*) newSeq((&NTI118097), 0);
	nimln(148, "vector.nim");
	count0 = ((NI) 0);
	{
		NIM_CHAR sym_118602_2406155209;
		TY118098* HEX3Atmp_118961_2406155209;
		NI i_118964_2406155209;
		NI L_118966_2406155209;
		sym_118602_2406155209 = (NIM_CHAR)0;
		HEX3Atmp_118961_2406155209 = (TY118098*)0;
		nimln(149, "vector.nim");
		HEX3Atmp_118961_2406155209 = reversed_118350_3792311747(available0->data, available0->Sup.len);
		nimln(3423, "system.nim");
		i_118964_2406155209 = ((NI) 0);
		nimln(3424, "system.nim");
		L_118966_2406155209 = (HEX3Atmp_118961_2406155209 ? HEX3Atmp_118961_2406155209->Sup.len : 0);
		{
			nimln(3425, "system.nim");
			while (1) {
				TY118098* res0;
				TY118604 LOC9;
				NI LOC10;
				NI T2406155209_16;
				NI T2406155209_20;
				if (!(i_118964_2406155209 < L_118966_2406155209)) goto LA8;
				nimln(3426, "system.nim");
				if ((NU)(i_118964_2406155209) >= (NU)(HEX3Atmp_118961_2406155209->Sup.len)) raiseIndexError();
				sym_118602_2406155209 = HEX3Atmp_118961_2406155209->data[i_118964_2406155209];
				nimln(150, "vector.nim");
				res0 = (TY118098*) newSeq((&NTI118098), 1);
				LOC9[0] = sym_118602_2406155209;
				res0->data[0] = LOC9[0];
				nimln(151, "vector.nim");
				LOC10 = (NI)0;
				LOC10 = glength_118255_2406155209(sym_118602_2406155209);
				T2406155209_16 = addInt(count0, LOC10);
				count0 = (NI)(T2406155209_16);
				nimln(152, "vector.nim");
				{
					TY118097* newsymbols0;
					NI T2406155209_17;
					if (!(count0 < (*HEX3Aenv_118943_2406155209).veclength118214)) goto LA13;
					nimln(153, "vector.nim");
					T2406155209_17 = subInt((*HEX3Aenv_118943_2406155209).veclength118214, count0);
					newsymbols0 = getcombinationsforlength_118212_2406155209((NI)(T2406155209_17), uptovec0);
					{
						TY118098* s_118802_2406155209;
						NI i_118958_2406155209;
						NI L_118960_2406155209;
						s_118802_2406155209 = (TY118098*)0;
						nimln(3423, "system.nim");
						i_118958_2406155209 = ((NI) 0);
						nimln(3424, "system.nim");
						L_118960_2406155209 = (newsymbols0 ? newsymbols0->Sup.len : 0);
						{
							nimln(3425, "system.nim");
							while (1) {
								TY118098* nres0;
								TY118804 LOC18;
								NI T2406155209_18;
								if (!(i_118958_2406155209 < L_118960_2406155209)) goto LA17;
								nimln(3426, "system.nim");
								if ((NU)(i_118958_2406155209) >= (NU)(newsymbols0->Sup.len)) raiseIndexError();
								s_118802_2406155209 = newsymbols0->data[i_118958_2406155209];
								nimln(155, "vector.nim");
								memset((void*)LOC18, 0, sizeof(LOC18));
								genericSeqAssign((&LOC18[0]), res0, (&NTI118098));
								genericSeqAssign((&LOC18[1]), s_118802_2406155209, (&NTI118098));
								nres0 = concat_118812_1556796702(LOC18, 2);
								nimln(156, "vector.nim");
								result0 = (TY118097*) incrSeqV2(&(result0)->Sup, sizeof(TY118098*));
								genericSeqAssign((&result0->data[result0->Sup.len]), nres0, (&NTI118098));
								++result0->Sup.len;
								nimln(3427, "system.nim");
								T2406155209_18 = addInt(i_118958_2406155209, ((NI) 1));
								i_118958_2406155209 = (NI)(T2406155209_18);
								nimln(3428, "system.nim");
								{
									if (!!(((newsymbols0 ? newsymbols0->Sup.len : 0) == L_118960_2406155209))) goto LA21;
									failedassertimpl_90839_1689653243(((NimStringDesc*) &T2406155209_19));
								}
								LA21: ;
							} LA17: ;
						}
					}
					nimln(157, "vector.nim");
					count0 = ((NI) 0);
				}
				goto LA11;
				LA13: ;
				{
					nimln(159, "vector.nim");
					count0 = ((NI) 0);
					nimln(160, "vector.nim");
					result0 = (TY118097*) incrSeqV2(&(result0)->Sup, sizeof(TY118098*));
					genericSeqAssign((&result0->data[result0->Sup.len]), res0, (&NTI118098));
					++result0->Sup.len;
				}
				LA11: ;
				nimln(3427, "system.nim");
				T2406155209_20 = addInt(i_118964_2406155209, ((NI) 1));
				i_118964_2406155209 = (NI)(T2406155209_20);
				nimln(3428, "system.nim");
				{
					if (!!(((HEX3Atmp_118961_2406155209 ? HEX3Atmp_118961_2406155209->Sup.len : 0) == L_118966_2406155209))) goto LA26;
					failedassertimpl_90839_1689653243(((NimStringDesc*) &T2406155209_19));
				}
				LA26: ;
			} LA8: ;
		}
	}
	popFrame();
	return result0;
}

static N_INLINE(Cell47305*, usrtocell_51440_1689653243)(void* usr0) {
	Cell47305* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell47305*)0;
	nimln(131, "gc.nim");
	result0 = ((Cell47305*) ((NI)((NU32)(((NI) (usr0))) - (NU32)(((NI)sizeof(Cell47305))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_52601_1689653243)(Cell47305* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(211, "gc.nim");
	addzct_51417_1689653243((&gch_49858_1689653243.zct), c0);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p0) {
	Cell47305* c0;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(253, "gc.nim");
	c0 = usrtocell_51440_1689653243(p0);
	nimln(255, "gc.nim");
	{
		nimln(177, "gc.nim");
		(*c0).refcount -= ((NI) 8);
		nimln(178, "gc.nim");
		if (!((NU32)((*c0).refcount) < (NU32)(((NI) 8)))) goto LA3;
		nimln(256, "gc.nim");
		rtladdzct_52601_1689653243(c0);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(TY14805*, componentgetters_118967_2406155209)(NIM_CHAR c0, NimStringDesc* sm0) {
	TY14805* result0;
	nimfr("componentGetters", "vector.nim")
	result0 = (TY14805*)0;
	nimln(163, "vector.nim");
	switch (((NU8)(c0))) {
	case 86:
	{
		TY118973 LOC2;
		NimStringDesc* LOC3;
		nimln(164, "vector.nim");
		result0 = (TY14805*) newSeq((&NTI14805), 1);
		memset((void*)LOC2, 0, sizeof(LOC2));
		LOC2[0] = copyString(sm0);
		LOC3 = (NimStringDesc*)0;
		LOC3 = result0->data[0]; result0->data[0] = copyStringRC1(LOC2[0]);
		if (LOC3) nimGCunrefNoCycle(LOC3);
	}
	break;
	default:
	{
		NI size0;
		NimStringDesc* LOC5;
		nimln(166, "vector.nim");
		result0 = (TY14805*) newSeq((&NTI14805), 0);
		nimln(167, "vector.nim");
		LOC5 = (NimStringDesc*)0;
		LOC5 = nimCharToStr(c0);
		size0 = nsuParseInt(LOC5);
		{
			NI i_119012_2406155209;
			NI HEX3Atmp_119026_2406155209;
			NI T2406155209_21;
			NI res_119029_2406155209;
			i_119012_2406155209 = (NI)0;
			HEX3Atmp_119026_2406155209 = (NI)0;
			nimln(168, "vector.nim");
			T2406155209_21 = subInt(size0, ((NI) 1));
			HEX3Atmp_119026_2406155209 = (NI)(T2406155209_21);
			nimln(1873, "system.nim");
			res_119029_2406155209 = ((NI) 0);
			{
				nimln(1874, "system.nim");
				while (1) {
					TY119013 LOC9;
					NimStringDesc* LOC10;
					NimStringDesc* LOC11;
					NI T2406155209_23;
					if (!(res_119029_2406155209 <= HEX3Atmp_119026_2406155209)) goto LA8;
					nimln(1875, "system.nim");
					i_119012_2406155209 = res_119029_2406155209;
					nimln(169, "vector.nim");
					memset((void*)LOC9, 0, sizeof(LOC9));
					LOC9[0] = copyString(sm0);
					LOC9[1] = nimIntToStr(i_119012_2406155209);
					LOC10 = (NimStringDesc*)0;
					LOC10 = nsuFormatOpenArray(((NimStringDesc*) &T2406155209_22), LOC9, 2);
					result0 = (TY14805*) incrSeqV2(&(result0)->Sup, sizeof(NimStringDesc*));
					LOC11 = (NimStringDesc*)0;
					LOC11 = result0->data[result0->Sup.len]; result0->data[result0->Sup.len] = copyStringRC1(LOC10);
					if (LOC11) nimGCunrefNoCycle(LOC11);
					++result0->Sup.len;
					nimln(1894, "system.nim");
					T2406155209_23 = addInt(res_119029_2406155209, ((NI) 1));
					res_119029_2406155209 = (NI)(T2406155209_23);
				} LA8: ;
			}
		}
	}
	break;
	}
	popFrame();
	return result0;
}

N_NIMCALL(TY14805*, parameterconstructor_119033_2406155209)(NIM_CHAR c0, NimStringDesc* sm0) {
	TY14805* result0;
	nimfr("parameterConstructor", "vector.nim")
	result0 = (TY14805*)0;
	nimln(173, "vector.nim");
	switch (((NU8)(c0))) {
	case 86:
	{
		TY118973 LOC2;
		TY118973 LOC3;
		NimStringDesc* LOC4;
		nimln(174, "vector.nim");
		result0 = (TY14805*) newSeq((&NTI14805), 1);
		memset((void*)LOC2, 0, sizeof(LOC2));
		memset((void*)LOC3, 0, sizeof(LOC3));
		LOC3[0] = copyString(sm0);
		LOC2[0] = nsuFormatOpenArray(((NimStringDesc*) &T2406155209_24), LOC3, 1);
		LOC4 = (NimStringDesc*)0;
		LOC4 = result0->data[0]; result0->data[0] = copyStringRC1(LOC2[0]);
		if (LOC4) nimGCunrefNoCycle(LOC4);
	}
	break;
	default:
	{
		NI size0;
		NimStringDesc* LOC6;
		TY119013 LOC7;
		NimStringDesc* LOC8;
		NimStringDesc* LOC9;
		nimln(176, "vector.nim");
		result0 = (TY14805*) newSeq((&NTI14805), 0);
		nimln(177, "vector.nim");
		LOC6 = (NimStringDesc*)0;
		LOC6 = nimCharToStr(c0);
		size0 = nsuParseInt(LOC6);
		nimln(178, "vector.nim");
		memset((void*)LOC7, 0, sizeof(LOC7));
		LOC7[0] = copyString(sm0);
		LOC7[1] = nimIntToStr(size0);
		LOC8 = (NimStringDesc*)0;
		LOC8 = nsuFormatOpenArray(((NimStringDesc*) &T2406155209_25), LOC7, 2);
		result0 = (TY14805*) incrSeqV2(&(result0)->Sup, sizeof(NimStringDesc*));
		LOC9 = (NimStringDesc*)0;
		LOC9 = result0->data[result0->Sup.len]; result0->data[result0->Sup.len] = copyStringRC1(LOC8);
		if (LOC9) nimGCunrefNoCycle(LOC9);
		++result0->Sup.len;
	}
	break;
	}
	popFrame();
	return result0;
}

N_NIMCALL(TY14805*, repeatstr_119083_2406155209)(NimStringDesc* a0, NI n0) {
	TY14805* result0;
	nimfr("repeatStr", "vector.nim")
	result0 = (TY14805*)0;
	nimln(181, "vector.nim");
	result0 = (TY14805*) newSeq((&NTI14805), 0);
	{
		NI i_119114_2406155209;
		NI res_119128_2406155209;
		i_119114_2406155209 = (NI)0;
		nimln(1873, "system.nim");
		res_119128_2406155209 = ((NI) 1);
		{
			nimln(1874, "system.nim");
			while (1) {
				NimStringDesc* LOC4;
				NI T2406155209_26;
				if (!(res_119128_2406155209 <= n0)) goto LA3;
				nimln(1875, "system.nim");
				i_119114_2406155209 = res_119128_2406155209;
				nimln(183, "vector.nim");
				result0 = (TY14805*) incrSeqV2(&(result0)->Sup, sizeof(NimStringDesc*));
				LOC4 = (NimStringDesc*)0;
				LOC4 = result0->data[result0->Sup.len]; result0->data[result0->Sup.len] = copyStringRC1(a0);
				if (LOC4) nimGCunrefNoCycle(LOC4);
				++result0->Sup.len;
				nimln(1894, "system.nim");
				T2406155209_26 = addInt(res_119128_2406155209, ((NI) 1));
				res_119128_2406155209 = (NI)(T2406155209_26);
			} LA3: ;
		}
	}
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, glm_vectorInit000)(void) {
	nimfr("vector", "vector.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, glm_vectorDatInit000)(void) {
static TNimNode* T2406155209_11[2];
static TNimNode T2406155209_0[3];
NTI118098.size = sizeof(TY118098*);
NTI118098.kind = 24;
NTI118098.base = (&NTI136);
NTI118098.flags = 2;
NTI118098.marker = T2406155209_4;
NTI118097.size = sizeof(TY118097*);
NTI118097.kind = 24;
NTI118097.base = (&NTI118098);
NTI118097.flags = 2;
NTI118097.marker = T2406155209_5;
NTI118938.size = sizeof(TY118938);
NTI118938.kind = 18;
NTI118938.base = 0;
NTI118938.flags = 3;
T2406155209_11[0] = &T2406155209_0[1];
T2406155209_0[1].kind = 1;
T2406155209_0[1].offset = offsetof(TY118938, HEX3Astate);
T2406155209_0[1].typ = (&NTI101021);
T2406155209_0[1].name = ":state";
T2406155209_11[1] = &T2406155209_0[2];
T2406155209_0[2].kind = 1;
T2406155209_0[2].offset = offsetof(TY118938, veclength118214);
T2406155209_0[2].typ = (&NTI104);
T2406155209_0[2].name = "vecLength118214";
T2406155209_0[0].len = 2; T2406155209_0[0].kind = 2; T2406155209_0[0].sons = &T2406155209_11[0];
NTI118938.node = &T2406155209_0[0];
NTI118937.size = sizeof(TY118938*);
NTI118937.kind = 22;
NTI118937.base = (&NTI118938);
NTI118937.flags = 2;
NTI118937.marker = T2406155209_12;
}

