/* Generated by Nim Compiler v0.14.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/john/code/Nim/lib -o /media/sf_D_DRIVE/Work/Code/nim-raytracer/src/src/nimcache/gradient.o /media/sf_D_DRIVE/Work/Code/nim-raytracer/src/src/nimcache/gradient.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
typedef struct Framebufobj153002 Framebufobj153002;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell47305 Cell47305;
typedef struct Cellseq47321 Cellseq47321;
typedef struct Gcheap49818 Gcheap49818;
typedef struct Gcstack49816 Gcstack49816;
typedef struct Memregion29485 Memregion29485;
typedef struct Smallchunk29439 Smallchunk29439;
typedef struct Llchunk29479 Llchunk29479;
typedef struct Bigchunk29441 Bigchunk29441;
typedef struct Intset29414 Intset29414;
typedef struct Trunk29410 Trunk29410;
typedef struct Avlnode29483 Avlnode29483;
typedef struct Gcstat49814 Gcstat49814;
typedef struct Cellset47317 Cellset47317;
typedef struct Pagedesc47313 Pagedesc47313;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY153031 TY153031;
typedef struct Basechunk29437 Basechunk29437;
typedef struct Freecell29429 Freecell29429;
typedef NF32 TY151018[3];
typedef NF32 TY155127[1];
typedef NF32 TY155181[2];
typedef struct {
N_NIMCALL_PTR(NF32, ClPrc) (NF32 a_155705_2824150814, NF32 b_155707_2824150814, void* ClEnv);
void* ClEnv;
} TY155703;
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, Globalmarkerproc55802) (void);
struct  Cell47305  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47321  {
NI len;
NI cap;
Cell47305** d;
};
typedef Smallchunk29439* TY29500[512];
typedef Trunk29410* Trunkbuckets29412[256];
struct  Intset29414  {
Trunkbuckets29412 data;
};
struct  Memregion29485  {
NI minlargeobj;
NI maxlargeobj;
TY29500 freesmallchunks;
Llchunk29479* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk29441* freechunkslist;
Intset29414 chunkstarts;
Avlnode29483* root;
Avlnode29483* deleted;
Avlnode29483* last;
Avlnode29483* freeavlnodes;
NIM_BOOL locked;
};
struct  Gcstat49814  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset47317  {
NI counter;
NI max;
Pagedesc47313* head;
Pagedesc47313** data;
};
struct  Gcheap49818  {
Gcstack49816* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47321 zct;
Cellseq47321 decstack;
Cellseq47321 tempstack;
NI recgclock;
Memregion29485 region;
Gcstat49814 stat;
Cellset47317 marked;
Cellseq47321 additionalroots;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Framebufobj153002  {
NI w;
NI h;
TY153031* data;
};
struct  Gcstack49816  {
Gcstack49816* prev;
Gcstack49816* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk29437  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk29439  {
  Basechunk29437 Sup;
Smallchunk29439* next;
Smallchunk29439* prev;
Freecell29429* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk29479  {
NI size;
NI acc;
Llchunk29479* next;
};
struct  Bigchunk29441  {
  Basechunk29437 Sup;
Bigchunk29441* next;
Bigchunk29441* prev;
NI align;
NF data;
};
typedef NI TY29418[16];
struct  Trunk29410  {
Trunk29410* next;
NI key;
TY29418 bits;
};
typedef Avlnode29483* TY29490[2];
struct  Avlnode29483  {
TY29490 link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc47313  {
Pagedesc47313* next;
NI key;
TY29418 bits;
};
struct  Freecell29429  {
Freecell29429* next;
NI zerofield;
};
struct TY153031 {
  TGenericSeq Sup;
  NF32 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, vec3_155068_140325102)(TY151018 a0, TY151018 Result);
N_NIMCALL(NF32, HEX5BHEX5D_155082_140325102)(TY151018 v0, NI ix0);
N_NIMCALL(void, vec3_155121_140325102)(TY155127 a0, NF32 b0, TY155127 c0, TY151018 Result);
N_NIMCALL(NF32, HEX5BHEX5D_155143_140325102)(TY155127 v0, NI ix0);
N_NIMCALL(void, vec3_155172_140325102)(TY155127 a0, TY155181 b0, TY151018 Result);
N_NIMCALL(NF32, HEX5BHEX5D_155202_140325102)(TY155181 v0, NI ix0);
N_NIMCALL(void, vec3_155231_140325102)(NF32 a0, TY155181 b0, TY151018 Result);
N_NIMCALL(void, vec3_155270_140325102)(NF32 a0, TY155127 b0, NF32 c0, TY151018 Result);
N_NIMCALL(void, vec3_155301_140325102)(NF32 a0, NF32 b0, TY155127 c0, TY151018 Result);
N_NIMCALL(void, vec3_155332_140325102)(TY155127 a0, TY155127 b0, NF32 c0, TY151018 Result);
N_NIMCALL(void, vec3_155386_140325102)(TY155127 a0, TY155127 b0, TY155127 c0, TY151018 Result);
N_NIMCALL(void, vec3_155439_140325102)(NF32 a0, TY151018 Result);
N_NIMCALL(void, vec3_155455_140325102)(TY155127 a0, NF32 b0, NF32 c0, TY151018 Result);
N_NIMCALL(void, vec3_155486_140325102)(TY155181 a0, NF32 b0, TY151018 Result);
N_NIMCALL(void, vec3_155525_140325102)(NF32 a0, TY155127 b0, TY155127 c0, TY151018 Result);
N_NIMCALL(void, vec3_155567_140325102)(TY155181 a0, TY155127 b0, TY151018 Result);
N_NIMCALL(void, HEX2B_155645_140325102)(TY151018 v0, TY151018 u0, TY151018 Result);
N_NIMCALL(void, zipwith_155692_2824150814)(TY151018 a0, TY151018 b0, TY155703 op0, TY151018 Result);
N_NIMCALL(void, horizgradient_155001_544778878)(Framebufobj153002** fb0, NI ox0, NI oy0, NI w0, NI h0, TY151018 c10, TY151018 c20, NIM_BOOL srgb0);
N_NIMCALL(NF32, r_151024_140325102)(TY151018 v0);
N_NIMCALL(NF32, g_151038_140325102)(TY151018 v0);
N_NIMCALL(NF32, b_151052_140325102)(TY151018 v0);
N_NIMCALL(void, vec3_151066_140325102)(NF32 a0, NF32 b0, NF32 c0, TY151018 Result);
N_NOINLINE(void, chckNil)(void* p0);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0);
N_NOINLINE(void, raiseRangeError)(NI64 val0);
N_NIMCALL(void, srgbtolinear_151011_2725535669)(TY151018 c0, TY151018 Result);
N_NIMCALL(void, rect_154219_623370228)(Framebufobj153002** fb0, NI ox0, NI oy0, NI w0, NI h0, TY151018 color0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_21201_1689653243)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NI, mulInt)(NI a0, NI b0);
N_NIMCALL(void, nimGCvisit)(void* d0, NI op0);
N_NIMCALL(void, T544778878_7)();
N_NIMCALL(void, nimRegisterGlobalMarker)(Globalmarkerproc55802 markerproc0);
N_NIMCALL(Framebufobj153002*, newframebuf_153010_623370228)(NI w0, NI h0);
static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0);
static N_INLINE(Cell47305*, usrtocell_51440_1689653243)(void* usr0);
static N_INLINE(void, rtladdzct_52601_1689653243)(Cell47305* c0);
N_NOINLINE(void, addzct_51417_1689653243)(Cellseq47321* s0, Cell47305* c0);
N_NIMCALL(void, genericReset)(void* dest0, TNimType* mt0);
N_NIMCALL(NIM_BOOL, writeppm_154276_623370228)(Framebufobj153002* fb0, NimStringDesc* filename0, NI bits0, NIM_BOOL srgb0);
static N_INLINE(void, initStackBottomWith)(void* locals0);
N_NOINLINE(void, setStackBottom)(void* thestackbottom0);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_arrayUtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_arrayUtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_vectorInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_vectorDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_functionsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_functionsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_vecInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_vecDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_matrixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_matrixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_matInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_matDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_globalsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_globalsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_mat_transformInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_mat_transformDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_glmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glm_glmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_colorInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_colorDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_mathutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_mathutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_framebufInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_framebufDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, gradientInit000)(void);
NIM_EXTERNC N_NOINLINE(void, gradientDatInit000)(void);
STRING_LITERAL(T544778878_21, "out/gradient.ppm", 16);
extern TFrame* frameptr_18436_1689653243;
NI Barheight_155744_544778878;
NI Ypad_155745_544778878;
NI Width_155747_544778878;
NI Height_155748_544778878;
Framebufobj153002* fb_155749_544778878;
extern TNimType NTI153004; /* Framebuf */
extern Gcheap49818 gch_49858_1689653243;
NI y_155936_544778878;
TY151018 c1_156122_544778878;
extern TNimType NTI151018; /* array[0..2, float32] */
TY151018 c2_156308_544778878;

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU32)(a0) + (NU32)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (a0 <= i0);
		if (!(LOC3)) goto LA4;
		LOC3 = (i0 <= b0);
		LA4: ;
		if (!LOC3) goto LA5;
		result0 = i0;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i0)));
	}
	LA1: ;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_18436_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_18436_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_18436_1689653243;
	frameptr_18436_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_21201_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_18436_1689653243 = (*frameptr_18436_1689653243).prev;
}

N_NIMCALL(void, horizgradient_155001_544778878)(Framebufobj153002** fb0, NI ox0, NI oy0, NI w0, NI h0, TY151018 c10, TY151018 c20, NIM_BOOL srgb0) {
	NF32 sr0;
	NF32 LOC1;
	NF32 LOC2;
	NF32 sg0;
	NF32 LOC3;
	NF32 LOC4;
	NF32 sb0;
	NF32 LOC5;
	NF32 LOC6;
	TY151018 dc0;
	TY151018 c0;
	TY151018 cc0;
	nimfr("horizGradient", "gradient.nim")
	nimln(11, "gradient.nim");
	LOC1 = (NF32)0;
	LOC1 = r_151024_140325102(c20);
	LOC2 = (NF32)0;
	LOC2 = r_151024_140325102(c10);
	sr0 = ((NF32)(((NF32)(LOC1) - (NF32)(LOC2))) / (NF32)(((NF32) (w0))));
	nimln(12, "gradient.nim");
	LOC3 = (NF32)0;
	LOC3 = g_151038_140325102(c20);
	LOC4 = (NF32)0;
	LOC4 = g_151038_140325102(c10);
	sg0 = ((NF32)(((NF32)(LOC3) - (NF32)(LOC4))) / (NF32)(((NF32) (w0))));
	nimln(13, "gradient.nim");
	LOC5 = (NF32)0;
	LOC5 = b_151052_140325102(c20);
	LOC6 = (NF32)0;
	LOC6 = b_151052_140325102(c10);
	sb0 = ((NF32)(((NF32)(LOC5) - (NF32)(LOC6))) / (NF32)(((NF32) (w0))));
	memset((void*)dc0, 0, sizeof(dc0));
	nimln(15, "gradient.nim");
	chckNil((void*)dc0);
	memset((void*)dc0, 0, sizeof(dc0));
	vec3_151066_140325102(sr0, sg0, sb0, dc0);
	memset((void*)c0, 0, sizeof(c0));
	nimln(18, "gradient.nim");
	memcpy((void*)c0, (NIM_CONST void*)c10, sizeof(TY151018));
	memset((void*)cc0, 0, sizeof(cc0));
	{
		NI x_155643_544778878;
		NI HEX3Atmp_155739_544778878;
		NI T544778878_2;
		NI i_155742_544778878;
		x_155643_544778878 = (NI)0;
		HEX3Atmp_155739_544778878 = (NI)0;
		nimln(20, "gradient.nim");
		T544778878_2 = addInt(((NI) (ox0)), ((NI) (w0)));
		HEX3Atmp_155739_544778878 = (NI)(T544778878_2);
		nimln(3615, "system.nim");
		i_155742_544778878 = ((NI) (ox0));
		{
			nimln(3616, "system.nim");
			while (1) {
				TY151018 LOC15;
				NI T544778878_3;
				if (!(((NI)chckRange(i_155742_544778878, ((NI) (-2147483647 -1)), ((NI) 2147483647))) < ((NI)chckRange(HEX3Atmp_155739_544778878, ((NI) (-2147483647 -1)), ((NI) 2147483647))))) goto LA9;
				nimln(3615, "system.nim");
				x_155643_544778878 = i_155742_544778878;
				nimln(21, "gradient.nim");
				{
					if (!srgb0) goto LA12;
					nimln(22, "gradient.nim");
					chckNil((void*)cc0);
					memset((void*)cc0, 0, sizeof(cc0));
					srgbtolinear_151011_2725535669(c0, cc0);
				}
				goto LA10;
				LA12: ;
				{
					nimln(24, "gradient.nim");
					memcpy((void*)cc0, (NIM_CONST void*)c0, sizeof(TY151018));
				}
				LA10: ;
				nimln(25, "gradient.nim");
				rect_154219_623370228(fb0, ((NI)chckRange(x_155643_544778878, ((NI) 0), ((NI) 2147483647))), oy0, ((NI) 1), h0, cc0);
				nimln(26, "gradient.nim");
				memset((void*)LOC15, 0, sizeof(LOC15));
				HEX2B_155645_140325102(c0, dc0, LOC15);
				memcpy((void*)c0, (NIM_CONST void*)LOC15, sizeof(TY151018));
				nimln(3618, "system.nim");
				T544778878_3 = addInt(i_155742_544778878, ((NI) 1));
				if (T544778878_3 < 0 || T544778878_3 > IL64(4294967294)) raiseOverflow();
				i_155742_544778878 = (NI)(T544778878_3);
			} LA9: ;
		}
	}
	popFrame();
}
N_NIMCALL(void, T544778878_7)() {
	nimGCvisit((void*)fb_155749_544778878, 0);
}

static N_INLINE(Cell47305*, usrtocell_51440_1689653243)(void* usr0) {
	Cell47305* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell47305*)0;
	nimln(131, "gc.nim");
	result0 = ((Cell47305*) ((NI)((NU32)(((NI) (usr0))) - (NU32)(((NI)sizeof(Cell47305))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_52601_1689653243)(Cell47305* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(211, "gc.nim");
	addzct_51417_1689653243((&gch_49858_1689653243.zct), c0);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(271, "gc.nim");
	{
		Cell47305* c0;
		nimln(343, "system.nim");
		if (!!((src0 == NIM_NIL))) goto LA3;
		nimln(272, "gc.nim");
		c0 = usrtocell_51440_1689653243(src0);
		nimln(179, "gc.nim");
		(*c0).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(274, "gc.nim");
	{
		Cell47305* c0;
		nimln(343, "system.nim");
		if (!!(((*dest0) == NIM_NIL))) goto LA7;
		nimln(275, "gc.nim");
		c0 = usrtocell_51440_1689653243((*dest0));
		nimln(276, "gc.nim");
		{
			nimln(177, "gc.nim");
			(*c0).refcount -= ((NI) 8);
			nimln(178, "gc.nim");
			if (!((NU32)((*c0).refcount) < (NU32)(((NI) 8)))) goto LA11;
			nimln(277, "gc.nim");
			rtladdzct_52601_1689653243(c0);
		}
		LA11: ;
	}
	LA7: ;
	nimln(278, "gc.nim");
	(*dest0) = src0;
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals0) {
	setStackBottom(locals0);
}
void PreMainInner() {
	systemInit000();
	stdlib_mathDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_sequtilsDatInit000();
	stdlib_macrosDatInit000();
	glm_arrayUtilsDatInit000();
	glm_vectorDatInit000();
	glm_functionsDatInit000();
	glm_vecDatInit000();
	glm_matrixDatInit000();
	glm_matDatInit000();
	glm_globalsDatInit000();
	glm_mat_transformDatInit000();
	glm_glmDatInit000();
	stdlib_endiansDatInit000();
	HEX00_colorDatInit000();
	HEX00_mathutilsDatInit000();
	HEX00_framebufDatInit000();
	gradientDatInit000();
	stdlib_mathInit000();
	stdlib_parseutilsInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_sequtilsInit000();
	stdlib_macrosInit000();
	glm_arrayUtilsInit000();
	glm_vectorInit000();
	glm_functionsInit000();
	glm_vecInit000();
	glm_matrixInit000();
	glm_matInit000();
	glm_globalsInit000();
	glm_mat_transformInit000();
	glm_glmInit000();
	stdlib_endiansInit000();
	HEX00_colorInit000();
	HEX00_mathutilsInit000();
	HEX00_framebufInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	gradientInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, gradientInit000)(void) {
	NI T544778878_4;
	NI T544778878_5;
	NI T544778878_6;
	TY151018 LOC1;
	NI T544778878_8;
	NI T544778878_9;
	NI T544778878_10;
	NI T544778878_11;
	NI T544778878_12;
	NI T544778878_13;
	NI T544778878_14;
	NI T544778878_15;
	NI T544778878_16;
	NI T544778878_17;
	NI T544778878_18;
	NI T544778878_19;
	NI T544778878_20;
	NIM_BOOL LOC2;
	nimfr("gradient", "gradient.nim")
	nimln(30, "gradient.nim");
	Barheight_155744_544778878 = ((NI) 30);
	nimln(31, "gradient.nim");
	Ypad_155745_544778878 = ((NI) 15);
	nimln(32, "gradient.nim");
	Width_155747_544778878 = ((NI) 500);
	nimln(33, "gradient.nim");
	T544778878_4 = mulInt(Barheight_155744_544778878, ((NI) 2));
	T544778878_5 = addInt((NI)(T544778878_4), Ypad_155745_544778878);
	T544778878_6 = mulInt(((NI) 5), (NI)(T544778878_5));
	Height_155748_544778878 = (NI)(T544778878_6);
nimRegisterGlobalMarker(T544778878_7);
	nimln(35, "gradient.nim");
	asgnRefNoCycle((void**) (&fb_155749_544778878), newframebuf_153010_623370228(((NI)chckRange(Width_155747_544778878, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Height_155748_544778878, ((NI) 0), ((NI) 2147483647)))));
	nimln(36, "gradient.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	vec3_151066_140325102(1.0000000000000000e+00, 1.0000000000000000e+00, 1.0000000000000000e+00, LOC1);
	rect_154219_623370228(&fb_155749_544778878, ((NI) 0), ((NI) 0), ((NI)chckRange(Width_155747_544778878, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Height_155748_544778878, ((NI) 0), ((NI) 2147483647))), LOC1);
	nimln(38, "gradient.nim");
	y_155936_544778878 = ((NI) 0);
	nimln(40, "gradient.nim");
	chckNil((void*)c1_156122_544778878);
	genericReset((void*)c1_156122_544778878, (&NTI151018));
	vec3_151066_140325102(1.0000000000000000e+00, 0.0, 0.0, c1_156122_544778878);
	nimln(41, "gradient.nim");
	chckNil((void*)c2_156308_544778878);
	genericReset((void*)c2_156308_544778878, (&NTI151018));
	vec3_151066_140325102(0.0, 1.0000000000000000e+00, 0.0, c2_156308_544778878);
	nimln(42, "gradient.nim");
	horizgradient_155001_544778878(&fb_155749_544778878, ((NI) 0), ((NI)chckRange(y_155936_544778878, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Width_155747_544778878, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Barheight_155744_544778878, ((NI) 0), ((NI) 2147483647))), c1_156122_544778878, c2_156308_544778878, NIM_FALSE);
	nimln(43, "gradient.nim");
	T544778878_8 = addInt(y_155936_544778878, Barheight_155744_544778878);
	y_155936_544778878 = (NI)(T544778878_8);
	nimln(44, "gradient.nim");
	horizgradient_155001_544778878(&fb_155749_544778878, ((NI) 0), ((NI)chckRange(y_155936_544778878, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Width_155747_544778878, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Barheight_155744_544778878, ((NI) 0), ((NI) 2147483647))), c1_156122_544778878, c2_156308_544778878, NIM_TRUE);
	nimln(46, "gradient.nim");
	T544778878_9 = addInt(Barheight_155744_544778878, Ypad_155745_544778878);
	T544778878_10 = addInt(y_155936_544778878, (NI)(T544778878_9));
	y_155936_544778878 = (NI)(T544778878_10);
	nimln(48, "gradient.nim");
	chckNil((void*)c1_156122_544778878);
	genericReset((void*)c1_156122_544778878, (&NTI151018));
	vec3_151066_140325102(0.0, 1.0000000000000000e+00, 0.0, c1_156122_544778878);
	nimln(49, "gradient.nim");
	chckNil((void*)c2_156308_544778878);
	genericReset((void*)c2_156308_544778878, (&NTI151018));
	vec3_151066_140325102(0.0, 0.0, 1.0000000000000000e+00, c2_156308_544778878);
	nimln(50, "gradient.nim");
	horizgradient_155001_544778878(&fb_155749_544778878, ((NI) 0), ((NI)chckRange(y_155936_544778878, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Width_155747_544778878, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Barheight_155744_544778878, ((NI) 0), ((NI) 2147483647))), c1_156122_544778878, c2_156308_544778878, NIM_FALSE);
	nimln(51, "gradient.nim");
	T544778878_11 = addInt(y_155936_544778878, Barheight_155744_544778878);
	y_155936_544778878 = (NI)(T544778878_11);
	nimln(52, "gradient.nim");
	horizgradient_155001_544778878(&fb_155749_544778878, ((NI) 0), ((NI)chckRange(y_155936_544778878, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Width_155747_544778878, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Barheight_155744_544778878, ((NI) 0), ((NI) 2147483647))), c1_156122_544778878, c2_156308_544778878, NIM_TRUE);
	nimln(54, "gradient.nim");
	T544778878_12 = addInt(Barheight_155744_544778878, Ypad_155745_544778878);
	T544778878_13 = addInt(y_155936_544778878, (NI)(T544778878_12));
	y_155936_544778878 = (NI)(T544778878_13);
	nimln(56, "gradient.nim");
	chckNil((void*)c1_156122_544778878);
	genericReset((void*)c1_156122_544778878, (&NTI151018));
	vec3_151066_140325102(0.0, 0.0, 1.0000000000000000e+00, c1_156122_544778878);
	nimln(57, "gradient.nim");
	chckNil((void*)c2_156308_544778878);
	genericReset((void*)c2_156308_544778878, (&NTI151018));
	vec3_151066_140325102(1.0000000000000000e+00, 0.0, 0.0, c2_156308_544778878);
	nimln(58, "gradient.nim");
	horizgradient_155001_544778878(&fb_155749_544778878, ((NI) 0), ((NI)chckRange(y_155936_544778878, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Width_155747_544778878, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Barheight_155744_544778878, ((NI) 0), ((NI) 2147483647))), c1_156122_544778878, c2_156308_544778878, NIM_FALSE);
	nimln(59, "gradient.nim");
	T544778878_14 = addInt(y_155936_544778878, Barheight_155744_544778878);
	y_155936_544778878 = (NI)(T544778878_14);
	nimln(60, "gradient.nim");
	horizgradient_155001_544778878(&fb_155749_544778878, ((NI) 0), ((NI)chckRange(y_155936_544778878, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Width_155747_544778878, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Barheight_155744_544778878, ((NI) 0), ((NI) 2147483647))), c1_156122_544778878, c2_156308_544778878, NIM_TRUE);
	nimln(62, "gradient.nim");
	T544778878_15 = addInt(Barheight_155744_544778878, Ypad_155745_544778878);
	T544778878_16 = addInt(y_155936_544778878, (NI)(T544778878_15));
	y_155936_544778878 = (NI)(T544778878_16);
	nimln(64, "gradient.nim");
	chckNil((void*)c1_156122_544778878);
	genericReset((void*)c1_156122_544778878, (&NTI151018));
	vec3_151066_140325102(1.0000000000000000e+00, 0.0, 1.0000000000000000e+00, c1_156122_544778878);
	nimln(65, "gradient.nim");
	chckNil((void*)c2_156308_544778878);
	genericReset((void*)c2_156308_544778878, (&NTI151018));
	vec3_151066_140325102(1.0000000000000000e+00, 1.0000000000000000e+00, 0.0, c2_156308_544778878);
	nimln(66, "gradient.nim");
	horizgradient_155001_544778878(&fb_155749_544778878, ((NI) 0), ((NI)chckRange(y_155936_544778878, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Width_155747_544778878, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Barheight_155744_544778878, ((NI) 0), ((NI) 2147483647))), c1_156122_544778878, c2_156308_544778878, NIM_FALSE);
	nimln(67, "gradient.nim");
	T544778878_17 = addInt(y_155936_544778878, Barheight_155744_544778878);
	y_155936_544778878 = (NI)(T544778878_17);
	nimln(68, "gradient.nim");
	horizgradient_155001_544778878(&fb_155749_544778878, ((NI) 0), ((NI)chckRange(y_155936_544778878, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Width_155747_544778878, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Barheight_155744_544778878, ((NI) 0), ((NI) 2147483647))), c1_156122_544778878, c2_156308_544778878, NIM_TRUE);
	nimln(70, "gradient.nim");
	T544778878_18 = addInt(Barheight_155744_544778878, Ypad_155745_544778878);
	T544778878_19 = addInt(y_155936_544778878, (NI)(T544778878_18));
	y_155936_544778878 = (NI)(T544778878_19);
	nimln(72, "gradient.nim");
	chckNil((void*)c1_156122_544778878);
	genericReset((void*)c1_156122_544778878, (&NTI151018));
	vec3_151066_140325102(1.0000000000000000e+00, 1.0000000000000000e+00, 0.0, c1_156122_544778878);
	nimln(73, "gradient.nim");
	chckNil((void*)c2_156308_544778878);
	genericReset((void*)c2_156308_544778878, (&NTI151018));
	vec3_151066_140325102(0.0, 1.0000000000000000e+00, 1.0000000000000000e+00, c2_156308_544778878);
	nimln(74, "gradient.nim");
	horizgradient_155001_544778878(&fb_155749_544778878, ((NI) 0), ((NI)chckRange(y_155936_544778878, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Width_155747_544778878, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Barheight_155744_544778878, ((NI) 0), ((NI) 2147483647))), c1_156122_544778878, c2_156308_544778878, NIM_FALSE);
	nimln(75, "gradient.nim");
	T544778878_20 = addInt(y_155936_544778878, Barheight_155744_544778878);
	y_155936_544778878 = (NI)(T544778878_20);
	nimln(76, "gradient.nim");
	horizgradient_155001_544778878(&fb_155749_544778878, ((NI) 0), ((NI)chckRange(y_155936_544778878, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Width_155747_544778878, ((NI) 0), ((NI) 2147483647))), ((NI)chckRange(Barheight_155744_544778878, ((NI) 0), ((NI) 2147483647))), c1_156122_544778878, c2_156308_544778878, NIM_TRUE);
	nimln(78, "gradient.nim");
	LOC2 = (NIM_BOOL)0;
	LOC2 = writeppm_154276_623370228(fb_155749_544778878, ((NimStringDesc*) &T544778878_21), ((NI) 8), NIM_TRUE);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, gradientDatInit000)(void) {
}

