/* Generated by Nim Compiler v0.14.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/john/code/Nim/lib -o /media/sf_D_DRIVE/Work/Code/nim-raytracer/src/src/nimcache/stdlib_strutils.o /media/sf_D_DRIVE/Work/Code/nim-raytracer/src/src/nimcache/stdlib_strutils.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Slice90251 Slice90251;
typedef struct Valueerror3446 Valueerror3446;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell47305 Cell47305;
typedef struct Cellseq47321 Cellseq47321;
typedef struct Gcheap49818 Gcheap49818;
typedef struct Gcstack49816 Gcstack49816;
typedef struct Memregion29485 Memregion29485;
typedef struct Smallchunk29439 Smallchunk29439;
typedef struct Llchunk29479 Llchunk29479;
typedef struct Bigchunk29441 Bigchunk29441;
typedef struct Intset29414 Intset29414;
typedef struct Trunk29410 Trunk29410;
typedef struct Avlnode29483 Avlnode29483;
typedef struct Gcstat49814 Gcstat49814;
typedef struct Cellset47317 Cellset47317;
typedef struct Pagedesc47313 Pagedesc47313;
typedef struct Basechunk29437 Basechunk29437;
typedef struct Freecell29429 Freecell29429;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Slice90251  {
NI a;
NI b;
};
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Valueerror3446  {
  Exception Sup;
};
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell47305  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47321  {
NI len;
NI cap;
Cell47305** d;
};
typedef Smallchunk29439* TY29500[512];
typedef Trunk29410* Trunkbuckets29412[256];
struct  Intset29414  {
Trunkbuckets29412 data;
};
struct  Memregion29485  {
NI minlargeobj;
NI maxlargeobj;
TY29500 freesmallchunks;
Llchunk29479* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk29441* freechunkslist;
Intset29414 chunkstarts;
Avlnode29483* root;
Avlnode29483* deleted;
Avlnode29483* last;
Avlnode29483* freeavlnodes;
NIM_BOOL locked;
};
struct  Gcstat49814  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset47317  {
NI counter;
NI max;
Pagedesc47313* head;
Pagedesc47313** data;
};
struct  Gcheap49818  {
Gcstack49816* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47321 zct;
Cellseq47321 decstack;
Cellseq47321 tempstack;
NI recgclock;
Memregion29485 region;
Gcstat49814 stat;
Cellset47317 marked;
Cellseq47321 additionalroots;
};
struct  Gcstack49816  {
Gcstack49816* prev;
Gcstack49816* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk29437  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk29439  {
  Basechunk29437 Sup;
Smallchunk29439* next;
Smallchunk29439* prev;
Freecell29429* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk29479  {
NI size;
NI acc;
Llchunk29479* next;
};
struct  Bigchunk29441  {
  Basechunk29437 Sup;
Bigchunk29441* next;
Bigchunk29441* prev;
NI align;
NF data;
};
typedef NI TY29418[16];
struct  Trunk29410  {
Trunk29410* next;
NI key;
TY29418 bits;
};
typedef Avlnode29483* TY29490[2];
struct  Avlnode29483  {
TY29490 link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc47313  {
Pagedesc47313* next;
NI key;
TY29418 bits;
};
struct  Freecell29429  {
Freecell29429* next;
NI zerofield;
};
N_NIMCALL(void, reverse_105048_3792311747)(NimStringDesc** a0, NI a0Len0);
N_NIMCALL(void, reverse_105063_3792311747)(NimStringDesc** a0, NI a0Len0, NI first0, NI last0);
static N_INLINE(NIM_BOOL, contains_108277_1689653243)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0);
static N_INLINE(NI, find_108287_1689653243)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_21201_1689653243)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, contains_108452_1689653243)(Slice90251 s0, NI value0);
N_NIMCALL(NF, round_108463_1009420244)(NF x0, NI places0);
static N_INLINE(void, HEX2AHEX3D_108493_1689653243)(NF* x0, NF y0);
static N_INLINE(void, HEX2BHEX3D_108503_1689653243)(NF* x0, NF y0);
N_NIMCALL(NI, npuParseInt)(NimStringDesc* s0, NI* number0, NI start0);
N_NIMCALL(void*, newObj)(TNimType* typ0, NI size0);
static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0);
static N_INLINE(void, copymem_7285_1689653243)(void* dest0, void* source0, NI size0);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space0);
static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0);
static N_INLINE(Cell47305*, usrtocell_51440_1689653243)(void* usr0);
static N_INLINE(void, rtladdzct_52601_1689653243)(Cell47305* c0);
N_NOINLINE(void, addzct_51417_1689653243)(Cellseq47321* s0, Cell47305* c0);
N_NIMCALL(void, raiseException)(Exception* e0, NCSTRING ename0);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap0);
N_NIMCALL(void, nsuAddf)(NimStringDesc** s0, NimStringDesc* formatstr0, NimStringDesc** a0, NI a0Len0);
N_NOINLINE(void, invalidformatstring_108547_4286263276)(void);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src0);
static N_INLINE(void, nimGCunrefNoCycle)(void* p0);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest0, NI addlen0);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s0, NIM_CHAR c0);
N_NIMCALL(NI, findnormalized_108530_4286263276)(NimStringDesc* x0, NimStringDesc** inarray0, NI inarray0Len0);
N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a0, NimStringDesc* b0);
N_NIMCALL(NIM_CHAR, nsuToLowerAsciiChar)(NIM_CHAR c0);
static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0);
N_NOINLINE(void, raiseRangeError)(NI64 val0);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s0, NI start_79010_1689653243, NI last0);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s0, NI first0, NI last0);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src0);
STRING_LITERAL(T4286263276_4, "invalid integer: ", 17);
STRING_LITERAL(T4286263276_5, "invalid format string", 21);
STRING_LITERAL(T4286263276_7, "", 0);
extern TFrame* frameptr_18436_1689653243;
extern TNimType NTI23025; /* ref ValueError */
extern TNimType NTI3446; /* ValueError */
extern Gcheap49818 gch_49858_1689653243;

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU32)(a0) + (NU32)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_18436_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_18436_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_18436_1689653243;
	frameptr_18436_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_21201_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_18436_1689653243 = (*frameptr_18436_1689653243).prev;
}

static N_INLINE(NI, find_108287_1689653243)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0) {
	NI result0;
	nimfr("find", "system.nim")
{	result0 = (NI)0;
	{
		NIM_CHAR i_108321_1689653243;
		NI i_108334_1689653243;
		i_108321_1689653243 = (NIM_CHAR)0;
		nimln(1964, "system.nim");
		i_108334_1689653243 = ((NI) 0);
		{
			nimln(1965, "system.nim");
			while (1) {
				NI T4286263276_2;
				NI T4286263276_3;
				if (!(i_108334_1689653243 < a0Len0)) goto LA3;
				nimln(1966, "system.nim");
				if ((NU)(i_108334_1689653243) >= (NU)(a0Len0)) raiseIndexError();
				i_108321_1689653243 = a0[i_108334_1689653243];
				nimln(2189, "system.nim");
				{
					if (!((NU8)(i_108321_1689653243) == (NU8)(item0))) goto LA6;
					goto BeforeRet;
				}
				LA6: ;
				nimln(2190, "system.nim");
				T4286263276_2 = addInt(result0, ((NI) 1));
				result0 = (NI)(T4286263276_2);
				nimln(1967, "system.nim");
				T4286263276_3 = addInt(i_108334_1689653243, ((NI) 1));
				i_108334_1689653243 = (NI)(T4286263276_3);
			} LA3: ;
		}
	}
	nimln(2191, "system.nim");
	result0 = ((NI) -1);
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(NIM_BOOL, contains_108277_1689653243)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0) {
	NIM_BOOL result0;
	NI LOC1;
	nimfr("contains", "system.nim")
{	result0 = (NIM_BOOL)0;
	nimln(2196, "system.nim");
	nimln(346, "system.nim");
	nimln(347, "system.nim");
	nimln(2196, "system.nim");
	LOC1 = (NI)0;
	LOC1 = find_108287_1689653243(a0, a0Len0, item0);
	result0 = (((NI) 0) <= LOC1);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(NIM_BOOL, contains_108452_1689653243)(Slice90251 s0, NI value0) {
	NIM_BOOL result0;
	NIM_BOOL LOC1;
	nimfr("contains", "system.nim")
	result0 = (NIM_BOOL)0;
	nimln(1093, "system.nim");
	LOC1 = (NIM_BOOL)0;
	LOC1 = (((NI) (s0.a)) <= ((NI) (value0)));
	if (!(LOC1)) goto LA2;
	LOC1 = (((NI) (value0)) <= ((NI) (s0.b)));
	LA2: ;
	result0 = LOC1;
	popFrame();
	return result0;
}

static N_INLINE(void, HEX2AHEX3D_108493_1689653243)(NF* x0, NF y0) {
	nimfr("*=", "system.nim")
	nimln(3332, "system.nim");
	(*x0) = ((NF)((*x0)) * (NF)(y0));
	popFrame();
}

static N_INLINE(void, HEX2BHEX3D_108503_1689653243)(NF* x0, NF y0) {
	nimfr("+=", "system.nim")
	nimln(3322, "system.nim");
	(*x0) = ((NF)((*x0)) + (NF)(y0));
	popFrame();
}

static N_INLINE(void, copymem_7285_1689653243)(void* dest0, void* source0, NI size0) {
	void* LOC1;
	LOC1 = (void*)0;
	LOC1 = memcpy(dest0, source0, ((size_t) (size0)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0) {
	copymem_7285_1689653243(((void*) ((&(*dest0).data[((*dest0).Sup.len)- 0]))), ((void*) ((*src0).data)), ((NI) ((NI)((*src0).Sup.len + ((NI) 1)))));
	(*dest0).Sup.len += (*src0).Sup.len;
}

static N_INLINE(Cell47305*, usrtocell_51440_1689653243)(void* usr0) {
	Cell47305* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell47305*)0;
	nimln(131, "gc.nim");
	result0 = ((Cell47305*) ((NI)((NU32)(((NI) (usr0))) - (NU32)(((NI)sizeof(Cell47305))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_52601_1689653243)(Cell47305* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(211, "gc.nim");
	addzct_51417_1689653243((&gch_49858_1689653243.zct), c0);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(271, "gc.nim");
	{
		Cell47305* c0;
		nimln(343, "system.nim");
		if (!!((src0 == NIM_NIL))) goto LA3;
		nimln(272, "gc.nim");
		c0 = usrtocell_51440_1689653243(src0);
		nimln(179, "gc.nim");
		(*c0).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(274, "gc.nim");
	{
		Cell47305* c0;
		nimln(343, "system.nim");
		if (!!(((*dest0) == NIM_NIL))) goto LA7;
		nimln(275, "gc.nim");
		c0 = usrtocell_51440_1689653243((*dest0));
		nimln(276, "gc.nim");
		{
			nimln(177, "gc.nim");
			(*c0).refcount -= ((NI) 8);
			nimln(178, "gc.nim");
			if (!((NU32)((*c0).refcount) < (NU32)(((NI) 8)))) goto LA11;
			nimln(277, "gc.nim");
			rtladdzct_52601_1689653243(c0);
		}
		LA11: ;
	}
	LA7: ;
	nimln(278, "gc.nim");
	(*dest0) = src0;
	popFrame();
}

N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s0) {
	NI result0;
	NI L0;
	nimfr("parseInt", "strutils.nim")
	result0 = (NI)0;
	L0 = npuParseInt(s0, (&result0), ((NI) 0));
	{
		NIM_BOOL LOC3;
		Valueerror3446* e_105464_4286263276;
		NimStringDesc* LOC7;
		LOC3 = (NIM_BOOL)0;
		LOC3 = !((L0 == (s0 ? s0->Sup.len : 0)));
		if (LOC3) goto LA4;
		LOC3 = (L0 == ((NI) 0));
		LA4: ;
		if (!LOC3) goto LA5;
		e_105464_4286263276 = (Valueerror3446*)0;
		e_105464_4286263276 = (Valueerror3446*) newObj((&NTI23025), sizeof(Valueerror3446));
		(*e_105464_4286263276).Sup.Sup.m_type = (&NTI3446);
		LOC7 = (NimStringDesc*)0;
		LOC7 = rawNewString(s0->Sup.len + 17);
appendString(LOC7, ((NimStringDesc*) &T4286263276_4));
appendString(LOC7, s0);
		asgnRefNoCycle((void**) (&(*e_105464_4286263276).Sup.message), LOC7);
		raiseException((Exception*)e_105464_4286263276, "ValueError");
	}
	LA5: ;
	popFrame();
	return result0;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p0) {
	Cell47305* c0;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(253, "gc.nim");
	c0 = usrtocell_51440_1689653243(p0);
	nimln(255, "gc.nim");
	{
		nimln(177, "gc.nim");
		(*c0).refcount -= ((NI) 8);
		nimln(178, "gc.nim");
		if (!((NU32)((*c0).refcount) < (NU32)(((NI) 8)))) goto LA3;
		nimln(256, "gc.nim");
		rtladdzct_52601_1689653243(c0);
	}
	LA3: ;
	popFrame();
}

N_NOINLINE(void, invalidformatstring_108547_4286263276)(void) {
	Valueerror3446* e_108552_4286263276;
	NimStringDesc* LOC1;
	nimfr("invalidFormatString", "strutils.nim")
	e_108552_4286263276 = (Valueerror3446*)0;
	e_108552_4286263276 = (Valueerror3446*) newObj((&NTI23025), sizeof(Valueerror3446));
	(*e_108552_4286263276).Sup.Sup.m_type = (&NTI3446);
	LOC1 = (NimStringDesc*)0;
	LOC1 = (*e_108552_4286263276).Sup.message; (*e_108552_4286263276).Sup.message = copyStringRC1(((NimStringDesc*) &T4286263276_5));
	if (LOC1) nimGCunrefNoCycle(LOC1);
	raiseException((Exception*)e_108552_4286263276, "ValueError");
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (a0 <= i0);
		if (!(LOC3)) goto LA4;
		LOC3 = (i0 <= b0);
		LA4: ;
		if (!LOC3) goto LA5;
		result0 = i0;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i0)));
	}
	LA1: ;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NIM_CHAR, nsuToLowerAsciiChar)(NIM_CHAR c0) {
	NIM_CHAR result0;
	nimfr("toLowerAscii", "strutils.nim")
	result0 = (NIM_CHAR)0;
	nimln(207, "strutils.nim");
	{
		NI T4286263276_6;
		nimln(1095, "system.nim");
		if (!(((NU8)(c0)) >= ((NU8)(65)) && ((NU8)(c0)) <= ((NU8)(90)))) goto LA3;
		nimln(208, "strutils.nim");
		T4286263276_6 = addInt(((NI) (((NU8)(c0)))), ((NI) 32));
		result0 = ((NIM_CHAR) (((NI)chckRange((NI)(T4286263276_6), ((NI) 0), ((NI) 255)))));
	}
	goto LA1;
	LA3: ;
	{
		nimln(210, "strutils.nim");
		result0 = c0;
	}
	LA1: ;
	popFrame();
	return result0;
}

N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a0, NimStringDesc* b0) {
	NI result0;
	NI i0;
	NI j0;
	nimfr("cmpIgnoreStyle", "strutils.nim")
	result0 = (NI)0;
	i0 = ((NI) 0);
	j0 = ((NI) 0);
	{
		while (1) {
			NIM_CHAR aa0;
			NIM_CHAR bb0;
			{
				while (1) {
					if (!((NU8)(a0->data[i0]) == (NU8)(95))) goto LA4;
					i0 += ((NI) 1);
				} LA4: ;
			}
			{
				while (1) {
					if (!((NU8)(b0->data[j0]) == (NU8)(95))) goto LA6;
					j0 += ((NI) 1);
				} LA6: ;
			}
			aa0 = nsuToLowerAsciiChar(a0->data[i0]);
			bb0 = nsuToLowerAsciiChar(b0->data[j0]);
			result0 = (NI)(((NI) (((NU8)(aa0)))) - ((NI) (((NU8)(bb0)))));
			{
				NIM_BOOL LOC9;
				LOC9 = (NIM_BOOL)0;
				LOC9 = !((result0 == ((NI) 0)));
				if (LOC9) goto LA10;
				LOC9 = ((NU8)(aa0) == (NU8)(0));
				LA10: ;
				if (!LOC9) goto LA11;
				goto LA1;
			}
			LA11: ;
			i0 += ((NI) 1);
			j0 += ((NI) 1);
		}
	} LA1: ;
	popFrame();
	return result0;
}

N_NIMCALL(NI, findnormalized_108530_4286263276)(NimStringDesc* x0, NimStringDesc** inarray0, NI inarray0Len0) {
	NI result0;
	NI i0;
	nimfr("findNormalized", "strutils.nim")
{	result0 = (NI)0;
	i0 = ((NI) 0);
	{
		while (1) {
			if (!(i0 < (inarray0Len0-1))) goto LA2;
			{
				NI LOC5;
				LOC5 = (NI)0;
				LOC5 = nsuCmpIgnoreStyle(x0, inarray0[i0]);
				if (!(LOC5 == ((NI) 0))) goto LA6;
				result0 = i0;
				goto BeforeRet;
			}
			LA6: ;
			i0 += ((NI) 2);
		} LA2: ;
	}
	result0 = ((NI) -1);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(void, nsuAddf)(NimStringDesc** s0, NimStringDesc* formatstr0, NimStringDesc** a0, NI a0Len0) {
	NI i0;
	NI num0;
	nimfr("addf", "strutils.nim")
	i0 = ((NI) 0);
	num0 = ((NI) 0);
	{
		while (1) {
			if (!(i0 < (formatstr0 ? formatstr0->Sup.len : 0))) goto LA2;
			{
				if (!((NU8)(formatstr0->data[i0]) == (NU8)(36))) goto LA5;
				switch (((NU8)(formatstr0->data[(NI)(i0 + ((NI) 1))]))) {
				case 35:
				{
					{
						if (!((NU32)((a0Len0-1)) < (NU32)(num0))) goto LA10;
						invalidformatstring_108547_4286263276();
					}
					LA10: ;
					(*s0) = resizeString((*s0), a0[num0]->Sup.len + 0);
appendString((*s0), a0[num0]);
					i0 += ((NI) 2);
					num0 += ((NI) 1);
				}
				break;
				case 36:
				{
					(*s0) = addChar((*s0), 36);
					i0 += ((NI) 2);
				}
				break;
				case 49 ... 57:
				case 45:
				{
					NI j0;
					NIM_BOOL negative0;
					NI idx0;
					j0 = ((NI) 0);
					i0 += ((NI) 1);
					negative0 = ((NU8)(formatstr0->data[i0]) == (NU8)(45));
					{
						if (!negative0) goto LA16;
						i0 += ((NI) 1);
					}
					LA16: ;
					{
						while (1) {
							if (!(((NU8)(formatstr0->data[i0])) >= ((NU8)(48)) && ((NU8)(formatstr0->data[i0])) <= ((NU8)(57)))) goto LA19;
							j0 = (NI)((NI)((NI)(j0 * ((NI) 10)) + ((NI) (((NU8)(formatstr0->data[i0]))))) - ((NI) 48));
							i0 += ((NI) 1);
						} LA19: ;
					}
					{
						if (!!(negative0)) goto LA22;
						idx0 = (NI)(j0 - ((NI) 1));
					}
					goto LA20;
					LA22: ;
					{
						idx0 = (NI)(a0Len0 - j0);
					}
					LA20: ;
					{
						if (!((NU32)((a0Len0-1)) < (NU32)(idx0))) goto LA27;
						invalidformatstring_108547_4286263276();
					}
					LA27: ;
					(*s0) = resizeString((*s0), a0[idx0]->Sup.len + 0);
appendString((*s0), a0[idx0]);
				}
				break;
				case 123:
				{
					NI j0;
					NI x0;
					NimStringDesc* LOC32;
					j0 = (NI)(i0 + ((NI) 1));
					{
						while (1) {
							if (!!((((NU8)(formatstr0->data[j0])) == ((NU8)(0)) || ((NU8)(formatstr0->data[j0])) == ((NU8)(125))))) goto LA31;
							j0 += ((NI) 1);
						} LA31: ;
					}
					LOC32 = (NimStringDesc*)0;
					LOC32 = copyStrLast(formatstr0, (NI)(i0 + ((NI) 2)), (NI)(j0 - ((NI) 1)));
					x0 = findnormalized_108530_4286263276(LOC32, a0, a0Len0);
					{
						NIM_BOOL LOC35;
						LOC35 = (NIM_BOOL)0;
						LOC35 = (((NI) 0) <= x0);
						if (!(LOC35)) goto LA36;
						LOC35 = (x0 < (a0Len0-1));
						LA36: ;
						if (!LOC35) goto LA37;
						(*s0) = resizeString((*s0), a0[(NI)(x0 + ((NI) 1))]->Sup.len + 0);
appendString((*s0), a0[(NI)(x0 + ((NI) 1))]);
					}
					goto LA33;
					LA37: ;
					{
						invalidformatstring_108547_4286263276();
					}
					LA33: ;
					i0 = (NI)(j0 + ((NI) 1));
				}
				break;
				case 97 ... 122:
				case 65 ... 90:
				case 128 ... 255:
				case 95:
				{
					NI j0;
					NI x0;
					NimStringDesc* LOC43;
					j0 = (NI)(i0 + ((NI) 1));
					{
						while (1) {
							if (!(((NU8)(formatstr0->data[j0])) >= ((NU8)(97)) && ((NU8)(formatstr0->data[j0])) <= ((NU8)(122)) || ((NU8)(formatstr0->data[j0])) >= ((NU8)(65)) && ((NU8)(formatstr0->data[j0])) <= ((NU8)(90)) || ((NU8)(formatstr0->data[j0])) >= ((NU8)(48)) && ((NU8)(formatstr0->data[j0])) <= ((NU8)(57)) || ((NU8)(formatstr0->data[j0])) >= ((NU8)(128)) && ((NU8)(formatstr0->data[j0])) <= ((NU8)(255)) || ((NU8)(formatstr0->data[j0])) == ((NU8)(95)))) goto LA42;
							j0 += ((NI) 1);
						} LA42: ;
					}
					LOC43 = (NimStringDesc*)0;
					LOC43 = copyStrLast(formatstr0, (NI)(i0 + ((NI) 1)), (NI)(j0 - ((NI) 1)));
					x0 = findnormalized_108530_4286263276(LOC43, a0, a0Len0);
					{
						NIM_BOOL LOC46;
						LOC46 = (NIM_BOOL)0;
						LOC46 = (((NI) 0) <= x0);
						if (!(LOC46)) goto LA47;
						LOC46 = (x0 < (a0Len0-1));
						LA47: ;
						if (!LOC46) goto LA48;
						(*s0) = resizeString((*s0), a0[(NI)(x0 + ((NI) 1))]->Sup.len + 0);
appendString((*s0), a0[(NI)(x0 + ((NI) 1))]);
					}
					goto LA44;
					LA48: ;
					{
						invalidformatstring_108547_4286263276();
					}
					LA44: ;
					i0 = j0;
				}
				break;
				default:
				{
					invalidformatstring_108547_4286263276();
				}
				break;
				}
			}
			goto LA3;
			LA5: ;
			{
				(*s0) = addChar((*s0), formatstr0->data[i0]);
				i0 += ((NI) 1);
			}
			LA3: ;
		} LA2: ;
	}
	popFrame();
}

N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr0, NimStringDesc** a0, NI a0Len0) {
	NimStringDesc* result0;
	nimfr("%", "strutils.nim")
	result0 = (NimStringDesc*)0;
	result0 = rawNewString(((NI) ((NI)((formatstr0 ? formatstr0->Sup.len : 0) + (NI)((NU32)(a0Len0) << (NU32)(((NI) 4)))))));
	nsuAddf((&result0), formatstr0, a0, a0Len0);
	popFrame();
	return result0;
}

N_NIMCALL(NimStringDesc*, nsuJoinSep)(NimStringDesc** a0, NI a0Len0, NimStringDesc* sep0) {
	NimStringDesc* result0;
	nimfr("join", "strutils.nim")
	result0 = (NimStringDesc*)0;
	{
		NI L0;
		if (!(((NI) 0) < a0Len0)) goto LA3;
		L0 = (NI)((sep0 ? sep0->Sup.len : 0) * (NI)(a0Len0 - ((NI) 1)));
		{
			NI i_106267_4286263276;
			NI HEX3Atmp_106288_4286263276;
			NI res_106291_4286263276;
			i_106267_4286263276 = (NI)0;
			HEX3Atmp_106288_4286263276 = (NI)0;
			HEX3Atmp_106288_4286263276 = (a0Len0-1);
			res_106291_4286263276 = ((NI) 0);
			{
				while (1) {
					if (!(res_106291_4286263276 <= HEX3Atmp_106288_4286263276)) goto LA7;
					i_106267_4286263276 = res_106291_4286263276;
					L0 += (a0[i_106267_4286263276] ? a0[i_106267_4286263276]->Sup.len : 0);
					res_106291_4286263276 += ((NI) 1);
				} LA7: ;
			}
		}
		result0 = rawNewString(((NI) (L0)));
		result0 = resizeString(result0, a0[((NI) 0)]->Sup.len + 0);
appendString(result0, a0[((NI) 0)]);
		{
			NI i_106286_4286263276;
			NI HEX3Atmp_106296_4286263276;
			NI res_106299_4286263276;
			i_106286_4286263276 = (NI)0;
			HEX3Atmp_106296_4286263276 = (NI)0;
			HEX3Atmp_106296_4286263276 = (a0Len0-1);
			res_106299_4286263276 = ((NI) 1);
			{
				while (1) {
					if (!(res_106299_4286263276 <= HEX3Atmp_106296_4286263276)) goto LA10;
					i_106286_4286263276 = res_106299_4286263276;
					result0 = resizeString(result0, sep0->Sup.len + 0);
appendString(result0, sep0);
					result0 = resizeString(result0, a0[i_106286_4286263276]->Sup.len + 0);
appendString(result0, a0[i_106286_4286263276]);
					res_106299_4286263276 += ((NI) 1);
				} LA10: ;
			}
		}
	}
	goto LA1;
	LA3: ;
	{
		result0 = copyString(((NimStringDesc*) &T4286263276_7));
	}
	LA1: ;
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void) {
	nimfr("strutils", "strutils.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void) {
}

