/* Generated by Nim Compiler v0.14.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/john/code/Nim/lib -o /media/sf_D_DRIVE/Work/Code/nim-raytracer/src/src/nimcache/stdlib_parseutils.o /media/sf_D_DRIVE/Work/Code/nim-raytracer/src/src/nimcache/stdlib_parseutils.c */
#define NIM_INTBITS 32

#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Overflowerror3440 Overflowerror3440;
typedef struct Arithmeticerror3436 Arithmeticerror3436;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell47305 Cell47305;
typedef struct Cellseq47321 Cellseq47321;
typedef struct Gcheap49818 Gcheap49818;
typedef struct Gcstack49816 Gcstack49816;
typedef struct Memregion29485 Memregion29485;
typedef struct Smallchunk29439 Smallchunk29439;
typedef struct Llchunk29479 Llchunk29479;
typedef struct Bigchunk29441 Bigchunk29441;
typedef struct Intset29414 Intset29414;
typedef struct Trunk29410 Trunk29410;
typedef struct Avlnode29483 Avlnode29483;
typedef struct Gcstat49814 Gcstat49814;
typedef struct Cellset47317 Cellset47317;
typedef struct Pagedesc47313 Pagedesc47313;
typedef struct Basechunk29437 Basechunk29437;
typedef struct Freecell29429 Freecell29429;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Arithmeticerror3436  {
  Exception Sup;
};
struct  Overflowerror3440  {
  Arithmeticerror3436 Sup;
};
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell47305  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47321  {
NI len;
NI cap;
Cell47305** d;
};
typedef Smallchunk29439* TY29500[512];
typedef Trunk29410* Trunkbuckets29412[256];
struct  Intset29414  {
Trunkbuckets29412 data;
};
struct  Memregion29485  {
NI minlargeobj;
NI maxlargeobj;
TY29500 freesmallchunks;
Llchunk29479* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk29441* freechunkslist;
Intset29414 chunkstarts;
Avlnode29483* root;
Avlnode29483* deleted;
Avlnode29483* last;
Avlnode29483* freeavlnodes;
NIM_BOOL locked;
};
struct  Gcstat49814  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset47317  {
NI counter;
NI max;
Pagedesc47313* head;
Pagedesc47313** data;
};
struct  Gcheap49818  {
Gcstack49816* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47321 zct;
Cellseq47321 decstack;
Cellseq47321 tempstack;
NI recgclock;
Memregion29485 region;
Gcstat49814 stat;
Cellset47317 marked;
Cellseq47321 additionalroots;
};
struct  Gcstack49816  {
Gcstack49816* prev;
Gcstack49816* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk29437  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk29439  {
  Basechunk29437 Sup;
Smallchunk29439* next;
Smallchunk29439* prev;
Freecell29429* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk29479  {
NI size;
NI acc;
Llchunk29479* next;
};
struct  Bigchunk29441  {
  Basechunk29437 Sup;
Bigchunk29441* next;
Bigchunk29441* prev;
NI align;
NF data;
};
typedef NI TY29418[16];
struct  Trunk29410  {
Trunk29410* next;
NI key;
TY29418 bits;
};
typedef Avlnode29483* TY29490[2];
struct  Avlnode29483  {
TY29490 link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc47313  {
Pagedesc47313* next;
NI key;
TY29418 bits;
};
struct  Freecell29429  {
Freecell29429* next;
NI zerofield;
};
N_NIMCALL(NI, npuParseBiggestInt)(NimStringDesc* s0, NI64* number0, NI start0);
N_NIMCALL(NI, rawparseint_99757_1912046442)(NimStringDesc* s0, NI64* b0, NI start0);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI64, mulInt64)(NI64 a0, NI64 b0);
static N_INLINE(NI, subInt)(NI a0, NI b0);
static N_INLINE(NI64, subInt64)(NI64 a0, NI64 b0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_21201_1689653243)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void*, newObj)(TNimType* typ0, NI size0);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src0);
static N_INLINE(void, nimGCunrefNoCycle)(void* p0);
static N_INLINE(Cell47305*, usrtocell_51440_1689653243)(void* usr0);
static N_INLINE(void, rtladdzct_52601_1689653243)(Cell47305* c0);
N_NOINLINE(void, addzct_51417_1689653243)(Cellseq47321* s0, Cell47305* c0);
N_NIMCALL(void, raiseException)(Exception* e0, NCSTRING ename0);
N_NIMCALL(NI64, chckRange64)(NI64 i0, NI64 a0, NI64 b0);
STRING_LITERAL(T1912046442_11, "overflow", 8);
extern TFrame* frameptr_18436_1689653243;
extern TNimType NTI23271; /* ref OverflowError */
extern TNimType NTI3440; /* OverflowError */
extern Gcheap49818 gch_49858_1689653243;

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU32)(a0) + (NU32)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU32)(a0) - (NU32)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU32) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI64, subInt64)(NI64 a0, NI64 b0) {
	NI64 result0;
{	result0 = (NI64)0;
	result0 = (NI64)((NU64)(a0) - (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (IL64(0) <= (NI64)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (IL64(0) <= (NI64)(result0 ^ (NI64)((NU64) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_18436_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_18436_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_18436_1689653243;
	frameptr_18436_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_21201_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_18436_1689653243 = (*frameptr_18436_1689653243).prev;
}

N_NIMCALL(NI, rawparseint_99757_1912046442)(NimStringDesc* s0, NI64* b0, NI start0) {
	NI result0;
	NI64 sign0;
	NI i0;
	nimfr("rawParseInt", "parseutils.nim")
	result0 = (NI)0;
	nimln(213, "parseutils.nim");
	sign0 = IL64(-1);
	nimln(214, "parseutils.nim");
	i0 = start0;
	nimln(215, "parseutils.nim");
	{
		NI T1912046442_2;
		if ((NU)(i0) > (NU)(s0->Sup.len)) raiseIndexError();
		if (!((NU8)(s0->data[i0]) == (NU8)(43))) goto LA3;
		T1912046442_2 = addInt(i0, ((NI) 1));
		i0 = (NI)(T1912046442_2);
	}
	goto LA1;
	LA3: ;
	{
		NI T1912046442_3;
		nimln(216, "parseutils.nim");
		if ((NU)(i0) > (NU)(s0->Sup.len)) raiseIndexError();
		if (!((NU8)(s0->data[i0]) == (NU8)(45))) goto LA6;
		nimln(217, "parseutils.nim");
		T1912046442_3 = addInt(i0, ((NI) 1));
		i0 = (NI)(T1912046442_3);
		nimln(218, "parseutils.nim");
		sign0 = IL64(1);
	}
	goto LA1;
	LA6: ;
	LA1: ;
	nimln(219, "parseutils.nim");
	{
		NI64 T1912046442_9;
		NI T1912046442_10;
		nimln(1095, "system.nim");
		if ((NU)(i0) > (NU)(s0->Sup.len)) raiseIndexError();
		if (!(((NU8)(s0->data[i0])) >= ((NU8)(48)) && ((NU8)(s0->data[i0])) <= ((NU8)(57)))) goto LA10;
		nimln(220, "parseutils.nim");
		(*b0) = IL64(0);
		{
			nimln(221, "parseutils.nim");
			while (1) {
				NI64 T1912046442_4;
				NI T1912046442_5;
				NI64 T1912046442_6;
				NI T1912046442_7;
				nimln(1095, "system.nim");
				if ((NU)(i0) > (NU)(s0->Sup.len)) raiseIndexError();
				if (!(((NU8)(s0->data[i0])) >= ((NU8)(48)) && ((NU8)(s0->data[i0])) <= ((NU8)(57)))) goto LA13;
				nimln(222, "parseutils.nim");
				T1912046442_4 = mulInt64((*b0), IL64(10));
				if ((NU)(i0) > (NU)(s0->Sup.len)) raiseIndexError();
				T1912046442_5 = subInt(((NI) (((NU8)(s0->data[i0])))), ((NI) 48));
				T1912046442_6 = subInt64((NI64)(T1912046442_4), ((NI64) ((NI)(T1912046442_5))));
				(*b0) = (NI64)(T1912046442_6);
				nimln(223, "parseutils.nim");
				T1912046442_7 = addInt(i0, ((NI) 1));
				i0 = (NI)(T1912046442_7);
				{
					nimln(224, "parseutils.nim");
					while (1) {
						NI T1912046442_8;
						if ((NU)(i0) > (NU)(s0->Sup.len)) raiseIndexError();
						if (!((NU8)(s0->data[i0]) == (NU8)(95))) goto LA15;
						T1912046442_8 = addInt(i0, ((NI) 1));
						i0 = (NI)(T1912046442_8);
					} LA15: ;
				}
			} LA13: ;
		}
		nimln(225, "parseutils.nim");
		T1912046442_9 = mulInt64((*b0), sign0);
		(*b0) = (NI64)(T1912046442_9);
		nimln(226, "parseutils.nim");
		T1912046442_10 = subInt(i0, start0);
		result0 = (NI)(T1912046442_10);
	}
	LA10: ;
	popFrame();
	return result0;
}

N_NIMCALL(NI, npuParseBiggestInt)(NimStringDesc* s0, NI64* number0, NI start0) {
	NI result0;
	NI64 res0;
	nimfr("parseBiggestInt", "parseutils.nim")
	result0 = (NI)0;
	res0 = (NI64)0;
	nimln(237, "parseutils.nim");
	result0 = rawparseint_99757_1912046442(s0, (&res0), start0);
	nimln(238, "parseutils.nim");
	(*number0) = res0;
	popFrame();
	return result0;
}

static N_INLINE(Cell47305*, usrtocell_51440_1689653243)(void* usr0) {
	Cell47305* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell47305*)0;
	nimln(131, "gc.nim");
	result0 = ((Cell47305*) ((NI)((NU32)(((NI) (usr0))) - (NU32)(((NI)sizeof(Cell47305))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_52601_1689653243)(Cell47305* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(211, "gc.nim");
	addzct_51417_1689653243((&gch_49858_1689653243.zct), c0);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p0) {
	Cell47305* c0;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(253, "gc.nim");
	c0 = usrtocell_51440_1689653243(p0);
	nimln(255, "gc.nim");
	{
		nimln(177, "gc.nim");
		(*c0).refcount -= ((NI) 8);
		nimln(178, "gc.nim");
		if (!((NU32)((*c0).refcount) < (NU32)(((NI) 8)))) goto LA3;
		nimln(256, "gc.nim");
		rtladdzct_52601_1689653243(c0);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(NI, npuParseInt)(NimStringDesc* s0, NI* number0, NI start0) {
	NI result0;
	NI64 res0;
	nimfr("parseInt", "parseutils.nim")
	result0 = (NI)0;
	res0 = (NI64)0;
	nimln(246, "parseutils.nim");
	result0 = npuParseBiggestInt(s0, (&res0), start0);
	nimln(247, "parseutils.nim");
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC5;
		Overflowerror3440* e_99871_1912046442;
		NimStringDesc* LOC9;
		LOC3 = (NIM_BOOL)0;
		LOC3 = NIM_TRUE;
		if (!(LOC3)) goto LA4;
		nimln(248, "parseutils.nim");
		LOC5 = (NIM_BOOL)0;
		LOC5 = (res0 < IL64(-2147483648));
		if (LOC5) goto LA6;
		nimln(351, "system.nim");
		LOC5 = (IL64(2147483647) < res0);
		LA6: ;
		LOC3 = LOC5;
		LA4: ;
		if (!LOC3) goto LA7;
		e_99871_1912046442 = (Overflowerror3440*)0;
		nimln(2512, "system.nim");
		e_99871_1912046442 = (Overflowerror3440*) newObj((&NTI23271), sizeof(Overflowerror3440));
		(*e_99871_1912046442).Sup.Sup.Sup.m_type = (&NTI3440);
		nimln(2513, "system.nim");
		LOC9 = (NimStringDesc*)0;
		LOC9 = (*e_99871_1912046442).Sup.Sup.message; (*e_99871_1912046442).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &T1912046442_11));
		if (LOC9) nimGCunrefNoCycle(LOC9);
		nimln(249, "parseutils.nim");
		raiseException((Exception*)e_99871_1912046442, "OverflowError");
	}
	goto LA1;
	LA7: ;
	{
		nimln(343, "system.nim");
		if (!!((result0 == ((NI) 0)))) goto LA11;
		nimln(251, "parseutils.nim");
		(*number0) = ((NI)chckRange64(res0, ((NI) (-2147483647 -1)), ((NI) 2147483647)));
	}
	goto LA1;
	LA11: ;
	LA1: ;
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void) {
	nimfr("parseutils", "parseutils.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void) {
}

