/* Generated by Nim Compiler v0.14.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/john/code/Nim/lib -o /media/sf_D_DRIVE/Work/Code/nim-raytracer/src/src/nimcache/stdlib_sequtils.o /media/sf_D_DRIVE/Work/Code/nim-raytracer/src/src/nimcache/stdlib_sequtils.c */
#define NIM_INTBITS 32

#include "nimbase.h"
typedef struct TY118098 TY118098;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
struct  TGenericSeq  {
NI len;
NI reserved;
};
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct TY118098 {
  TGenericSeq Sup;
  NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0);
N_NOINLINE(void, raiseRangeError)(NI64 val0);
N_NIMCALL(void*, newSeq)(TNimType* typ0, NI len0);
N_NIMCALL(void, failedassertimpl_90839_1689653243)(NimStringDesc* msg0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_21201_1689653243)(void);
static N_INLINE(void, popFrame)(void);
STRING_LITERAL(T1556796702_6, "len(a) == L seq modified while iterating over it", 48);
extern TNimType NTI118098; /* seq[char] */
extern TFrame* frameptr_18436_1689653243;

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU32)(a0) + (NU32)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (a0 <= i0);
		if (!(LOC3)) goto LA4;
		LOC3 = (i0 <= b0);
		LA4: ;
		if (!LOC3) goto LA5;
		result0 = i0;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i0)));
	}
	LA1: ;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_18436_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_18436_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_18436_1689653243;
	frameptr_18436_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_21201_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_18436_1689653243 = (*frameptr_18436_1689653243).prev;
}

N_NIMCALL(TY118098*, concat_118812_1556796702)(TY118098** seqs0, NI seqs0Len0) {
	TY118098* result0;
	NI L0;
	NI i0;
	nimfr("concat", "sequtils.nim")
	result0 = (TY118098*)0;
	nimln(38, "sequtils.nim");
	L0 = ((NI) 0);
	{
		TY118098* seqitm_118847_1556796702;
		NI i_118905_1556796702;
		seqitm_118847_1556796702 = (TY118098*)0;
		nimln(1964, "system.nim");
		i_118905_1556796702 = ((NI) 0);
		{
			nimln(1965, "system.nim");
			while (1) {
				NI T1556796702_2;
				NI T1556796702_3;
				if (!(i_118905_1556796702 < seqs0Len0)) goto LA3;
				nimln(1966, "system.nim");
				if ((NU)(i_118905_1556796702) >= (NU)(seqs0Len0)) raiseIndexError();
				seqitm_118847_1556796702 = seqs0[i_118905_1556796702];
				nimln(39, "sequtils.nim");
				T1556796702_2 = addInt(L0, (seqitm_118847_1556796702 ? seqitm_118847_1556796702->Sup.len : 0));
				L0 = (NI)(T1556796702_2);
				nimln(1967, "system.nim");
				T1556796702_3 = addInt(i_118905_1556796702, ((NI) 1));
				i_118905_1556796702 = (NI)(T1556796702_3);
			} LA3: ;
		}
	}
	nimln(40, "sequtils.nim");
	result0 = (TY118098*) newSeq((&NTI118098), ((NI)chckRange(L0, ((NI) 0), ((NI) 2147483647))));
	nimln(41, "sequtils.nim");
	i0 = ((NI) 0);
	{
		TY118098* s_118883_1556796702;
		NI i_118915_1556796702;
		s_118883_1556796702 = (TY118098*)0;
		nimln(1964, "system.nim");
		i_118915_1556796702 = ((NI) 0);
		{
			nimln(1965, "system.nim");
			while (1) {
				NI T1556796702_7;
				if (!(i_118915_1556796702 < seqs0Len0)) goto LA6;
				nimln(1966, "system.nim");
				if ((NU)(i_118915_1556796702) >= (NU)(seqs0Len0)) raiseIndexError();
				s_118883_1556796702 = seqs0[i_118915_1556796702];
				{
					NIM_CHAR itm_118892_1556796702;
					NI i_118910_1556796702;
					NI L_118912_1556796702;
					itm_118892_1556796702 = (NIM_CHAR)0;
					nimln(3423, "system.nim");
					i_118910_1556796702 = ((NI) 0);
					nimln(3424, "system.nim");
					L_118912_1556796702 = (s_118883_1556796702 ? s_118883_1556796702->Sup.len : 0);
					{
						nimln(3425, "system.nim");
						while (1) {
							NI T1556796702_4;
							NI T1556796702_5;
							if (!(i_118910_1556796702 < L_118912_1556796702)) goto LA9;
							nimln(3426, "system.nim");
							if ((NU)(i_118910_1556796702) >= (NU)(s_118883_1556796702->Sup.len)) raiseIndexError();
							itm_118892_1556796702 = s_118883_1556796702->data[i_118910_1556796702];
							nimln(44, "sequtils.nim");
							if ((NU)(i0) >= (NU)(result0->Sup.len)) raiseIndexError();
							result0->data[i0] = itm_118892_1556796702;
							nimln(45, "sequtils.nim");
							T1556796702_4 = addInt(i0, ((NI) 1));
							i0 = (NI)(T1556796702_4);
							nimln(3427, "system.nim");
							T1556796702_5 = addInt(i_118910_1556796702, ((NI) 1));
							i_118910_1556796702 = (NI)(T1556796702_5);
							nimln(3428, "system.nim");
							{
								if (!!(((s_118883_1556796702 ? s_118883_1556796702->Sup.len : 0) == L_118912_1556796702))) goto LA12;
								failedassertimpl_90839_1689653243(((NimStringDesc*) &T1556796702_6));
							}
							LA12: ;
						} LA9: ;
					}
				}
				nimln(1967, "system.nim");
				T1556796702_7 = addInt(i_118915_1556796702, ((NI) 1));
				i_118915_1556796702 = (NI)(T1556796702_7);
			} LA6: ;
		}
	}
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void) {
	nimfr("sequtils", "sequtils.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void) {
}

