/* Generated by Nim Compiler v0.14.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, i386, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/john/code/Nim/lib -o /media/sf_D_DRIVE/Work/Code/nim-raytracer/src/src/nimcache/stdlib_algorithm.o /media/sf_D_DRIVE/Work/Code/nim-raytracer/src/src/nimcache/stdlib_algorithm.c */
#define NIM_INTBITS 32

#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY118098 TY118098;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef NU8 Sortorder101004;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TY118098 {
  TGenericSeq Sup;
  NIM_CHAR data[SEQ_DECL_SIZE];
};
static N_INLINE(NI, HEX2A_101008_3792311747)(NI x0, Sortorder101004 order0);
static N_INLINE(NI, subInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_21201_1689653243)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, reverse_105063_3792311747)(NimStringDesc** a0, NI a0Len0, NI first0, NI last0);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void, unsureAsgnRef)(void** dest0, void* src0);
static N_INLINE(NI, addInt)(NI a0, NI b0);
static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0);
N_NOINLINE(void, raiseRangeError)(NI64 val0);
N_NIMCALL(TY118098*, reversed_118366_3792311747)(NIM_CHAR* a0, NI a0Len0, NI first0, NI last0);
N_NIMCALL(void, failedassertimpl_90839_1689653243)(NimStringDesc* msg0);
N_NIMCALL(TY118098*, newseq_118278_1689653243)(NI len0);
STRING_LITERAL(T3792311747_7, "\012  first - 1 <= last ", 21);
extern TFrame* frameptr_18436_1689653243;
extern TNimType NTI104; /* int */
TNimType NTI101021; /* range -1..0(int) */

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU32)(a0) - (NU32)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU32) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_18436_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_18436_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_18436_1689653243;
	frameptr_18436_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_21201_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_18436_1689653243 = (*frameptr_18436_1689653243).prev;
}

static N_INLINE(NI, HEX2A_101008_3792311747)(NI x0, Sortorder101004 order0) {
	NI result0;
	NI y0;
	NI T3792311747_2;
	NI T3792311747_3;
	nimfr("*", "algorithm.nim")
	result0 = (NI)0;
	nimln(24, "algorithm.nim");
	T3792311747_2 = subInt(((NI) (order0)), ((NI) 1));
	y0 = (NI)(T3792311747_2);
	nimln(25, "algorithm.nim");
	T3792311747_3 = subInt((NI)(x0 ^ ((NI) (y0))), ((NI) (y0)));
	result0 = (NI)(T3792311747_3);
	popFrame();
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU32)(a0) + (NU32)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(void, reverse_105063_3792311747)(NimStringDesc** a0, NI a0Len0, NI first0, NI last0) {
	NI x0;
	NI y0;
	nimfr("reverse", "algorithm.nim")
	nimln(40, "algorithm.nim");
	x0 = first0;
	nimln(41, "algorithm.nim");
	y0 = last0;
	{
		nimln(42, "algorithm.nim");
		while (1) {
			NimStringDesc* LOC3;
			NI T3792311747_4;
			NI T3792311747_5;
			if (!(((NI) (x0)) < ((NI) (y0)))) goto LA2;
			nimln(43, "algorithm.nim");
			LOC3 = (NimStringDesc*)0;
			if ((NU)(x0) >= (NU)(a0Len0)) raiseIndexError();
			if ((NU)(y0) >= (NU)(a0Len0)) raiseIndexError();
			LOC3 = a0[x0];
			unsureAsgnRef((void**) (&a0[x0]), a0[y0]);
			unsureAsgnRef((void**) (&a0[y0]), LOC3);
			nimln(44, "algorithm.nim");
			T3792311747_4 = subInt(y0, ((NI) 1));
			if (T3792311747_4 < 0 || T3792311747_4 > 2147483647) raiseOverflow();
			y0 = (NI)(T3792311747_4);
			nimln(45, "algorithm.nim");
			T3792311747_5 = addInt(x0, ((NI) 1));
			if (T3792311747_5 < 0 || T3792311747_5 > 2147483647) raiseOverflow();
			x0 = (NI)(T3792311747_5);
		} LA2: ;
	}
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (a0 <= i0);
		if (!(LOC3)) goto LA4;
		LOC3 = (i0 <= b0);
		LA4: ;
		if (!LOC3) goto LA5;
		result0 = i0;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i0)));
	}
	LA1: ;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(void, reverse_105048_3792311747)(NimStringDesc** a0, NI a0Len0) {
	nimfr("reverse", "algorithm.nim")
	nimln(49, "algorithm.nim");
	reverse_105063_3792311747(a0, a0Len0, ((NI) 0), ((NI)chckRange((a0Len0-1), ((NI) 0), ((NI) 2147483647))));
	popFrame();
}

N_NIMCALL(TY118098*, reversed_118366_3792311747)(NIM_CHAR* a0, NI a0Len0, NI first0, NI last0) {
	TY118098* result0;
	NI i0;
	NI T3792311747_8;
	NI x0;
	NI T3792311747_9;
	nimfr("reversed", "algorithm.nim")
	result0 = (TY118098*)0;
	nimln(53, "algorithm.nim");
	{
		NI T3792311747_6;
		T3792311747_6 = subInt(((NI) (first0)), ((NI) 1));
		if (!!((((NI) ((NI)(T3792311747_6))) <= last0))) goto LA3;
		failedassertimpl_90839_1689653243(((NimStringDesc*) &T3792311747_7));
	}
	LA3: ;
	nimln(54, "algorithm.nim");
	T3792311747_8 = subInt(last0, ((NI) (first0)));
	i0 = (NI)(T3792311747_8);
	nimln(55, "algorithm.nim");
	x0 = ((NI) (first0));
	nimln(56, "algorithm.nim");
	T3792311747_9 = addInt(i0, ((NI) 1));
	result0 = newseq_118278_1689653243(((NI)chckRange((NI)(T3792311747_9), ((NI) 0), ((NI) 2147483647))));
	{
		nimln(57, "algorithm.nim");
		while (1) {
			NI T3792311747_10;
			NI T3792311747_11;
			nimln(347, "system.nim");
			if (!(((NI) 0) <= i0)) goto LA6;
			nimln(58, "algorithm.nim");
			if ((NU)(i0) >= (NU)(result0->Sup.len)) raiseIndexError();
			if ((NU)(x0) >= (NU)(a0Len0)) raiseIndexError();
			result0->data[i0] = a0[x0];
			nimln(59, "algorithm.nim");
			T3792311747_10 = subInt(i0, ((NI) 1));
			i0 = (NI)(T3792311747_10);
			nimln(60, "algorithm.nim");
			T3792311747_11 = addInt(x0, ((NI) 1));
			x0 = (NI)(T3792311747_11);
		} LA6: ;
	}
	popFrame();
	return result0;
}

N_NIMCALL(TY118098*, reversed_118350_3792311747)(NIM_CHAR* a0, NI a0Len0) {
	TY118098* result0;
	nimfr("reversed", "algorithm.nim")
	result0 = (TY118098*)0;
	nimln(63, "algorithm.nim");
	nimln(64, "algorithm.nim");
	result0 = reversed_118366_3792311747(a0, a0Len0, ((NI) 0), (a0Len0-1));
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void) {
	nimfr("algorithm", "algorithm.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void) {
NTI101021.size = sizeof(NI);
NTI101021.kind = 20;
NTI101021.base = (&NTI104);
NTI101021.flags = 3;
}

